Learn-ARM: main.c File Reference
main.c File Reference
#include "main.h"
Functions
int main (void)
void initialize ()
System initialization.
void configureSystemClock (void)
System clock confoguration.
void HCSR04 (void)
HC-SRO4 configuration.
void trigger (void)
HC-SRO4 trigger.
Function Documentation
configureSystemClock()
void configureSystemClock (void)
System clock confoguration.
This function configures the system clock to 72 MHz. APB2 clock = 72 MHz and APB1 clcok = 36 MHz. HSE clock is 8 MHz and prescaler = 9
Definition at line 27 of file main.c.
References disableHSI(), enableHSE(), enableHSI(), enablePLL(), FLASH_PRFTB_ENABLE, FLASH_WAIT_STATES_TWO, getSWS(), isHSERDY(), isPLLRDY(), RCC_CFGR_HCLK_DIVx2, RCC_CFGR_PLLMULx9, RCC_CFGR_SW_PLL, setAPB1_PSC(), setPLLMULL(), setPLLSRC(), setPRFTB(), setSW(), setUSBPRE(), setWaitStates(), and USB_PLL_DIVx1.
Referenced by initialize().
HCSR04()
void HCSR04 (void)
HC-SRO4 configuration.
This function initializes the ultrasonic sensor and performs the initial configuration of any GPIO and other supporting periphersals
See also
initialize()
Definition at line 63 of file main.c.
References CNF_MODE_INPUT_FLOAT, CNF_MODE_OUTPUT_GP_PP, configurePortPin(), enablePeripheralClock(), GPIO_PIN1, GPIO_PIN8, LOW, MODE_INPUT, MODE_OUTPUT_2MHz, pinState(), PORTA, PORTB, RCC_APB2ENR_IOPAEN, and RCC_APB2ENR_IOPBEN.
Referenced by initialize().
initialize()
void initialize (void)
System initialization.
This function perform all initialization tasks such as the configuration of the system clock, enabling peripheral clocks, enabling peripherals, etc.
Note
The system clcok at this time can only be configured for two speeds
8 MHz
72 MHz
Attention
To configure the system clock for 8 MHz simply change the value of SYS_CLK to 8 and do not call configureSystemClock
Definition at line 13 of file main.c.
References CNF_MODE_INPUT_PULL_UP_DN, configurePortPin(), configureSystemClock(), delays_init(), GPIO_PIN1, GPIO_PIN2, GPIO_PIN3, GPIO_PIN4, GPIO_PIN5, GPIO_PIN6, GPIO_PIN7, HCSR04(), lcdInit(), MODE_INPUT, PORTA, SPI1, and SYS_CLK.
Referenced by main().
main()
int main (void)
Definition at line 3 of file main.c.
References initialize().
Referenced by Reset_Handler().
trigger()
void trigger (void)
HC-SRO4 trigger.
This function initiates a pulse train of at least 10us to trigger the ultrasonic sensor whenever a distance measurement is required
See also
initialize()
Definition at line 74 of file main.c.
References delay_us(), GPIO_PIN1, HIGH, LOW, pinState(), and PORTB.