Learn-ARM: /home/ubuntu/Desktop/repositories/learn-arm/src/c/lib/source/rcc.c File Reference
rcc.c File Reference
#include "../include/rcc.h"
Functions
void enablePeripheralClock (uint32_t p)
bool isHSIRDY (void)
void enableHSE (void)
void disableHSE (void)
void enableHSI (void)
void disableHSI (void)
bool isHSERDY (void)
void enableCSS (void)
void disableCSS (void)
void enablePLL (void)
void disablePLL (void)
bool isPLLRDY (void)
void setSW (uint32_t sw)
uint32_t getSWS (void)
void setAHB_PSC (uint32_t psc)
void setAPB1_PSC (uint32_t psc)
void setPLLSRC (void)
void clearPLLSRC (void)
void setAPB2_PSC (uint32_t psc)
void setPLLXTPRE (void)
void clearPLLXTPRE (void)
void setPLLMULL (uint32_t pll)
void setUSBPRE (uint32_t psc)
Variables
uint32_t * RCC_CR = (uint32_t*)(RCC_BASE + 0x00)
uint32_t * RCC_CFGR = (uint32_t*)(RCC_BASE + 0x04)
uint32_t * RCC_APB2ENR = (uint32_t*)(RCC_BASE + 0x18)
uint32_t * RCC_APB1ENR = (uint32_t*)(RCC_BASE + 0x1C)
Function Documentation
clearPLLSRC()
void clearPLLSRC (void)
Definition at line 116 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_PLLSRC.
clearPLLXTPRE()
void clearPLLXTPRE (void)
Definition at line 131 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_PLLXTPRE.
disableCSS()
void disableCSS (void)
Definition at line 67 of file rcc.c.
References RCC_CR, and RCC_CR_CSSON.
disableHSE()
void disableHSE (void)
Definition at line 39 of file rcc.c.
References RCC_CR, and RCC_CR_HSEON.
disableHSI()
void disableHSI (void)
Definition at line 49 of file rcc.c.
References RCC_CR, and RCC_CR_HSION.
Referenced by configureSystemClock().
disablePLL()
void disablePLL (void)
Definition at line 77 of file rcc.c.
References RCC_CR, and RCC_CR_PLLON.
enableCSS()
void enableCSS (void)
Definition at line 62 of file rcc.c.
References RCC_CR, and RCC_CR_CSSON.
enableHSE()
void enableHSE (void)
Definition at line 34 of file rcc.c.
References RCC_CR, and RCC_CR_HSEON.
Referenced by configureSystemClock().
enableHSI()
void enableHSI (void)
Definition at line 44 of file rcc.c.
References RCC_CR, and RCC_CR_HSION.
Referenced by configureSystemClock().
enablePeripheralClock()
void enablePeripheralClock (uint32_t p)
Definition at line 9 of file rcc.c.
References RCC_APB1ENR, and RCC_APB2ENR.
Referenced by enableSpiClk(), enableTIMxClock(), and HCSR04().
enablePLL()
void enablePLL (void)
Definition at line 72 of file rcc.c.
References RCC_CR, and RCC_CR_PLLON.
Referenced by configureSystemClock().
getSWS()
uint32_t getSWS (void)
Definition at line 95 of file rcc.c.
References RCC_CFGR.
Referenced by configureSystemClock().
isHSERDY()
bool isHSERDY (void)
Definition at line 54 of file rcc.c.
References RCC_CR, and RCC_CR_HSERDY.
Referenced by configureSystemClock().
isHSIRDY()
bool isHSIRDY (void)
Definition at line 26 of file rcc.c.
References RCC_CR, and RCC_CR_HSIRDY.
isPLLRDY()
bool isPLLRDY (void)
Definition at line 82 of file rcc.c.
References RCC_CR, and RCC_CR_PLLRDY.
Referenced by configureSystemClock().
setAHB_PSC()
void setAHB_PSC (uint32_t psc)
Definition at line 101 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_HPRE.
setAPB1_PSC()
void setAPB1_PSC (uint32_t psc)
Definition at line 106 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_PPRE1.
Referenced by configureSystemClock().
setAPB2_PSC()
void setAPB2_PSC (uint32_t psc)
Definition at line 121 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_PPRE2.
setPLLMULL()
void setPLLMULL (uint32_t pll)
Definition at line 136 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_PLLMUL.
Referenced by configureSystemClock().
setPLLSRC()
void setPLLSRC (void)
Definition at line 111 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_PLLSRC.
Referenced by configureSystemClock().
setPLLXTPRE()
void setPLLXTPRE (void)
Definition at line 126 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_PLLXTPRE.
setSW()
void setSW (uint32_t sw)
Definition at line 90 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_SW.
Referenced by configureSystemClock().
setUSBPRE()
void setUSBPRE (uint32_t psc)
Definition at line 141 of file rcc.c.
References RCC_CFGR, RCC_CFGR_USBPRE, and USB_PLL_DIVx1.
Referenced by configureSystemClock().
Variable Documentation
RCC_APB1ENR
uint32_t* RCC_APB1ENR = (uint32_t*)(RCC_BASE + 0x1C)
Definition at line 7 of file rcc.c.
Referenced by enablePeripheralClock().
RCC_APB2ENR
uint32_t* RCC_APB2ENR = (uint32_t*)(RCC_BASE + 0x18)
Definition at line 6 of file rcc.c.
Referenced by enablePeripheralClock().
RCC_CFGR
uint32_t* RCC_CFGR = (uint32_t*)(RCC_BASE + 0x04)
Definition at line 5 of file rcc.c.
Referenced by clearPLLSRC(), clearPLLXTPRE(), getSWS(), setAHB_PSC(), setAPB1_PSC(), setAPB2_PSC(), setPLLMULL(), setPLLSRC(), setPLLXTPRE(), setSW(), and setUSBPRE().
RCC_CR
uint32_t* RCC_CR = (uint32_t*)(RCC_BASE + 0x00)
Definition at line 4 of file rcc.c.
Referenced by disableCSS(), disableHSE(), disableHSI(), disablePLL(), enableCSS(), enableHSE(), enableHSI(), enablePLL(), isHSERDY(), isHSIRDY(), and isPLLRDY().