Learn-ARM: stm32_startup.c File Reference
stm32_startup.c File Reference
#include <stdint.h>
Functions
int main (void)
void Reset_Handler (void)
void NMI_Handler (void)
void Default_Handler (void)
Variables
uint32_t _end_of_text
uint32_t _start_of_data
uint32_t _end_of_data
uint32_t _start_of_bss
uint32_t _end_of_bss
uint32_t _DataLoad
uint32_t _STACK_END
Function Documentation
Default_Handler()
void Default_Handler (void)
Definition at line 155 of file stm32_startup.c.
main()
int main (void)
Definition at line 3 of file main.c.
References initialize().
Referenced by Reset_Handler().
NMI_Handler()
void NMI_Handler (void)
Definition at line 14 of file stm32_startup.c.
Reset_Handler()
void Reset_Handler (void)
Definition at line 130 of file stm32_startup.c.
References _DataLoad, _end_of_bss, _end_of_data, _start_of_bss, _start_of_data, and main().
Variable Documentation
_DataLoad
uint32_t _DataLoad extern
Referenced by Reset_Handler().
_end_of_bss
uint32_t _end_of_bss extern
Referenced by Reset_Handler().
_end_of_data
uint32_t _end_of_data extern
Referenced by Reset_Handler().
_end_of_text
uint32_t _end_of_text extern
_STACK_END
uint32_t _STACK_END extern
_start_of_bss
uint32_t _start_of_bss extern
Referenced by Reset_Handler().
_start_of_data
uint32_t _start_of_data extern
Referenced by Reset_Handler().