Learn-ARM: /home/ubuntu/Desktop/repositories/learn-arm/src/c/lib/source/flash.c File Reference
flash.c File Reference
#include "../include/flash.h"
Functions
bool getPRFTBS (void)
void setPRFTB (uint32_t state)
void setWaitStates (uint32_t latency)
Variables
uint32_t * FLASH_ACR = (uint32_t*)(FLASH_BASE + 0x00)
Function Documentation
getPRFTBS()
bool getPRFTBS (void)
Definition at line 5 of file flash.c.
References FLASH_ACR, and FLASH_ACR_PRFTBS.
setPRFTB()
void setPRFTB (uint32_t state)
Definition at line 13 of file flash.c.
References FLASH_ACR, and FLASH_ACR_PRFTBE.
Referenced by configureSystemClock().
setWaitStates()
void setWaitStates (uint32_t latency)
Definition at line 21 of file flash.c.
References FLASH_ACR, and FLASH_ACR_LATENCY.
Referenced by configureSystemClock().
Variable Documentation
FLASH_ACR
uint32_t* FLASH_ACR = (uint32_t*)(FLASH_BASE + 0x00)
Definition at line 3 of file flash.c.
Referenced by getPRFTBS(), setPRFTB(), and setWaitStates().