Learn-ARM: /home/ubuntu/Desktop/repositories/learn-arm/src/c/lib/include/jlx12864g-086.h File Reference
jlx12864g-086.h File Reference
This header file contains all the function declarations for the LCD module.
#include <stdint.h>
#include <stdbool.h>
#include "spi.h"
#include "delay.h"
#include "gpio.h"
Macros
#define DISPLY_STATE_ON 0xAF
#define DISPLY_STATE_OFF 0xAE
Functions
void println (char *line)
Print line.
void lcdInit (uint32_t module, uint32_t port, uint32_t mosi, uint32_t sck, uint32_t nss, uint32_t rs, uint32_t rst, uint32_t leda, uint32_t sysclk)
LCD initialization and setup.
void sendCMD (uint16_t cmd)
Send a command byte to the LCD This function sends a configuration command to the LCD module.
void sendData (uint16_t data)
Sends a byte of data to LCD This function trabsfers a byte of data to the LCD via the serial interface.
void setDisplayState (uint16_t state)
Sets the display state.
void setCursor (uint32_t x, uint32_t y)
Set the cursor position.
void clearScreen (void)
Clears the LCD screen.
Detailed Description
This header file contains all the function declarations for the LCD module.
Author
Mark R. Jennings mbede.nosp@m.ce@g.nosp@m.mail..nosp@m.com
Date
Auguts 2, 2020
Version
1.0
Definition in file jlx12864g-086.h.
Macro Definition Documentation
DISPLY_STATE_OFF
#define DISPLY_STATE_OFF 0xAE
Definition at line 27 of file jlx12864g-086.h.
DISPLY_STATE_ON
#define DISPLY_STATE_ON 0xAF
Definition at line 26 of file jlx12864g-086.h.
Function Documentation
clearScreen()
void clearScreen (void)
Clears the LCD screen.
This function clears all the pixels on the LCD screens.
Definition at line 218 of file jlx12864g-086.c.
References sendData(), and setCursor().
lcdInit()
void lcdInit (uint32_t module, uint32_t port, uint32_t mosi, uint32_t sck, uint32_t nss, uint32_t rs, uint32_t rst, uint32_t leda, uint32_t sysclk)
LCD initialization and setup.
This function performs LCD initalization and configuration
Parameters
module The selected SPI module (either SPI1 or SPI2)
port The GPIO port for the SPI pins (either PORTA or PORTB)
mosi The port pin for MOSI
sck The port pin for SPI clock
nss The port pin for the slave select
rs The port pin for the RS input on the LCD module
rst The port pin for LCD reset
leda The port pin for the LCD backlight
sysclk The value of the system clock in MHz
Definition at line 143 of file jlx12864g-086.c.
Referenced by initialize().
println()
void println (char * line)
Print line.
This function prints a line of characters to the LCD screen
Parameters
line The string of characters to be displyed on he LCD
Definition at line 123 of file jlx12864g-086.c.
sendCMD()
void sendCMD (uint16_t cmd)
Send a command byte to the LCD This function sends a configuration command to the LCD module.
Parameters
cmd The command to be sent to the LCD
Definition at line 236 of file jlx12864g-086.c.
References enableSPI().
Referenced by setDisplayState().
sendData()
void sendData (uint16_t data)
Sends a byte of data to LCD This function trabsfers a byte of data to the LCD via the serial interface.
Parameters
data The byte of data to be sent
Definition at line 246 of file jlx12864g-086.c.
References enableSPI().
Referenced by clearScreen().
setCursor()
void setCursor (uint32_t x, uint32_t y)
Set the cursor position.
This function takes as arguments the desired coordinates of the cursor
Parameters
x The column index
y The row index
Definition at line 261 of file jlx12864g-086.c.
Referenced by clearScreen().
setDisplayState()
void setDisplayState (uint16_t state)
Sets the display state.
This function enables or disables the LCD display based on the argument passed to it
Parameters
state The command value to enable/disable the LCD module
Definition at line 256 of file jlx12864g-086.c.
References sendCMD().