Learn-ARM: /home/ubuntu/Desktop/repositories/learn-arm/src/c/lib/source/systick.c File Reference
systick.c File Reference
#include "../include/systick.h"
Functions
bool isCountZero (void)
void setCockSource (uint32_t src)
void enableSystickTimer (void)
void disableSystickTimer (void)
void enableException (void)
void disableException (void)
bool isTimerEnabled (void)
bool isExcetionEnabled (void)
void setReloadValue (uint32_t rvr)
uint32_t getCurrentValue (void)
void setCurrentValue (uint32_t value)
Variables
uint32_t * SYST_CSR =(uint32_t*)0xE000E010
uint32_t * SYST_RVR =(uint32_t*)0xE000E014
uint32_t * SYST_CVR =(uint32_t*)0xE000E018
Function Documentation
disableException()
void disableException (void)
Definition at line 39 of file systick.c.
References SYST_CSR, and SYST_CSR_TICKINT.
Referenced by delays_init().
disableSystickTimer()
void disableSystickTimer (void)
Definition at line 29 of file systick.c.
References SYST_CSR, and SYST_CSR_ENABLE.
Referenced by delays_init().
enableException()
void enableException (void)
Definition at line 34 of file systick.c.
References SYST_CSR, and SYST_CSR_TICKINT.
enableSystickTimer()
void enableSystickTimer (void)
Definition at line 24 of file systick.c.
References SYST_CSR, and SYST_CSR_ENABLE.
Referenced by delays_init().
getCurrentValue()
uint32_t getCurrentValue (void)
Definition at line 65 of file systick.c.
References SYST_CVR.
isCountZero()
bool isCountZero (void)
Definition at line 7 of file systick.c.
References SYST_CSR, and SYST_CSR_COUNTFLAG.
Referenced by wait().
isExcetionEnabled()
bool isExcetionEnabled (void)
Definition at line 52 of file systick.c.
References SYST_CSR, and SYST_CSR_TICKINT.
isTimerEnabled()
bool isTimerEnabled (void)
Definition at line 44 of file systick.c.
References SYST_CSR, and SYST_CSR_ENABLE.
setCockSource()
void setCockSource (uint32_t src)
Definition at line 15 of file systick.c.
References CLK_PROCESSOR, SYST_CSR, and SYST_CSR_CLKSOURCE.
Referenced by delays_init().
setCurrentValue()
void setCurrentValue (uint32_t value)
Definition at line 70 of file systick.c.
References SYST_CVR.
Referenced by wait().
setReloadValue()
void setReloadValue (uint32_t rvr)
Definition at line 60 of file systick.c.
References SYST_RVR.
Referenced by wait().
Variable Documentation
SYST_CSR
uint32_t* SYST_CSR =(uint32_t*)0xE000E010
Definition at line 3 of file systick.c.
Referenced by disableException(), disableSystickTimer(), enableException(), enableSystickTimer(), isCountZero(), isExcetionEnabled(), isTimerEnabled(), and setCockSource().
SYST_CVR
uint32_t* SYST_CVR =(uint32_t*)0xE000E018
Definition at line 5 of file systick.c.
Referenced by getCurrentValue(), and setCurrentValue().
SYST_RVR
uint32_t* SYST_RVR =(uint32_t*)0xE000E014
Definition at line 4 of file systick.c.
Referenced by setReloadValue().