Learn-ARM: /home/ubuntu/Desktop/repositories/learn-arm/src/c/lib/source/gpio.c File Reference
gpio.c File Reference
#include <stdint.h>
#include "../include/gpio.h"
Functions
void configurePortPin (uint32_t port, uint32_t pin, uint32_t config, uint32_t mode)
void pinState (uint32_t port, uint32_t pin, uint32_t state)
void toggle (uint32_t port, uint32_t pin)
Variables
uint32_t * GPIOA_CRL =(uint32_t*)PORTA_BASE
uint32_t * GPIOA_CRH =(uint32_t*)(PORTA_BASE + 0x04)
uint32_t * GPIOA_IDR =(uint32_t*)(PORTA_BASE + 0x08)
uint32_t * GPIOA_ORD =(uint32_t*)(PORTA_BASE + 0x0C)
uint32_t * GPIOA_BSRR =(uint32_t*)(PORTA_BASE + 0x10)
uint32_t * GPIOA_BRR =(uint32_t*)(PORTA_BASE + 0x14)
uint32_t * GPIOA_LCKR =(uint32_t*)(PORTA_BASE + 0x18)
uint32_t * GPIOB_CRL =(uint32_t*)PORTB_BASE
uint32_t * GPIOB_CRH =(uint32_t*)(PORTB_BASE + 0x04)
uint32_t * GPIOB_IDR =(uint32_t*)(PORTB_BASE + 0x08)
uint32_t * GPIOB_ORD =(uint32_t*)(PORTB_BASE + 0x0C)
uint32_t * GPIOB_BSRR =(uint32_t*)(PORTB_BASE + 0x10)
uint32_t * GPIOB_BRR =(uint32_t*)(PORTB_BASE + 0x14)
uint32_t * GPIOB_LCKR =(uint32_t*)(PORTB_BASE + 0x18)
uint32_t * GPIOC_CRL =(uint32_t*)PORTC_BASE
uint32_t * GPIOC_CRH =(uint32_t*)(PORTC_BASE + 0x04)
uint32_t * GPIOC_IDR =(uint32_t*)(PORTC_BASE + 0x08)
uint32_t * GPIOC_ORD =(uint32_t*)(PORTC_BASE + 0x0C)
uint32_t * GPIOC_BSRR =(uint32_t*)(PORTC_BASE + 0x10)
uint32_t * GPIOC_BRR =(uint32_t*)(PORTC_BASE + 0x14)
uint32_t * GPIOC_LCKR =(uint32_t*)(PORTC_BASE + 0x18)
uint32_t * GPIOD_CRL =(uint32_t*)PORTD_BASE
uint32_t * GPIOD_CRH =(uint32_t*)(PORTD_BASE + 0x04)
uint32_t * GPIOD_IDR =(uint32_t*)(PORTD_BASE + 0x08)
uint32_t * GPIOD_ORD =(uint32_t*)(PORTD_BASE+ 0x0C)
uint32_t * GPIOD_BSRR =(uint32_t*)(PORTD_BASE + 0x10)
uint32_t * GPIOD_BRR =(uint32_t*)(PORTD_BASE + 0x14)
uint32_t * GPIOD_LCKR =(uint32_t*)(PORTD_BASE + 0x18)
uint32_t * GPIOE_CRL =(uint32_t*)PORTE_BASE
uint32_t * GPIOE_CRH =(uint32_t*)(PORTE_BASE + 0x04)
uint32_t * GPIOE_IDR =(uint32_t*)(PORTE_BASE + 0x08)
uint32_t * GPIOE_ORD =(uint32_t*)(PORTE_BASE + 0x0C)
uint32_t * GPIOE_BSRR =(uint32_t*)(PORTE_BASE + 0x10)
uint32_t * GPIOE_BRR =(uint32_t*)(PORTE_BASE + 0x14)
uint32_t * GPIOE_LCKR =(uint32_t*)(PORTE_BASE + 0x18)
Function Documentation
configurePortPin()
void configurePortPin (uint32_t port, uint32_t pin, uint32_t config, uint32_t mode)
Definition at line 50 of file gpio.c.
References GPIOA_CRH, GPIOA_CRL, GPIOB_CRH, GPIOB_CRL, GPIOC_CRH, GPIOC_CRL, GPIOD_CRH, GPIOD_CRL, GPIOE_CRH, GPIOE_CRL, PORTA, PORTB, PORTC, PORTD, and PORTE.
Referenced by HCSR04(), and initialize().
pinState()
void pinState (uint32_t port, uint32_t pin, uint32_t state)
Definition at line 126 of file gpio.c.
References GPIOA_BSRR, GPIOB_BSRR, GPIOC_BSRR, GPIOD_BSRR, GPIOE_BSRR, PORTA, PORTB, PORTC, PORTD, and PORTE.
Referenced by HCSR04(), and trigger().
toggle()
void toggle (uint32_t port, uint32_t pin)
Definition at line 167 of file gpio.c.
References GPIOA_ORD, GPIOB_ORD, GPIOC_ORD, GPIOD_ORD, GPIOE_ORD, PORTA, PORTB, PORTC, PORTD, and PORTE.
Variable Documentation
GPIOA_BRR
uint32_t* GPIOA_BRR =(uint32_t*)(PORTA_BASE + 0x14)
Definition at line 11 of file gpio.c.
GPIOA_BSRR
uint32_t* GPIOA_BSRR =(uint32_t*)(PORTA_BASE + 0x10)
Definition at line 10 of file gpio.c.
Referenced by pinState().
GPIOA_CRH
uint32_t* GPIOA_CRH =(uint32_t*)(PORTA_BASE + 0x04)
Definition at line 7 of file gpio.c.
Referenced by configurePortPin().
GPIOA_CRL
uint32_t* GPIOA_CRL =(uint32_t*)PORTA_BASE
Definition at line 6 of file gpio.c.
Referenced by configurePortPin().
GPIOA_IDR
uint32_t* GPIOA_IDR =(uint32_t*)(PORTA_BASE + 0x08)
Definition at line 8 of file gpio.c.
GPIOA_LCKR
uint32_t* GPIOA_LCKR =(uint32_t*)(PORTA_BASE + 0x18)
Definition at line 12 of file gpio.c.
GPIOA_ORD
uint32_t* GPIOA_ORD =(uint32_t*)(PORTA_BASE + 0x0C)
Definition at line 9 of file gpio.c.
Referenced by toggle().
GPIOB_BRR
uint32_t* GPIOB_BRR =(uint32_t*)(PORTB_BASE + 0x14)
Definition at line 20 of file gpio.c.
GPIOB_BSRR
uint32_t* GPIOB_BSRR =(uint32_t*)(PORTB_BASE + 0x10)
Definition at line 19 of file gpio.c.
Referenced by pinState().
GPIOB_CRH
uint32_t* GPIOB_CRH =(uint32_t*)(PORTB_BASE + 0x04)
Definition at line 16 of file gpio.c.
Referenced by configurePortPin().
GPIOB_CRL
uint32_t* GPIOB_CRL =(uint32_t*)PORTB_BASE
Definition at line 15 of file gpio.c.
Referenced by configurePortPin().
GPIOB_IDR
uint32_t* GPIOB_IDR =(uint32_t*)(PORTB_BASE + 0x08)
Definition at line 17 of file gpio.c.
GPIOB_LCKR
uint32_t* GPIOB_LCKR =(uint32_t*)(PORTB_BASE + 0x18)
Definition at line 21 of file gpio.c.
GPIOB_ORD
uint32_t* GPIOB_ORD =(uint32_t*)(PORTB_BASE + 0x0C)
Definition at line 18 of file gpio.c.
Referenced by toggle().
GPIOC_BRR
uint32_t* GPIOC_BRR =(uint32_t*)(PORTC_BASE + 0x14)
Definition at line 29 of file gpio.c.
GPIOC_BSRR
uint32_t* GPIOC_BSRR =(uint32_t*)(PORTC_BASE + 0x10)
Definition at line 28 of file gpio.c.
Referenced by pinState().
GPIOC_CRH
uint32_t* GPIOC_CRH =(uint32_t*)(PORTC_BASE + 0x04)
Definition at line 25 of file gpio.c.
Referenced by configurePortPin().
GPIOC_CRL
uint32_t* GPIOC_CRL =(uint32_t*)PORTC_BASE
Definition at line 24 of file gpio.c.
Referenced by configurePortPin().
GPIOC_IDR
uint32_t* GPIOC_IDR =(uint32_t*)(PORTC_BASE + 0x08)
Definition at line 26 of file gpio.c.
GPIOC_LCKR
uint32_t* GPIOC_LCKR =(uint32_t*)(PORTC_BASE + 0x18)
Definition at line 30 of file gpio.c.
GPIOC_ORD
uint32_t* GPIOC_ORD =(uint32_t*)(PORTC_BASE + 0x0C)
Definition at line 27 of file gpio.c.
Referenced by toggle().
GPIOD_BRR
uint32_t* GPIOD_BRR =(uint32_t*)(PORTD_BASE + 0x14)
Definition at line 38 of file gpio.c.
GPIOD_BSRR
uint32_t* GPIOD_BSRR =(uint32_t*)(PORTD_BASE + 0x10)
Definition at line 37 of file gpio.c.
Referenced by pinState().
GPIOD_CRH
uint32_t* GPIOD_CRH =(uint32_t*)(PORTD_BASE + 0x04)
Definition at line 34 of file gpio.c.
Referenced by configurePortPin().
GPIOD_CRL
uint32_t* GPIOD_CRL =(uint32_t*)PORTD_BASE
Definition at line 33 of file gpio.c.
Referenced by configurePortPin().
GPIOD_IDR
uint32_t* GPIOD_IDR =(uint32_t*)(PORTD_BASE + 0x08)
Definition at line 35 of file gpio.c.
GPIOD_LCKR
uint32_t* GPIOD_LCKR =(uint32_t*)(PORTD_BASE + 0x18)
Definition at line 39 of file gpio.c.
GPIOD_ORD
uint32_t* GPIOD_ORD =(uint32_t*)(PORTD_BASE+ 0x0C)
Definition at line 36 of file gpio.c.
Referenced by toggle().
GPIOE_BRR
uint32_t* GPIOE_BRR =(uint32_t*)(PORTE_BASE + 0x14)
Definition at line 47 of file gpio.c.
GPIOE_BSRR
uint32_t* GPIOE_BSRR =(uint32_t*)(PORTE_BASE + 0x10)
Definition at line 46 of file gpio.c.
Referenced by pinState().
GPIOE_CRH
uint32_t* GPIOE_CRH =(uint32_t*)(PORTE_BASE + 0x04)
Definition at line 43 of file gpio.c.
Referenced by configurePortPin().
GPIOE_CRL
uint32_t* GPIOE_CRL =(uint32_t*)PORTE_BASE
Definition at line 42 of file gpio.c.
Referenced by configurePortPin().
GPIOE_IDR
uint32_t* GPIOE_IDR =(uint32_t*)(PORTE_BASE + 0x08)
Definition at line 44 of file gpio.c.
GPIOE_LCKR
uint32_t* GPIOE_LCKR =(uint32_t*)(PORTE_BASE + 0x18)
Definition at line 48 of file gpio.c.
GPIOE_ORD
uint32_t* GPIOE_ORD =(uint32_t*)(PORTE_BASE + 0x0C)
Definition at line 45 of file gpio.c.
Referenced by toggle().