#ifndef _AFIO_H
#define _AFIO_H

#include <stdint.h>
#include <stdbool.h>

#define AFIO_BASE 0x40010000

#define AFIO_MAPR_SWJ_CFG 24
#define AFIO_MAPR_ADC2_ETRIGREG_REMAP
#define AFIO_MAPR_ADC2_ETRIGINJ_REMAP
#define AFIO_MAPR_ADC1_ETRIGREG_REMAP 18
#define AFIO_MAPR_ADC1_ETRIGINJ_REMAP 17
#define AFIO_MAPR_PDO1_REMAP 15
#define AFIO_MAPR_CAN_REMAP 13
#define AFIO_MAPR_TIM4_REMAP 12
#define AFIO_MAPR_TIM3_REMAP 10
#define AFIO_MAPR_TIM2_REMAP 8
#define AFIO_MAPR_TIM1_REMAP 6
#define AFIO_MAPR_USART2_REMAP 3
#define AFIO_MAPR_USART1_REMAP 2
#define AFIO_MAPR_I2C1_REMAP 1
#define AFIO_MAPR_SPI-REMAO 0

uint32_t *AFIO_MAPR;

#endif
