#ifndef _AFIO_H
#define _AFIO_H

#include <stdint.h>
#include <stdbool.h>

#define AFIO_BASE 0x40010000

#define AFIO_EVCR_EVOE 7
#define AFIO_EVCR_PORT 4
#define AFIO_EVCR_PIN 0

#define AFIO_MAPR_SWJ_CFG 24
#define AFIO_MAPR_ADC2_ETRIGREG_REMAP
#define AFIO_MAPR_ADC2_ETRIGINJ_REMAP
#define AFIO_MAPR_ADC1_ETRIGREG_REMAP 18
#define AFIO_MAPR_ADC1_ETRIGINJ_REMAP 17
#define AFIO_MAPR_PDO1_REMAP 15
#define AFIO_MAPR_CAN_REMAP 13
#define AFIO_MAPR_TIM4_REMAP 12
#define AFIO_MAPR_TIM3_REMAP 10
#define AFIO_MAPR_TIM2_REMAP 8
#define AFIO_MAPR_TIM1_REMAP 6
#define AFIO_MAPR_USART2_REMAP 3
#define AFIO_MAPR_USART1_REMAP 2
#define AFIO_MAPR_I2C1_REMAP 1
#define AFIO_MAPR_SPI_REMAO 0

#define AFIO_EXTICR1_EXTI0 0
#define AFIO_EXTICR1_EXTI1 4
#define AFIO_EXTICR1_EXTI2 8
#define AFIO_EXTICR1_EXTI3 12

#define AFIO_EXTICR2_EXTI4 0
#define AFIO_EXTICR2_EXTI5 4
#define AFIO_EXTICR2_EXTI6 8
#define AFIO_EXTICR2_EXTI7 12

#define AFIO_EXTICR3_EXTI8 0
#define AFIO_EXTICR3_EXTI9 4
#define AFIO_EXTICR3_EXTI10 8
#define AFIO_EXTICR3_EXTI11 12

#define AFIO_EXTICR4_EXTI12 0
#define AFIO_EXTICR4_EXTI13 4
#define AFIO_EXTICR4_EXTI14 8
#define AFIO_EXTICR4_EXTI15 12

uint32_t *AFIO_EVCR;
uint32_t *AFIO_MAPR;
uint32_t *AFIO_EXTICR1;
uint32_t *AFIO_EXTICR2;
uint32_t *AFIO_EXTICR3;
uint32_t *AFIO_EXTICR4;



#endif
