Learn-ARM: /home/ubuntu/Desktop/repositories/learn-arm/src/c/lib/source/timers.c File Reference
timers.c File Reference
#include "../include/timers.h"
Functions
void enableTIMxClock (uint32_t module)
void enableCounter (uint32_t module)
void setUDIS (uint32_t module, bool state)
void setURS (uint32_t module, bool state)
void setOPM (uint32_t module, bool state)
void setDIR (uint32_t module, bool state)
void setCMS (uint32_t module, uint32_t cms)
void setARPE (uint32_t module, bool state)
void setCKD (uint32_t module, uint32_t ckd)
void disableCounter (uint32_t module)
bool getUDIS (uint32_t module)
bool getURS (uint32_t module)
bool getOPM (uint32_t module)
bool getDIR (uint32_t module)
uint32_t getCMS (uint32_t module)
bool getARPE (uint32_t module)
uint32_t getCKD (uint32_t module)
void setCCPC (uint32_t module, bool state)
void setCCUS (uint32_t module, bool state)
void setCCDS (uint32_t module, bool state)
void setMMS (uint32_t module, uint32_t mms)
void setTI1S (uint32_t module, bool state)
void setOIS1 (uint32_t module, bool state)
void setOIS1N (uint32_t module, bool state)
void setOIS2 (uint32_t module, bool state)
void setOIS2N (uint32_t module, bool state)
void setOIS3 (uint32_t module, bool state)
void setOIS3N (uint32_t module, bool state)
void setOIS4 (uint32_t module, bool state)
bool getOIS4 (uint32_t module)
bool getOIS3N (uint32_t module)
bool getOIS3 (uint32_t module)
bool getOIS2N (uint32_t module)
bool getOIS2 (uint32_t module)
bool getOIS1N (uint32_t module)
bool getOIS1 (uint32_t module)
bool getTI1S (uint32_t module)
uint32_t getMMS (uint32_t module)
bool getCCDS (uint32_t module)
bool getCCUS (uint32_t module)
bool getCCPC (uint32_t module)
void setETP (uint32_t module, bool state)
void setECE (uint32_t module, bool state)
void setETPS (uint32_t module, uint32_t etps)
void setETF (uint32_t module, uint32_t etf)
void setMSM (uint32_t module, bool state)
void setTS (uint32_t module, uint32_t ts)
void setSMS (uint32_t module, uint32_t sms)
bool getETP (uint32_t module)
bool getECE (uint32_t module)
uint32_t getETPS (uint32_t module)
uint32_t getETF (uint32_t module)
bool getMSM (uint32_t module)
uint32_t getTS (uint32_t module)
uint32_t getSMS (uint32_t module)
void setTDE (uint32_t, bool)
void setCOMDE (uint32_t, bool)
void setCC4DE (uint32_t, bool)
void setCC3DE (uint32_t, bool)
void setCC2DE (uint32_t, bool)
void setCC1DE (uint32_t, bool)
void setUDE (uint32_t, bool)
void setBIE (uint32_t, bool)
void setTIE (uint32_t, bool)
void setCOMIE (uint32_t, bool)
void setCC4IE (uint32_t, bool)
void setCC3IE (uint32_t, bool)
void setCC2IE (uint32_t, bool)
void setCC1IE (uint32_t, bool)
void setUIE (uint32_t, bool)
bool getTDE (uint32_t)
bool getCOMDE (uint32_t)
bool getCC4DE (uint32_t)
bool getCC3DE (uint32_t)
bool getCC2DE (uint32_t)
bool getCC1DE (uint32_t)
bool getUDE (uint32_t)
bool getBIE (uint32_t)
bool getTIE (uint32_t)
bool getCOMIE (uint32_t)
bool getCC4IE (uint32_t)
bool getCC3IE (uint32_t)
bool getCC2IE (uint32_t)
bool getCC1IE (uint32_t)
bool getUIE (uint32_t)
void setCC4OF (uint32_t, bool)
void setCC3OF (uint32_t, bool)
void setCC2OF (uint32_t, bool)
void setCC1OF (uint32_t, bool)
void setBIF (uint32_t, bool)
void setTIF (uint32_t, bool)
void setCOMIF (uint32_t, bool)
void setCC4IF (uint32_t, bool)
void setCC3IF (uint32_t, bool)
void setCC2IF (uint32_t, bool)
void setCC1IF (uint32_t, bool)
void setUIF (uint32_t, bool)
bool getCC4OF (uint32_t)
bool getCC3OF (uint32_t)
bool getCC2OF (uint32_t)
bool getCC1OF (uint32_t)
bool getBIF (uint32_t)
bool getTIF (uint32_t)
bool getCOMIF (uint32_t)
bool getCC4IF (uint32_t)
bool getCC3IF (uint32_t)
bool getCC2IF (uint32_t)
bool getCC1IF (uint32_t)
bool getUIF (uint32_t)
void setBG (uint32_t, bool)
void setTG (uint32_t, bool)
void setCOMG (uint32_t, bool)
void setCC4G (uint32_t, bool)
void setCC3G (uint32_t, bool)
void setCC2G (uint32_t, bool)
void setCC1G (uint32_t, bool)
void setUG (uint32_t, bool)
bool getBG (uint32_t)
bool getTG (uint32_t)
bool getCOMG (uint32_t)
bool getCC4G (uint32_t)
bool getCC3G (uint32_t)
bool getCC2G (uint32_t)
bool getCC1G (uint32_t)
bool getUG (uint32_t)
void setOC2CE (uint32_t, bool)
void setOC2M (uint32_t module, uint32_t value)
void setOC2PE (uint32_t, bool)
void setOC2FE (uint32_t, bool)
void setCC2S (uint32_t module, uint32_t value)
void setOC1CE (uint32_t, bool)
void setOC1M (uint32_t module, uint32_t value)
void setOC1PE (uint32_t, bool)
void setOC1FE (uint32_t, bool)
void setCC1S (uint32_t module, uint32_t value)
bool getOC2CE (uint32_t)
uint32_t getOC2M (uint32_t module)
bool getOC2PE (uint32_t)
bool getOC2FE (uint32_t)
uint32_t getCC2S (uint32_t module)
bool getOC1CE (uint32_t)
uint32_t getOC1M (uint32_t module)
bool getOC1PE (uint32_t)
bool getOC1FE (uint32_t)
uint32_t getCCS1 (uint32_t module)
void setIC2F (uint32_t module, uint32_t value)
void setIC2PSC (uint32_t module, uint32_t value)
void setIC1F (uint32_t module, uint32_t value)
void setIC1PSC (uint32_t module, uint32_t value)
uint32_t getIC2F (uint32_t module)
uint32_t getIC2PSC (uint32_t module)
uint32_t getIC1F (uint32_t module)
uint32_t getIC1PSC (uint32_t module)
void setOC4CE (uint32_t, bool)
void setOC4M (uint32_t module, uint32_t value)
void setOC4PE (uint32_t, bool)
void setOC4FE (uint32_t, bool)
void setCC4S (uint32_t module, uint32_t value)
void setOC3CE (uint32_t, bool)
void setOC3M (uint32_t module, uint32_t value)
void setOC3PE (uint32_t, bool)
void setOC3FE (uint32_t, bool)
void setCC3S (uint32_t module, uint32_t value)
bool getOC4CE (uint32_t)
uint32_t getOC4M (uint32_t module)
bool getOC4PE (uint32_t)
bool getOC4FE (uint32_t)
uint32_t getCC4S (uint32_t module)
bool getOC3CE (uint32_t)
uint32_t getOC3M (uint32_t module)
bool getOC3PE (uint32_t)
bool getOC3FE (uint32_t)
uint32_t getCCS3 (uint32_t module)
void setIC4F (uint32_t module, uint32_t value)
void setIC4PSC (uint32_t module, uint32_t value)
void setIC3F (uint32_t module, uint32_t value)
void setIC3PSC (uint32_t module, uint32_t value)
uint32_t getIC4F (uint32_t module)
uint32_t getIC4PSC (uint32_t module)
uint32_t getIC3F (uint32_t module)
uint32_t getIC3PSC (uint32_t module)
void setCC4P (uint32_t, bool)
void setCC4E (uint32_t, bool)
void setCC3NP (uint32_t, bool)
void setCC3NE (uint32_t, bool)
void setCC3P (uint32_t, bool)
void setCC3E (uint32_t, bool)
void setCC2NP (uint32_t, bool)
void setCC2NE (uint32_t, bool)
void setCC2P (uint32_t, bool)
void setCC2E (uint32_t, bool)
void setCC1NP (uint32_t, bool)
void setCC1NE (uint32_t, bool)
void setCC1P (uint32_t, bool)
void setCC1E (uint32_t, bool)
bool getCC4P (uint32_t)
bool getCC4E (uint32_t)
bool getCC3NP (uint32_t)
bool getCC3NE (uint32_t)
bool getCC3P (uint32_t)
bool getCC3E (uint32_t)
bool getCC2NP (uint32_t)
bool getCC2NE (uint32_t)
bool getCC2P (uint32_t)
bool getCC2E (uint32_t)
bool getCC1NP (uint32_t)
bool getCC1NE (uint32_t)
bool getCC1P (uint32_t)
bool getCC1E (uint32_t)
void setMOE (uint32_t module, bool state)
void setAOE (uint32_t module, bool state)
void setBKP (uint32_t module, bool state)
void setBKE (uint32_t module, bool state)
void setOSSR (uint32_t module, bool state)
void setOSSI (uint32_t module, bool state)
void setLOCK (uint32_t module, uint32_t value)
void setDTG (uint32_t module, uint32_t value)
bool getMOE (uint32_t module)
bool getAOE (uint32_t module)
bool getBKP (uint32_t module)
bool getBKE (uint32_t module)
bool getOSSR (uint32_t module)
bool getOSSI (uint32_t module)
uint32_t getLOCK (uint32_t module)
uint32_t getDTG (uint32_t module)
void setDLB (uint32_t module, uint32_t value)
void setDBA (uint32_t module, uint32_t value)
uint32_t getDLB (uint32_t module)
uint32_t getDBA (uint32_t module)
void setTIMx_CNT (uint32_t module, uint32_t value)
uint32_t getTIMx_CNT (uint32_t module)
void setTIMx_PSC (uint32_t module, uint32_t value)
uint32_t getTIMx_PSC (uint32_t module)
void setTIMx_ARR (uint32_t module, uint32_t value)
uint32_t getTIMx_ARR (uint32_t module)
void setTIMx_RCR (uint32_t module, uint32_t value)
uint32_t getTIMx_RCR (uint32_t module)
void setTIMx_CCR1 (uint32_t module, uint32_t value)
uint32_t getTIMx_CCR1 (uint32_t module)
void setTIMx_CCR2 (uint32_t module, uint32_t value)
uint32_t getTIMx_CCR2 (uint32_t module)
void setTIMx_CCR3 (uint32_t module, uint32_t value)
uint32_t getTIMx_CCR3 (uint32_t module)
void setTIMx_CCR4 (uint32_t module, uint32_t value)
uint32_t getTIMx_CCR4 (uint32_t module)
void setTIMx_DMAR (uint32_t module, uint32_t value)
uint32_t getTIMx_DMAR (uint32_t module)
Variables
uint32_t * TIM1_CR1 = (uint32_t*)(TIM1_BASE + 0x00)
uint32_t * TIM1_CR2 = (uint32_t*)(TIM1_BASE + 0x04)
uint32_t * TIM1_SMCR = (uint32_t*)(TIM1_BASE + 0x08)
uint32_t * TIM1_DIER = (uint32_t*)(TIM1_BASE + 0x0C)
uint32_t * TIM1_SR = (uint32_t*)(TIM1_BASE + 0x10)
uint32_t * TIM1_EGR = (uint32_t*)(TIM1_BASE + 0x14)
uint32_t * TIM1_CCMR1 = (uint32_t*)(TIM1_BASE + 0x18)
uint32_t * TIM1_CCMR2 = (uint32_t*)(TIM1_BASE + 0x1C)
uint32_t * TIM1_CCER = (uint32_t*)(TIM1_BASE + 0x20)
uint32_t * TIM1_CNT = (uint32_t*)(TIM1_BASE + 0x24)
uint32_t * TIM1_PSC = (uint32_t*)(TIM1_BASE + 0x28)
uint32_t * TIM1_ARR = (uint32_t*)(TIM1_BASE + 0x2C)
uint32_t * TIM1_RCR = (uint32_t*)(TIM1_BASE + 0x30)
uint32_t * TIM1_CCR1 = (uint32_t*)(TIM1_BASE + 0x34)
uint32_t * TIM1_CCR2 = (uint32_t*)(TIM1_BASE + 0x38)
uint32_t * TIM1_CCR3 = (uint32_t*)(TIM1_BASE + 0x3C)
uint32_t * TIM1_CCR4 = (uint32_t*)(TIM1_BASE + 0x40)
uint32_t * TIM1_BDTR = (uint32_t*)(TIM1_BASE + 0x44)
uint32_t * TIM1_DCR = (uint32_t*)(TIM1_BASE + 0x48)
uint32_t * TIM1_DMAR = (uint32_t*)(TIM1_BASE + 0x4C)
uint32_t * TIM2_CR1 = (uint32_t*)(TIM2_BASE + 0x00)
uint32_t * TIM2_CR2 = (uint32_t*)(TIM2_BASE + 0x04)
uint32_t * TIM2_SMCR = (uint32_t*)(TIM2_BASE + 0x08)
uint32_t * TIM2_DIER = (uint32_t*)(TIM2_BASE + 0x0C)
uint32_t * TIM2_SR = (uint32_t*)(TIM2_BASE + 0x10)
uint32_t * TIM2_EGR = (uint32_t*)(TIM2_BASE + 0x14)
uint32_t * TIM2_CCMR1 = (uint32_t*)(TIM2_BASE + 0x18)
uint32_t * TIM2_CCMR2 = (uint32_t*)(TIM2_BASE + 0x1C)
uint32_t * TIM2_CCER = (uint32_t*)(TIM2_BASE + 0x20)
uint32_t * TIM2_CNT = (uint32_t*)(TIM2_BASE + 0x24)
uint32_t * TIM2_PSC = (uint32_t*)(TIM2_BASE + 0x28)
uint32_t * TIM2_ARR = (uint32_t*)(TIM2_BASE + 0x2C)
uint32_t * TIM2_RCR = (uint32_t*)(TIM2_BASE + 0x30)
uint32_t * TIM2_CCR1 = (uint32_t*)(TIM2_BASE + 0x34)
uint32_t * TIM2_CCR2 = (uint32_t*)(TIM2_BASE + 0x38)
uint32_t * TIM2_CCR3 = (uint32_t*)(TIM2_BASE + 0x3C)
uint32_t * TIM2_CCR4 = (uint32_t*)(TIM2_BASE + 0x40)
uint32_t * TIM2_BDTR = (uint32_t*)(TIM2_BASE + 0x44)
uint32_t * TIM2_DCR = (uint32_t*)(TIM2_BASE + 0x48)
uint32_t * TIM2_DMAR = (uint32_t*)(TIM2_BASE + 0x4C)
uint32_t * TIM3_CR1 = (uint32_t*)(TIM3_BASE + 0x00)
uint32_t * TIM3_CR2 = (uint32_t*)(TIM3_BASE + 0x04)
uint32_t * TIM3_SMCR = (uint32_t*)(TIM3_BASE + 0x08)
uint32_t * TIM3_DIER = (uint32_t*)(TIM3_BASE + 0x0C)
uint32_t * TIM3_SR = (uint32_t*)(TIM3_BASE + 0x10)
uint32_t * TIM3_EGR = (uint32_t*)(TIM3_BASE + 0x14)
uint32_t * TIM3_CCMR1 = (uint32_t*)(TIM3_BASE + 0x18)
uint32_t * TIM3_CCMR2 = (uint32_t*)(TIM3_BASE + 0x1C)
uint32_t * TIM3_CCER = (uint32_t*)(TIM3_BASE + 0x20)
uint32_t * TIM3_CNT = (uint32_t*)(TIM3_BASE + 0x24)
uint32_t * TIM3_PSC = (uint32_t*)(TIM3_BASE + 0x28)
uint32_t * TIM3_ARR = (uint32_t*)(TIM3_BASE + 0x2C)
uint32_t * TIM3_RCR = (uint32_t*)(TIM3_BASE + 0x30)
uint32_t * TIM3_CCR1 = (uint32_t*)(TIM3_BASE + 0x34)
uint32_t * TIM3_CCR2 = (uint32_t*)(TIM3_BASE + 0x38)
uint32_t * TIM3_CCR3 = (uint32_t*)(TIM3_BASE + 0x3C)
uint32_t * TIM3_CCR4 = (uint32_t*)(TIM3_BASE + 0x40)
uint32_t * TIM3_BDTR = (uint32_t*)(TIM3_BASE + 0x44)
uint32_t * TIM3_DCR = (uint32_t*)(TIM3_BASE + 0x48)
uint32_t * TIM3_DMAR = (uint32_t*)(TIM3_BASE + 0x4C)
uint32_t * TIM4_CR1 = (uint32_t*)(TIM4_BASE + 0x00)
uint32_t * TIM4_CR2 = (uint32_t*)(TIM4_BASE + 0x04)
uint32_t * TIM4_SMCR = (uint32_t*)(TIM4_BASE + 0x08)
uint32_t * TIM4_DIER = (uint32_t*)(TIM4_BASE + 0x0C)
uint32_t * TIM4_SR = (uint32_t*)(TIM4_BASE + 0x10)
uint32_t * TIM4_EGR = (uint32_t*)(TIM4_BASE + 0x14)
uint32_t * TIM4_CCMR1 = (uint32_t*)(TIM4_BASE + 0x18)
uint32_t * TIM4_CCMR2 = (uint32_t*)(TIM4_BASE + 0x1C)
uint32_t * TIM4_CCER = (uint32_t*)(TIM4_BASE + 0x20)
uint32_t * TIM4_CNT = (uint32_t*)(TIM4_BASE + 0x24)
uint32_t * TIM4_PSC = (uint32_t*)(TIM4_BASE + 0x28)
uint32_t * TIM4_ARR = (uint32_t*)(TIM4_BASE + 0x2C)
uint32_t * TIM4_RCR = (uint32_t*)(TIM4_BASE + 0x30)
uint32_t * TIM4_CCR1 = (uint32_t*)(TIM4_BASE + 0x34)
uint32_t * TIM4_CCR2 = (uint32_t*)(TIM4_BASE + 0x38)
uint32_t * TIM4_CCR3 = (uint32_t*)(TIM4_BASE + 0x3C)
uint32_t * TIM4_CCR4 = (uint32_t*)(TIM4_BASE + 0x40)
uint32_t * TIM4_BDTR = (uint32_t*)(TIM4_BASE + 0x44)
uint32_t * TIM4_DCR = (uint32_t*)(TIM4_BASE + 0x48)
uint32_t * TIM4_DMAR = (uint32_t*)(TIM4_BASE + 0x4C)
Function Documentation
disableCounter()
void disableCounter (uint32_t module)
Definition at line 320 of file timers.c.
References TIM1, TIM1_CR1, TIM2, TIM2_CR1, TIM3, TIM3_CR1, TIM4, TIM4_CR1, and TIMx_CR1_CEN.
enableCounter()
void enableCounter (uint32_t module)
Definition at line 107 of file timers.c.
References TIM1, TIM1_CR1, TIM2, TIM2_CR1, TIM3, TIM3_CR1, TIM4, TIM4_CR1, and TIMx_CR1_CEN.
enableTIMxClock()
void enableTIMxClock (uint32_t module)
Definition at line 88 of file timers.c.
References enablePeripheralClock(), RCC_APB1ENR_TIM2EN, RCC_APB1ENR_TIM3EN, RCC_APB1ENR_TIM4EN, RCC_APB2ENR_TIM1EN, TIM1, TIM2, TIM3, and TIM4.
getAOE()
bool getAOE (uint32_t module)
Definition at line 2471 of file timers.c.
References TIM1, TIM1_BDTR, TIM2, TIM2_BDTR, TIM3, TIM3_BDTR, TIM4, TIM4_BDTR, and TIMx_BDTR_AOE.
getARPE()
bool getARPE (uint32_t module)
Definition at line 446 of file timers.c.
References TIM1, TIM1_CR1, TIM2, TIM2_CR1, TIM3, TIM3_CR1, TIM4, TIM4_CR1, and TIMx_CR1_ARPE.
getBG()
bool getBG (uint32_t)
getBIE()
bool getBIE (uint32_t)
getBIF()
bool getBIF (uint32_t)
getBKE()
bool getBKE (uint32_t module)
Definition at line 2513 of file timers.c.
References TIM1, TIM1_BDTR, TIM2, TIM2_BDTR, TIM3, TIM3_BDTR, TIM4, TIM4_BDTR, and TIMx_BDTR_BKE.
getBKP()
bool getBKP (uint32_t module)
Definition at line 2492 of file timers.c.
References TIM1, TIM1_BDTR, TIM2, TIM2_BDTR, TIM3, TIM3_BDTR, TIM4, TIM4_BDTR, and TIMx_BDTR_BKP.
getCC1DE()
bool getCC1DE (uint32_t)
getCC1E()
bool getCC1E (uint32_t)
getCC1G()
bool getCC1G (uint32_t)
getCC1IE()
bool getCC1IE (uint32_t)
getCC1IF()
bool getCC1IF (uint32_t)
getCC1NE()
bool getCC1NE (uint32_t)
getCC1NP()
bool getCC1NP (uint32_t)
getCC1OF()
bool getCC1OF (uint32_t)
getCC1P()
bool getCC1P (uint32_t)
getCC2DE()
bool getCC2DE (uint32_t)
getCC2E()
bool getCC2E (uint32_t)
getCC2G()
bool getCC2G (uint32_t)
getCC2IE()
bool getCC2IE (uint32_t)
getCC2IF()
bool getCC2IF (uint32_t)
getCC2NE()
bool getCC2NE (uint32_t)
getCC2NP()
bool getCC2NP (uint32_t)
getCC2OF()
bool getCC2OF (uint32_t)
getCC2P()
bool getCC2P (uint32_t)
getCC2S()
uint32_t getCC2S (uint32_t module)
Definition at line 1617 of file timers.c.
References TIM1, TIM1_CCMR1, TIM2, TIM2_CCMR1, TIM3, TIM3_CCMR1, TIM4, TIM4_CCMR1, and TIMx_CCMR1_CC2S.
getCC3DE()
bool getCC3DE (uint32_t)
getCC3E()
bool getCC3E (uint32_t)
getCC3G()
bool getCC3G (uint32_t)
getCC3IE()
bool getCC3IE (uint32_t)
getCC3IF()
bool getCC3IF (uint32_t)
getCC3NE()
bool getCC3NE (uint32_t)
getCC3NP()
bool getCC3NP (uint32_t)
getCC3OF()
bool getCC3OF (uint32_t)
getCC3P()
bool getCC3P (uint32_t)
getCC4DE()
bool getCC4DE (uint32_t)
getCC4E()
bool getCC4E (uint32_t)
getCC4G()
bool getCC4G (uint32_t)
getCC4IE()
bool getCC4IE (uint32_t)
getCC4IF()
bool getCC4IF (uint32_t)
getCC4OF()
bool getCC4OF (uint32_t)
getCC4P()
bool getCC4P (uint32_t)
getCC4S()
uint32_t getCC4S (uint32_t module)
Definition at line 1960 of file timers.c.
References TIM1, TIM1_CCMR2, TIM2, TIM2_CCMR2, TIM3, TIM3_CCMR2, TIM4, TIM4_CCMR2, and TIMx_CCMR2_CC4S.
getCCDS()
bool getCCDS (uint32_t module)
Definition at line 1041 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM3_CR2, TIM4, TIM4_CR2, and TIMx_CR2_CCDS.
getCCPC()
bool getCCPC (uint32_t module)
Definition at line 1083 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM3_CR2, TIM4, TIM4_CR2, and TIMx_CR2_CCPC.
getCCS1()
uint32_t getCCS1 (uint32_t module)
Definition at line 1664 of file timers.c.
References TIM1, TIM1_CCMR1, TIM2, TIM2_CCMR1, TIM3, TIM3_CCMR1, TIM4, TIM4_CCMR1, and TIMx_CCMR1_CC1S.
getCCS3()
uint32_t getCCS3 (uint32_t module)
Definition at line 2008 of file timers.c.
References TIM1, TIM1_CCMR2, TIM2, TIM2_CCMR2, TIM3, TIM3_CCMR2, TIM4, TIM4_CCMR2, and TIMx_CCMR2_CC3S.
getCCUS()
bool getCCUS (uint32_t module)
Definition at line 1062 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM3_CR2, TIM4, TIM4_CR2, and TIMx_CR2_CCUS.
getCKD()
uint32_t getCKD (uint32_t module)
Definition at line 468 of file timers.c.
References TIM1, TIM1_CR1, TIM2, TIM2_CR1, TIM3, TIM4, TIM4_CR1, and TIMx_CR1_CKD.
getCMS()
uint32_t getCMS (uint32_t module)
Definition at line 424 of file timers.c.
References TIM1, TIM1_CR1, TIM2, TIM2_CR1, TIM3, TIM4, TIM4_CR1, and TIMx_CR1_CMS.
getCOMDE()
bool getCOMDE (uint32_t)
getCOMG()
bool getCOMG (uint32_t)
getCOMIE()
bool getCOMIE (uint32_t)
getCOMIF()
bool getCOMIF (uint32_t)
getDBA()
uint32_t getDBA (uint32_t module)
Definition at line 2678 of file timers.c.
References TIM1, TIM1_DCR, TIM2, TIM2_DCR, TIM3, TIM3_DCR, TIM4, TIM4_DCR, and TIMx_DCR_DBA.
getDIR()
bool getDIR (uint32_t module)
Definition at line 403 of file timers.c.
References TIM1, TIM1_CR1, TIM2, TIM2_CR1, TIM3, TIM3_CR1, TIM4, TIM4_CR1, and TIMx_CR1_DIR.
getDLB()
uint32_t getDLB (uint32_t module)
Definition at line 2657 of file timers.c.
References TIM1, TIM1_DCR, TIM2, TIM2_DCR, TIM3, TIM3_DCR, TIM4, TIM4_DCR, and TIMx_DCR_DBL.
getDTG()
uint32_t getDTG (uint32_t module)
Definition at line 2598 of file timers.c.
References TIM1, TIM1_BDTR, TIM2, TIM2_BDTR, TIM3, TIM3_BDTR, TIM4, TIM4_BDTR, and TIMx_BDTR_DTG.
getECE()
bool getECE (uint32_t module)
Definition at line 1296 of file timers.c.
References TIM1, TIM1_SMCR, TIM2, TIM2_SMCR, TIM3, TIM3_SMCR, TIM4, TIM4_SMCR, and TIMx_SMCR_ECE.
getETF()
uint32_t getETF (uint32_t module)
Definition at line 1338 of file timers.c.
References TIM1, TIM1_SMCR, TIM2, TIM2_SMCR, TIM3, TIM3_SMCR, TIM4, TIM4_SMCR, and TIMx_SMCR_ETF.
getETP()
bool getETP (uint32_t module)
Definition at line 1275 of file timers.c.
References TIM1, TIM1_SMCR, TIM2, TIM2_SMCR, TIM3, TIM3_SMCR, TIM4, TIM4_SMCR, and TIMx_SMCR_ETP.
getETPS()
uint32_t getETPS (uint32_t module)
Definition at line 1317 of file timers.c.
References TIM1, TIM1_SMCR, TIM2, TIM2_SMCR, TIM3, TIM3_SMCR, TIM4, TIM4_SMCR, and TIMx_SMCR_ETPS.
getIC1F()
uint32_t getIC1F (uint32_t module)
Definition at line 1803 of file timers.c.
References TIM1, TIM1_CCMR1, TIM2, TIM2_CCMR1, TIM3, TIM3_CCMR1, TIM4, TIM4_CCMR1, and TIMx_CCMR1_IC1F.
getIC1PSC()
uint32_t getIC1PSC (uint32_t module)
Definition at line 1824 of file timers.c.
References TIM1, TIM1_CCMR1, TIM2, TIM2_CCMR1, TIM3, TIM3_CCMR1, TIM4, TIM4_CCMR1, and TIMx_CCMR1_IC1PSC.
getIC2F()
uint32_t getIC2F (uint32_t module)
Definition at line 1761 of file timers.c.
References TIM1, TIM1_CCMR1, TIM2, TIM2_CCMR1, TIM3, TIM3_CCMR1, TIM4, TIM4_CCMR1, and TIMx_CCMR1_IC2F.
getIC2PSC()
uint32_t getIC2PSC (uint32_t module)
Definition at line 1782 of file timers.c.
References TIM1, TIM1_CCMR1, TIM2, TIM2_CCMR1, TIM3, TIM3_CCMR1, TIM4, TIM4_CCMR1, and TIMx_CCMR1_IC2PSC.
getIC3F()
uint32_t getIC3F (uint32_t module)
Definition at line 2148 of file timers.c.
References TIM1, TIM1_CCMR2, TIM2, TIM2_CCMR2, TIM3, TIM3_CCMR2, TIM4, TIM4_CCMR2, and TIMx_CCMR2_IC3F.
getIC3PSC()
uint32_t getIC3PSC (uint32_t module)
Definition at line 2169 of file timers.c.
References TIM1, TIM1_CCMR2, TIM2, TIM2_CCMR2, TIM3, TIM3_CCMR2, TIM4, TIM4_CCMR2, and TIMx_CCMR2_IC3PSC.
getIC4F()
uint32_t getIC4F (uint32_t module)
Definition at line 2106 of file timers.c.
References TIM1, TIM1_CCMR2, TIM2, TIM2_CCMR2, TIM3, TIM3_CCMR2, TIM4, TIM4_CCMR2, and TIMx_CCMR2_IC4F.
getIC4PSC()
uint32_t getIC4PSC (uint32_t module)
Definition at line 2127 of file timers.c.
References TIM1, TIM1_CCMR2, TIM2, TIM2_CCMR2, TIM3, TIM3_CCMR2, TIM4, TIM4_CCMR2, and TIMx_CCMR2_IC4PSC.
getLOCK()
uint32_t getLOCK (uint32_t module)
Definition at line 2577 of file timers.c.
References TIM1, TIM1_BDTR, TIM2, TIM2_BDTR, TIM3, TIM3_BDTR, TIM4, TIM4_BDTR, and TIMx_BDTR_LOCK.
getMMS()
uint32_t getMMS (uint32_t module)
Definition at line 1020 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM4, TIM4_CR2, and TIMx_CR2_MMS.
getMOE()
bool getMOE (uint32_t module)
Definition at line 2450 of file timers.c.
References TIM1, TIM1_BDTR, TIM2, TIM2_BDTR, TIM3, TIM3_BDTR, TIM4, TIM4_BDTR, and TIMx_BDTR_MOE.
getMSM()
bool getMSM (uint32_t module)
Definition at line 1359 of file timers.c.
References TIM1, TIM1_SMCR, TIM2, TIM2_SMCR, TIM3, TIM3_SMCR, TIM4, TIM4_SMCR, and TIMx_SMCR_MSM.
getOC1CE()
bool getOC1CE (uint32_t)
getOC1FE()
bool getOC1FE (uint32_t)
getOC1M()
uint32_t getOC1M (uint32_t module)
Definition at line 1640 of file timers.c.
References TIM1, TIM1_CCMR1, TIM2, TIM2_CCMR1, TIM3, TIM3_CCMR1, TIM4, TIM4_CCMR1, and TIMx_CCMR1_OC1M.
getOC1PE()
bool getOC1PE (uint32_t)
getOC2CE()
bool getOC2CE (uint32_t)
getOC2FE()
bool getOC2FE (uint32_t)
getOC2M()
uint32_t getOC2M (uint32_t module)
Definition at line 1593 of file timers.c.
References TIM1, TIM1_CCMR1, TIM2, TIM2_CCMR1, TIM3, TIM3_CCMR1, TIM4, TIM4_CCMR1, and TIMx_CCMR1_OC2M.
getOC2PE()
bool getOC2PE (uint32_t)
getOC3CE()
bool getOC3CE (uint32_t)
getOC3FE()
bool getOC3FE (uint32_t)
getOC3M()
uint32_t getOC3M (uint32_t module)
Definition at line 1983 of file timers.c.
References TIM1, TIM1_CCMR2, TIM2, TIM2_CCMR2, TIM3, TIM3_CCMR2, TIM4, TIM4_CCMR2, and TIMx_CCMR2_OC3M.
getOC3PE()
bool getOC3PE (uint32_t)
getOC4CE()
bool getOC4CE (uint32_t)
getOC4FE()
bool getOC4FE (uint32_t)
getOC4M()
uint32_t getOC4M (uint32_t module)
Definition at line 1935 of file timers.c.
References TIM1, TIM1_CCMR2, TIM2, TIM2_CCMR2, TIM3, TIM3_CCMR2, TIM4, TIM4_CCMR2, and TIMx_CCMR2_OC4M.
getOC4PE()
bool getOC4PE (uint32_t)
getOIS1()
bool getOIS1 (uint32_t module)
Definition at line 978 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM3_CR2, TIM4, TIM4_CR2, and TIMx_CR2_OIS1.
getOIS1N()
bool getOIS1N (uint32_t module)
Definition at line 956 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM3_CR2, TIM4, TIM4_CR2, and TIMx_CR2_OIS1N.
getOIS2()
bool getOIS2 (uint32_t module)
Definition at line 935 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM3_CR2, TIM4, TIM4_CR2, and TIMx_CR2_OIS2.
getOIS2N()
bool getOIS2N (uint32_t module)
Definition at line 914 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM3_CR2, TIM4, TIM4_CR2, and TIMx_CR2_OIS2N.
getOIS3()
bool getOIS3 (uint32_t module)
Definition at line 893 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM3_CR2, TIM4, TIM4_CR2, and TIMx_CR2_OIS3.
getOIS3N()
bool getOIS3N (uint32_t module)
Definition at line 871 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM3_CR2, TIM4, TIM4_CR2, and TIMx_CR2_OIS3N.
getOIS4()
bool getOIS4 (uint32_t module)
Definition at line 850 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM3_CR2, TIM4, TIM4_CR2, and TIMx_CR2_OIS4.
getOPM()
bool getOPM (uint32_t module)
Definition at line 382 of file timers.c.
References TIM1, TIM1_CR1, TIM2, TIM2_CR1, TIM3, TIM3_CR1, TIM4, TIM4_CR1, and TIMx_CR1_OPM.
getOSSI()
bool getOSSI (uint32_t module)
Definition at line 2556 of file timers.c.
References TIM1, TIM1_BDTR, TIM2, TIM2_BDTR, TIM3, TIM3_BDTR, TIM4, TIM4_BDTR, and TIMx_BDTR_OSSI.
getOSSR()
bool getOSSR (uint32_t module)
Definition at line 2535 of file timers.c.
References TIM1, TIM1_BDTR, TIM2, TIM2_BDTR, TIM3, TIM3_BDTR, TIM4, TIM4_BDTR, and TIMx_BDTR_OSSR.
getSMS()
uint32_t getSMS (uint32_t module)
Definition at line 1401 of file timers.c.
References TIM1, TIM1_SMCR, TIM2, TIM2_SMCR, TIM3, TIM3_SMCR, TIM4, TIM4_SMCR, and TIMx_SMCR_SMS.
getTDE()
bool getTDE (uint32_t)
getTG()
bool getTG (uint32_t)
getTI1S()
bool getTI1S (uint32_t module)
Definition at line 999 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM3_CR2, TIM4, TIM4_CR2, and TIMx_CR2_TI1S.
getTIE()
bool getTIE (uint32_t)
getTIF()
bool getTIF (uint32_t)
getTIMx_ARR()
uint32_t getTIMx_ARR (uint32_t module)
Definition at line 2818 of file timers.c.
References TIM1, TIM1_ARR, TIM2, TIM2_ARR, TIM3, TIM3_ARR, TIM4, and TIM4_ARR.
getTIMx_CCR1()
uint32_t getTIMx_CCR1 (uint32_t module)
Definition at line 2914 of file timers.c.
References TIM1, TIM1_CCR1, TIM2, TIM2_CCR1, TIM3, TIM3_CCR1, TIM4, and TIM4_CCR1.
getTIMx_CCR2()
uint32_t getTIMx_CCR2 (uint32_t module)
Definition at line 2962 of file timers.c.
References TIM1, TIM1_CCR2, TIM2, TIM2_CCR2, TIM3, TIM3_CCR2, TIM4, and TIM4_CCR2.
getTIMx_CCR3()
uint32_t getTIMx_CCR3 (uint32_t module)
Definition at line 3010 of file timers.c.
References TIM1, TIM1_CCR3, TIM2, TIM2_CCR3, TIM3, TIM3_CCR3, TIM4, and TIM4_CCR3.
getTIMx_CCR4()
uint32_t getTIMx_CCR4 (uint32_t module)
Definition at line 3058 of file timers.c.
References TIM1, TIM1_CCR4, TIM2, TIM2_CCR4, TIM3, TIM3_CCR4, TIM4, and TIM4_CCR4.
getTIMx_CNT()
uint32_t getTIMx_CNT (uint32_t module)
Definition at line 2721 of file timers.c.
References TIM1, TIM1_CNT, TIM2, TIM2_CNT, TIM3, TIM3_CNT, TIM4, and TIM4_CNT.
getTIMx_DMAR()
uint32_t getTIMx_DMAR (uint32_t module)
Definition at line 3106 of file timers.c.
References TIM1, TIM1_DMAR, TIM2, TIM2_DMAR, TIM3, TIM3_DMAR, TIM4, and TIM4_DMAR.
getTIMx_PSC()
uint32_t getTIMx_PSC (uint32_t module)
Definition at line 2770 of file timers.c.
References TIM1, TIM1_PSC, TIM2, TIM2_PSC, TIM3, TIM3_PSC, TIM4, and TIM4_PSC.
getTIMx_RCR()
uint32_t getTIMx_RCR (uint32_t module)
Definition at line 2866 of file timers.c.
References TIM1, TIM1_RCR, TIM2, TIM2_RCR, TIM3, TIM3_RCR, TIM4, and TIM4_RCR.
getTS()
uint32_t getTS (uint32_t module)
Definition at line 1380 of file timers.c.
References TIM1, TIM1_SMCR, TIM2, TIM2_SMCR, TIM3, TIM3_SMCR, TIM4, TIM4_SMCR, and TIMx_SMCR_TS.
getUDE()
bool getUDE (uint32_t)
getUDIS()
bool getUDIS (uint32_t module)
Definition at line 339 of file timers.c.
References TIM1, TIM1_CR1, TIM2, TIM2_CR1, TIM3, TIM3_CR1, TIM4, TIM4_CR1, and TIMx_CR1_UDIS.
getUG()
bool getUG (uint32_t)
getUIE()
bool getUIE (uint32_t)
getUIF()
bool getUIF (uint32_t)
getURS()
bool getURS (uint32_t module)
Definition at line 361 of file timers.c.
References TIM1, TIM1_CR1, TIM2, TIM2_CR1, TIM3, TIM3_CR1, TIM4, TIM4_CR1, and TIMx_CR1_URS.
setAOE()
void setAOE (uint32_t module, bool state)
Definition at line 2257 of file timers.c.
References TIM1, TIM1_BDTR, TIM2, TIM2_BDTR, TIM3, TIM3_BDTR, TIM4, TIM4_BDTR, and TIMx_BDTR_AOE.
setARPE()
void setARPE (uint32_t module, bool state)
Definition at line 269 of file timers.c.
References TIM1, TIM1_CR1, TIM2, TIM2_CR1, TIM3, TIM3_CR1, TIM4, TIM4_CR1, and TIMx_CR1_ARPE.
setBG()
void setBG (uint32_t , bool)
setBIE()
void setBIE (uint32_t , bool)
setBIF()
void setBIF (uint32_t , bool)
setBKE()
void setBKE (uint32_t module, bool state)
Definition at line 2319 of file timers.c.
References TIM1, TIM1_BDTR, TIM2, TIM2_BDTR, TIM3, TIM3_BDTR, TIM4, TIM4_BDTR, and TIMx_BDTR_BKE.
setBKP()
void setBKP (uint32_t module, bool state)
Definition at line 2288 of file timers.c.
References TIM1, TIM1_BDTR, TIM2, TIM2_BDTR, TIM3, TIM3_BDTR, TIM4, TIM4_BDTR, and TIMx_BDTR_BKP.
setCC1DE()
void setCC1DE (uint32_t , bool)
setCC1E()
void setCC1E (uint32_t , bool)
setCC1G()
void setCC1G (uint32_t , bool)
setCC1IE()
void setCC1IE (uint32_t , bool)
setCC1IF()
void setCC1IF (uint32_t , bool)
setCC1NE()
void setCC1NE (uint32_t , bool)
setCC1NP()
void setCC1NP (uint32_t , bool)
setCC1OF()
void setCC1OF (uint32_t , bool)
setCC1P()
void setCC1P (uint32_t , bool)
setCC1S()
void setCC1S (uint32_t module, uint32_t value)
Definition at line 1570 of file timers.c.
References TIM1, TIM1_CCMR1, TIM2, TIM2_CCMR1, TIM3, TIM3_CCMR1, TIM4, TIM4_CCMR1, and TIMx_CCMR1_CC1S.
setCC2DE()
void setCC2DE (uint32_t , bool)
setCC2E()
void setCC2E (uint32_t , bool)
setCC2G()
void setCC2G (uint32_t , bool)
setCC2IE()
void setCC2IE (uint32_t , bool)
setCC2IF()
void setCC2IF (uint32_t , bool)
setCC2NE()
void setCC2NE (uint32_t , bool)
setCC2NP()
void setCC2NP (uint32_t , bool)
setCC2OF()
void setCC2OF (uint32_t , bool)
setCC2P()
void setCC2P (uint32_t , bool)
setCC2S()
void setCC2S (uint32_t module, uint32_t value)
Definition at line 1525 of file timers.c.
References TIM1, TIM1_CCMR1, TIM2, TIM2_CCMR1, TIM3, TIM3_CCMR1, TIM4, TIM4_CCMR1, and TIMx_CCMR1_CC2S.
setCC3DE()
void setCC3DE (uint32_t , bool)
setCC3E()
void setCC3E (uint32_t , bool)
setCC3G()
void setCC3G (uint32_t , bool)
setCC3IE()
void setCC3IE (uint32_t , bool)
setCC3IF()
void setCC3IF (uint32_t , bool)
setCC3NE()
void setCC3NE (uint32_t , bool)
setCC3NP()
void setCC3NP (uint32_t , bool)
setCC3OF()
void setCC3OF (uint32_t , bool)
setCC3P()
void setCC3P (uint32_t , bool)
setCC3S()
void setCC3S (uint32_t module, uint32_t value)
Definition at line 1913 of file timers.c.
References TIM1, TIM1_CCMR2, TIM2, TIM2_CCMR2, TIM3, TIM3_CCMR2, TIM4, TIM4_CCMR2, and TIMx_CCMR2_CC3S.
setCC4DE()
void setCC4DE (uint32_t , bool)
setCC4E()
void setCC4E (uint32_t , bool)
setCC4G()
void setCC4G (uint32_t , bool)
setCC4IE()
void setCC4IE (uint32_t , bool)
setCC4IF()
void setCC4IF (uint32_t , bool)
setCC4OF()
void setCC4OF (uint32_t , bool)
setCC4P()
void setCC4P (uint32_t , bool)
setCC4S()
void setCC4S (uint32_t module, uint32_t value)
Definition at line 1869 of file timers.c.
References TIM1, TIM1_CCMR2, TIM2, TIM2_CCMR2, TIM3, TIM3_CCMR2, TIM4, TIM4_CCMR2, and TIMx_CCMR2_CC4S.
setCCDS()
void setCCDS (uint32_t module, bool state)
Definition at line 551 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM3_CR2, TIM4, TIM4_CR2, and TIMx_CR2_CCDS.
setCCPC()
void setCCPC (uint32_t module, bool state)
Definition at line 489 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM3_CR2, TIM4, TIM4_CR2, and TIMx_CR2_CCPC.
setCCUS()
void setCCUS (uint32_t module, bool state)
Definition at line 520 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM3_CR2, TIM4, TIM4_CR2, and TIMx_CR2_CCUS.
setCKD()
void setCKD (uint32_t module, uint32_t ckd)
Definition at line 300 of file timers.c.
References TIM1, TIM1_CR1, TIM2, TIM2_CR1, TIM3, TIM3_CR1, TIM4, TIM4_CR1, and TIMx_CR1_CKD.
setCMS()
void setCMS (uint32_t module, uint32_t cms)
Definition at line 250 of file timers.c.
References TIM1, TIM1_CR1, TIM2, TIM2_CR1, TIM3, TIM3_CR1, TIM4, TIM4_CR1, and TIMx_CR1_CMS.
setCOMDE()
void setCOMDE (uint32_t , bool)
setCOMG()
void setCOMG (uint32_t , bool)
setCOMIE()
void setCOMIE (uint32_t , bool)
setCOMIF()
void setCOMIF (uint32_t , bool)
setDBA()
void setDBA (uint32_t module, uint32_t value)
Definition at line 2638 of file timers.c.
References TIM1, TIM1_DCR, TIM2, TIM2_DCR, TIM3, TIM3_DCR, TIM4, TIM4_DCR, and TIMx_DCR_DBA.
setDIR()
void setDIR (uint32_t module, bool state)
Definition at line 219 of file timers.c.
References TIM1, TIM1_CR1, TIM2, TIM2_CR1, TIM3, TIM3_CR1, TIM4, TIM4_CR1, and TIMx_CR1_DIR.
setDLB()
void setDLB (uint32_t module, uint32_t value)
Definition at line 2619 of file timers.c.
References TIM1, TIM1_DCR, TIM2, TIM2_DCR, TIM3, TIM3_DCR, TIM4, TIM4_DCR, and TIMx_DCR_DBL.
setDTG()
void setDTG (uint32_t module, uint32_t value)
Definition at line 2431 of file timers.c.
References TIM1, TIM1_BDTR, TIM2, TIM2_BDTR, TIM3, TIM3_BDTR, TIM4, TIM4_BDTR, and TIMx_BDTR_DTG.
setECE()
void setECE (uint32_t module, bool state)
Definition at line 1136 of file timers.c.
References TIM1, TIM1_SMCR, TIM2, TIM2_SMCR, TIM3, TIM3_SMCR, TIM4, TIM4_SMCR, and TIMx_SMCR_ECE.
setETF()
void setETF (uint32_t module, uint32_t etf)
Definition at line 1186 of file timers.c.
References TIM1, TIM1_SMCR, TIM2, TIM2_SMCR, TIM3, TIM3_SMCR, TIM4, TIM4_SMCR, and TIMx_SMCR_ETF.
setETP()
void setETP (uint32_t module, bool state)
Definition at line 1105 of file timers.c.
References TIM1, TIM1_SMCR, TIM2, TIM2_SMCR, TIM3, TIM3_SMCR, TIM4, TIM4_SMCR, and TIMx_SMCR_ETP.
setETPS()
void setETPS (uint32_t module, uint32_t etps)
Definition at line 1167 of file timers.c.
References TIM1, TIM1_SMCR, TIM2, TIM2_SMCR, TIM3, TIM3_SMCR, TIM4, TIM4_SMCR, and TIMx_SMCR_ETPS.
setIC1F()
void setIC1F (uint32_t module, uint32_t value)
Definition at line 1723 of file timers.c.
References TIM1, TIM1_CCMR1, TIM2, TIM2_CCMR1, TIM3, TIM3_CCMR1, TIM4, TIM4_CCMR1, and TIMx_CCMR1_IC1F.
setIC1PSC()
void setIC1PSC (uint32_t module, uint32_t value)
Definition at line 1742 of file timers.c.
References TIM1, TIM1_CCMR1, TIM2, TIM2_CCMR1, TIM3, TIM3_CCMR1, TIM4, TIM4_CCMR1, and TIMx_CCMR1_IC1PSC.
setIC2F()
void setIC2F (uint32_t module, uint32_t value)
Definition at line 1685 of file timers.c.
References TIM1, TIM1_CCMR1, TIM2, TIM2_CCMR1, TIM3, TIM3_CCMR1, TIM4, TIM4_CCMR1, and TIMx_CCMR1_IC2F.
setIC2PSC()
void setIC2PSC (uint32_t module, uint32_t value)
Definition at line 1704 of file timers.c.
References TIM1, TIM1_CCMR1, TIM2, TIM2_CCMR1, TIM3, TIM3_CCMR1, TIM4, TIM4_CCMR1, and TIMx_CCMR1_IC2PSC.
setIC3F()
void setIC3F (uint32_t module, uint32_t value)
Definition at line 2068 of file timers.c.
References TIM1, TIM1_CCMR2, TIM2, TIM2_CCMR2, TIM3, TIM3_CCMR2, TIM4, TIM4_CCMR2, and TIMx_CCMR2_IC3F.
setIC3PSC()
void setIC3PSC (uint32_t module, uint32_t value)
Definition at line 2087 of file timers.c.
References TIM1, TIM1_CCMR2, TIM2, TIM2_CCMR2, TIM3, TIM3_CCMR2, TIM4, TIM4_CCMR2, and TIMx_CCMR2_IC3PSC.
setIC4F()
void setIC4F (uint32_t module, uint32_t value)
Definition at line 2030 of file timers.c.
References TIM1, TIM1_CCMR2, TIM2, TIM2_CCMR2, TIM3, TIM3_CCMR2, TIM4, TIM4_CCMR2, and TIMx_CCMR2_IC4F.
setIC4PSC()
void setIC4PSC (uint32_t module, uint32_t value)
Definition at line 2049 of file timers.c.
References TIM1, TIM1_CCMR2, TIM2, TIM2_CCMR2, TIM3, TIM3_CCMR2, TIM4, TIM4_CCMR2, and TIMx_CCMR2_IC4PSC.
setLOCK()
void setLOCK (uint32_t module, uint32_t value)
Definition at line 2412 of file timers.c.
References TIM1, TIM1_BDTR, TIM2, TIM2_BDTR, TIM3, TIM3_BDTR, TIM4, TIM4_BDTR, and TIMx_BDTR_LOCK.
setMMS()
void setMMS (uint32_t module, uint32_t mms)
Definition at line 582 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM3_CR2, TIM4, TIM4_CR2, and TIMx_CR2_MMS.
setMOE()
void setMOE (uint32_t module, bool state)
Definition at line 2226 of file timers.c.
References TIM1, TIM1_BDTR, TIM2, TIM2_BDTR, TIM3, TIM3_BDTR, TIM4, TIM4_BDTR, and TIMx_BDTR_MOE.
setMSM()
void setMSM (uint32_t module, bool state)
Definition at line 1205 of file timers.c.
References TIM1, TIM1_SMCR, TIM2, TIM2_SMCR, TIM3, TIM3_SMCR, TIM4, TIM4_SMCR, and TIMx_SMCR_MSM.
setOC1CE()
void setOC1CE (uint32_t , bool)
setOC1FE()
void setOC1FE (uint32_t , bool)
setOC1M()
void setOC1M (uint32_t module, uint32_t value)
Definition at line 1547 of file timers.c.
References TIM1, TIM1_CCMR1, TIM2, TIM2_CCMR1, TIM3, TIM3_CCMR1, TIM4, TIM4_CCMR1, and TIMx_CCMR1_OC1M.
setOC1PE()
void setOC1PE (uint32_t , bool)
setOC2CE()
void setOC2CE (uint32_t , bool)
setOC2FE()
void setOC2FE (uint32_t , bool)
setOC2M()
void setOC2M (uint32_t module, uint32_t value)
Definition at line 1502 of file timers.c.
References TIM1, TIM1_CCMR1, TIM2, TIM2_CCMR1, TIM3, TIM3_CCMR1, TIM4, TIM4_CCMR1, and TIMx_CCMR1_OC2M.
setOC2PE()
void setOC2PE (uint32_t , bool)
setOC3CE()
void setOC3CE (uint32_t , bool)
setOC3FE()
void setOC3FE (uint32_t , bool)
setOC3M()
void setOC3M (uint32_t module, uint32_t value)
Definition at line 1891 of file timers.c.
References TIM1, TIM1_CCMR2, TIM2, TIM2_CCMR2, TIM3, TIM3_CCMR2, TIM4, TIM4_CCMR2, and TIMx_CCMR2_OC3M.
setOC3PE()
void setOC3PE (uint32_t , bool)
setOC4CE()
void setOC4CE (uint32_t , bool)
setOC4FE()
void setOC4FE (uint32_t , bool)
setOC4M()
void setOC4M (uint32_t module, uint32_t value)
Definition at line 1847 of file timers.c.
References TIM1, TIM1_CCMR2, TIM2, TIM2_CCMR2, TIM3, TIM3_CCMR2, TIM4, TIM4_CCMR2, and TIMx_CCMR2_OC4M.
setOC4PE()
void setOC4PE (uint32_t , bool)
setOIS1()
void setOIS1 (uint32_t module, bool state)
Definition at line 632 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM3_CR2, TIM4, TIM4_CR2, and TIMx_CR2_OIS1.
setOIS1N()
void setOIS1N (uint32_t module, bool state)
Definition at line 663 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM3_CR2, TIM4, TIM4_CR2, and TIMx_CR2_OIS1N.
setOIS2()
void setOIS2 (uint32_t module, bool state)
Definition at line 694 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM3_CR2, TIM4, TIM4_CR2, and TIMx_CR2_OIS2.
setOIS2N()
void setOIS2N (uint32_t module, bool state)
Definition at line 725 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM3_CR2, TIM4, TIM4_CR2, and TIMx_CR2_OIS2N.
setOIS3()
void setOIS3 (uint32_t module, bool state)
Definition at line 756 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM3_CR2, TIM4, TIM4_CR2, and TIMx_CR2_OIS3.
setOIS3N()
void setOIS3N (uint32_t module, bool state)
Definition at line 787 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM3_CR2, TIM4, TIM4_CR2, and TIMx_CR2_OIS3N.
setOIS4()
void setOIS4 (uint32_t module, bool state)
Definition at line 818 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM3_CR2, TIM4, TIM4_CR2, and TIMx_CR2_OIS4.
setOPM()
void setOPM (uint32_t module, bool state)
Definition at line 188 of file timers.c.
References TIM1, TIM1_CR1, TIM2, TIM2_CR1, TIM3, TIM3_CR1, TIM4, TIM4_CR1, and TIMx_CR1_OPM.
setOSSI()
void setOSSI (uint32_t module, bool state)
Definition at line 2381 of file timers.c.
References TIM1, TIM1_BDTR, TIM2, TIM2_BDTR, TIM3, TIM3_BDTR, TIM4, TIM4_BDTR, and TIMx_BDTR_OSSI.
setOSSR()
void setOSSR (uint32_t module, bool state)
Definition at line 2350 of file timers.c.
References TIM1, TIM1_BDTR, TIM2, TIM2_BDTR, TIM3, TIM3_BDTR, TIM4, TIM4_BDTR, and TIMx_BDTR_OSSR.
setSMS()
void setSMS (uint32_t module, uint32_t sms)
Definition at line 1255 of file timers.c.
References TIM1, TIM1_SMCR, TIM2, TIM2_SMCR, TIM3, TIM3_SMCR, TIM4, TIM4_SMCR, and TIMx_SMCR_SMS.
setTDE()
void setTDE (uint32_t , bool)
setTG()
void setTG (uint32_t , bool)
setTI1S()
void setTI1S (uint32_t module, bool state)
Definition at line 601 of file timers.c.
References TIM1, TIM1_CR2, TIM2, TIM2_CR2, TIM3, TIM3_CR2, TIM4, TIM4_CR2, and TIMx_CR2_TI1S.
setTIE()
void setTIE (uint32_t , bool)
setTIF()
void setTIF (uint32_t , bool)
setTIMx_ARR()
void setTIMx_ARR (uint32_t module, uint32_t value)
Definition at line 2796 of file timers.c.
References TIM1, TIM1_ARR, TIM2, TIM2_ARR, TIM3, TIM3_ARR, TIM4, and TIM4_ARR.
setTIMx_CCR1()
void setTIMx_CCR1 (uint32_t module, uint32_t value)
Definition at line 2892 of file timers.c.
References TIM1, TIM1_CCR1, TIM2, TIM2_CCR1, TIM3, TIM3_CCR1, TIM4, and TIM4_CCR1.
setTIMx_CCR2()
void setTIMx_CCR2 (uint32_t module, uint32_t value)
Definition at line 2940 of file timers.c.
References TIM1, TIM1_CCR2, TIM2, TIM2_CCR2, TIM3, TIM3_CCR2, TIM4, and TIM4_CCR2.
setTIMx_CCR3()
void setTIMx_CCR3 (uint32_t module, uint32_t value)
Definition at line 2988 of file timers.c.
References TIM1, TIM1_CCR3, TIM2, TIM2_CCR3, TIM3, TIM3_CCR3, TIM4, and TIM4_CCR3.
setTIMx_CCR4()
void setTIMx_CCR4 (uint32_t module, uint32_t value)
Definition at line 3036 of file timers.c.
References TIM1, TIM1_CCR4, TIM2, TIM2_CCR4, TIM3, TIM3_CCR4, TIM4, and TIM4_CCR4.
setTIMx_CNT()
void setTIMx_CNT (uint32_t module, uint32_t value)
Definition at line 2699 of file timers.c.
References TIM1, TIM1_CNT, TIM2, TIM2_CNT, TIM3, TIM3_CNT, TIM4, and TIM4_CNT.
setTIMx_DMAR()
void setTIMx_DMAR (uint32_t module, uint32_t value)
Definition at line 3084 of file timers.c.
References TIM1, TIM1_DMAR, TIM2, TIM2_DMAR, TIM3, TIM3_DMAR, TIM4, and TIM4_DMAR.
setTIMx_PSC()
void setTIMx_PSC (uint32_t module, uint32_t value)
Definition at line 2747 of file timers.c.
References TIM1, TIM1_PSC, TIM2, TIM2_ARR, TIM3, TIM3_ARR, TIM4, and TIM4_ARR.
setTIMx_RCR()
void setTIMx_RCR (uint32_t module, uint32_t value)
Definition at line 2844 of file timers.c.
References TIM1, TIM1_RCR, TIM2, TIM2_RCR, TIM3, TIM3_RCR, TIM4, and TIM4_RCR.
setTS()
void setTS (uint32_t module, uint32_t ts)
Definition at line 1236 of file timers.c.
References TIM1, TIM1_SMCR, TIM2, TIM2_SMCR, TIM3, TIM3_SMCR, TIM4, TIM4_SMCR, and TIMx_SMCR_TS.
setUDE()
void setUDE (uint32_t , bool)
setUDIS()
void setUDIS (uint32_t module, bool state)
Definition at line 126 of file timers.c.
References TIM1, TIM1_CR1, TIM2, TIM2_CR1, TIM3, TIM3_CR1, TIM4, TIM4_CR1, and TIMx_CR1_UDIS.
setUG()
void setUG (uint32_t , bool)
setUIE()
void setUIE (uint32_t , bool)
setUIF()
void setUIF (uint32_t , bool)
setURS()
void setURS (uint32_t module, bool state)
Definition at line 157 of file timers.c.
References TIM1, TIM1_CR1, TIM2, TIM2_CR1, TIM3, TIM3_CR1, TIM4, TIM4_CR1, and TIMx_CR1_URS.
Variable Documentation
TIM1_ARR
uint32_t* TIM1_ARR = (uint32_t*)(TIM1_BASE + 0x2C)
Definition at line 14 of file timers.c.
Referenced by getTIMx_ARR(), and setTIMx_ARR().
TIM1_BDTR
uint32_t* TIM1_BDTR = (uint32_t*)(TIM1_BASE + 0x44)
Definition at line 20 of file timers.c.
Referenced by getAOE(), getBKE(), getBKP(), getDTG(), getLOCK(), getMOE(), getOSSI(), getOSSR(), setAOE(), setBKE(), setBKP(), setDTG(), setLOCK(), setMOE(), setOSSI(), and setOSSR().
TIM1_CCER
uint32_t* TIM1_CCER = (uint32_t*)(TIM1_BASE + 0x20)
Definition at line 11 of file timers.c.
TIM1_CCMR1
uint32_t* TIM1_CCMR1 = (uint32_t*)(TIM1_BASE + 0x18)
Definition at line 9 of file timers.c.
Referenced by getCC2S(), getCCS1(), getIC1F(), getIC1PSC(), getIC2F(), getIC2PSC(), getOC1M(), getOC2M(), setCC1S(), setCC2S(), setIC1F(), setIC1PSC(), setIC2F(), setIC2PSC(), setOC1M(), and setOC2M().
TIM1_CCMR2
uint32_t* TIM1_CCMR2 = (uint32_t*)(TIM1_BASE + 0x1C)
Definition at line 10 of file timers.c.
Referenced by getCC4S(), getCCS3(), getIC3F(), getIC3PSC(), getIC4F(), getIC4PSC(), getOC3M(), getOC4M(), setCC3S(), setCC4S(), setIC3F(), setIC3PSC(), setIC4F(), setIC4PSC(), setOC3M(), and setOC4M().
TIM1_CCR1
uint32_t* TIM1_CCR1 = (uint32_t*)(TIM1_BASE + 0x34)
Definition at line 16 of file timers.c.
Referenced by getTIMx_CCR1(), and setTIMx_CCR1().
TIM1_CCR2
uint32_t* TIM1_CCR2 = (uint32_t*)(TIM1_BASE + 0x38)
Definition at line 17 of file timers.c.
Referenced by getTIMx_CCR2(), and setTIMx_CCR2().
TIM1_CCR3
uint32_t* TIM1_CCR3 = (uint32_t*)(TIM1_BASE + 0x3C)
Definition at line 18 of file timers.c.
Referenced by getTIMx_CCR3(), and setTIMx_CCR3().
TIM1_CCR4
uint32_t* TIM1_CCR4 = (uint32_t*)(TIM1_BASE + 0x40)
Definition at line 19 of file timers.c.
Referenced by getTIMx_CCR4(), and setTIMx_CCR4().
TIM1_CNT
uint32_t* TIM1_CNT = (uint32_t*)(TIM1_BASE + 0x24)
Definition at line 12 of file timers.c.
Referenced by getTIMx_CNT(), and setTIMx_CNT().
TIM1_CR1
uint32_t* TIM1_CR1 = (uint32_t*)(TIM1_BASE + 0x00)
Definition at line 3 of file timers.c.
Referenced by disableCounter(), enableCounter(), getARPE(), getCKD(), getCMS(), getDIR(), getOPM(), getUDIS(), getURS(), setARPE(), setCKD(), setCMS(), setDIR(), setOPM(), setUDIS(), and setURS().
TIM1_CR2
uint32_t* TIM1_CR2 = (uint32_t*)(TIM1_BASE + 0x04)
Definition at line 4 of file timers.c.
Referenced by getCCDS(), getCCPC(), getCCUS(), getMMS(), getOIS1(), getOIS1N(), getOIS2(), getOIS2N(), getOIS3(), getOIS3N(), getOIS4(), getTI1S(), setCCDS(), setCCPC(), setCCUS(), setMMS(), setOIS1(), setOIS1N(), setOIS2(), setOIS2N(), setOIS3(), setOIS3N(), setOIS4(), and setTI1S().
TIM1_DCR
uint32_t* TIM1_DCR = (uint32_t*)(TIM1_BASE + 0x48)
Definition at line 21 of file timers.c.
Referenced by getDBA(), getDLB(), setDBA(), and setDLB().
TIM1_DIER
uint32_t* TIM1_DIER = (uint32_t*)(TIM1_BASE + 0x0C)
Definition at line 6 of file timers.c.
TIM1_DMAR
uint32_t* TIM1_DMAR = (uint32_t*)(TIM1_BASE + 0x4C)
Definition at line 22 of file timers.c.
Referenced by getTIMx_DMAR(), and setTIMx_DMAR().
TIM1_EGR
uint32_t* TIM1_EGR = (uint32_t*)(TIM1_BASE + 0x14)
Definition at line 8 of file timers.c.
TIM1_PSC
uint32_t* TIM1_PSC = (uint32_t*)(TIM1_BASE + 0x28)
Definition at line 13 of file timers.c.
Referenced by getTIMx_PSC(), and setTIMx_PSC().
TIM1_RCR
uint32_t* TIM1_RCR = (uint32_t*)(TIM1_BASE + 0x30)
Definition at line 15 of file timers.c.
Referenced by getTIMx_RCR(), and setTIMx_RCR().
TIM1_SMCR
uint32_t* TIM1_SMCR = (uint32_t*)(TIM1_BASE + 0x08)
Definition at line 5 of file timers.c.
Referenced by getECE(), getETF(), getETP(), getETPS(), getMSM(), getSMS(), getTS(), setECE(), setETF(), setETP(), setETPS(), setMSM(), setSMS(), and setTS().
TIM1_SR
uint32_t* TIM1_SR = (uint32_t*)(TIM1_BASE + 0x10)
Definition at line 7 of file timers.c.
TIM2_ARR
uint32_t* TIM2_ARR = (uint32_t*)(TIM2_BASE + 0x2C)
Definition at line 35 of file timers.c.
Referenced by getTIMx_ARR(), setTIMx_ARR(), and setTIMx_PSC().
TIM2_BDTR
uint32_t* TIM2_BDTR = (uint32_t*)(TIM2_BASE + 0x44)
Definition at line 41 of file timers.c.
Referenced by getAOE(), getBKE(), getBKP(), getDTG(), getLOCK(), getMOE(), getOSSI(), getOSSR(), setAOE(), setBKE(), setBKP(), setDTG(), setLOCK(), setMOE(), setOSSI(), and setOSSR().
TIM2_CCER
uint32_t* TIM2_CCER = (uint32_t*)(TIM2_BASE + 0x20)
Definition at line 32 of file timers.c.
TIM2_CCMR1
uint32_t* TIM2_CCMR1 = (uint32_t*)(TIM2_BASE + 0x18)
Definition at line 30 of file timers.c.
Referenced by getCC2S(), getCCS1(), getIC1F(), getIC1PSC(), getIC2F(), getIC2PSC(), getOC1M(), getOC2M(), setCC1S(), setCC2S(), setIC1F(), setIC1PSC(), setIC2F(), setIC2PSC(), setOC1M(), and setOC2M().
TIM2_CCMR2
uint32_t* TIM2_CCMR2 = (uint32_t*)(TIM2_BASE + 0x1C)
Definition at line 31 of file timers.c.
Referenced by getCC4S(), getCCS3(), getIC3F(), getIC3PSC(), getIC4F(), getIC4PSC(), getOC3M(), getOC4M(), setCC3S(), setCC4S(), setIC3F(), setIC3PSC(), setIC4F(), setIC4PSC(), setOC3M(), and setOC4M().
TIM2_CCR1
uint32_t* TIM2_CCR1 = (uint32_t*)(TIM2_BASE + 0x34)
Definition at line 37 of file timers.c.
Referenced by getTIMx_CCR1(), and setTIMx_CCR1().
TIM2_CCR2
uint32_t* TIM2_CCR2 = (uint32_t*)(TIM2_BASE + 0x38)
Definition at line 38 of file timers.c.
Referenced by getTIMx_CCR2(), and setTIMx_CCR2().
TIM2_CCR3
uint32_t* TIM2_CCR3 = (uint32_t*)(TIM2_BASE + 0x3C)
Definition at line 39 of file timers.c.
Referenced by getTIMx_CCR3(), and setTIMx_CCR3().
TIM2_CCR4
uint32_t* TIM2_CCR4 = (uint32_t*)(TIM2_BASE + 0x40)
Definition at line 40 of file timers.c.
Referenced by getTIMx_CCR4(), and setTIMx_CCR4().
TIM2_CNT
uint32_t* TIM2_CNT = (uint32_t*)(TIM2_BASE + 0x24)
Definition at line 33 of file timers.c.
Referenced by getTIMx_CNT(), and setTIMx_CNT().
TIM2_CR1
uint32_t* TIM2_CR1 = (uint32_t*)(TIM2_BASE + 0x00)
Definition at line 24 of file timers.c.
Referenced by disableCounter(), enableCounter(), getARPE(), getCKD(), getCMS(), getDIR(), getOPM(), getUDIS(), getURS(), setARPE(), setCKD(), setCMS(), setDIR(), setOPM(), setUDIS(), and setURS().
TIM2_CR2
uint32_t* TIM2_CR2 = (uint32_t*)(TIM2_BASE + 0x04)
Definition at line 25 of file timers.c.
Referenced by getCCDS(), getCCPC(), getCCUS(), getMMS(), getOIS1(), getOIS1N(), getOIS2(), getOIS2N(), getOIS3(), getOIS3N(), getOIS4(), getTI1S(), setCCDS(), setCCPC(), setCCUS(), setMMS(), setOIS1(), setOIS1N(), setOIS2(), setOIS2N(), setOIS3(), setOIS3N(), setOIS4(), and setTI1S().
TIM2_DCR
uint32_t* TIM2_DCR = (uint32_t*)(TIM2_BASE + 0x48)
Definition at line 42 of file timers.c.
Referenced by getDBA(), getDLB(), setDBA(), and setDLB().
TIM2_DIER
uint32_t* TIM2_DIER = (uint32_t*)(TIM2_BASE + 0x0C)
Definition at line 27 of file timers.c.
TIM2_DMAR
uint32_t* TIM2_DMAR = (uint32_t*)(TIM2_BASE + 0x4C)
Definition at line 43 of file timers.c.
Referenced by getTIMx_DMAR(), and setTIMx_DMAR().
TIM2_EGR
uint32_t* TIM2_EGR = (uint32_t*)(TIM2_BASE + 0x14)
Definition at line 29 of file timers.c.
TIM2_PSC
uint32_t* TIM2_PSC = (uint32_t*)(TIM2_BASE + 0x28)
Definition at line 34 of file timers.c.
Referenced by getTIMx_PSC().
TIM2_RCR
uint32_t* TIM2_RCR = (uint32_t*)(TIM2_BASE + 0x30)
Definition at line 36 of file timers.c.
Referenced by getTIMx_RCR(), and setTIMx_RCR().
TIM2_SMCR
uint32_t* TIM2_SMCR = (uint32_t*)(TIM2_BASE + 0x08)
Definition at line 26 of file timers.c.
Referenced by getECE(), getETF(), getETP(), getETPS(), getMSM(), getSMS(), getTS(), setECE(), setETF(), setETP(), setETPS(), setMSM(), setSMS(), and setTS().
TIM2_SR
uint32_t* TIM2_SR = (uint32_t*)(TIM2_BASE + 0x10)
Definition at line 28 of file timers.c.
TIM3_ARR
uint32_t* TIM3_ARR = (uint32_t*)(TIM3_BASE + 0x2C)
Definition at line 56 of file timers.c.
Referenced by getTIMx_ARR(), setTIMx_ARR(), and setTIMx_PSC().
TIM3_BDTR
uint32_t* TIM3_BDTR = (uint32_t*)(TIM3_BASE + 0x44)
Definition at line 62 of file timers.c.
Referenced by getAOE(), getBKE(), getBKP(), getDTG(), getLOCK(), getMOE(), getOSSI(), getOSSR(), setAOE(), setBKE(), setBKP(), setDTG(), setLOCK(), setMOE(), setOSSI(), and setOSSR().
TIM3_CCER
uint32_t* TIM3_CCER = (uint32_t*)(TIM3_BASE + 0x20)
Definition at line 53 of file timers.c.
TIM3_CCMR1
uint32_t* TIM3_CCMR1 = (uint32_t*)(TIM3_BASE + 0x18)
Definition at line 51 of file timers.c.
Referenced by getCC2S(), getCCS1(), getIC1F(), getIC1PSC(), getIC2F(), getIC2PSC(), getOC1M(), getOC2M(), setCC1S(), setCC2S(), setIC1F(), setIC1PSC(), setIC2F(), setIC2PSC(), setOC1M(), and setOC2M().
TIM3_CCMR2
uint32_t* TIM3_CCMR2 = (uint32_t*)(TIM3_BASE + 0x1C)
Definition at line 52 of file timers.c.
Referenced by getCC4S(), getCCS3(), getIC3F(), getIC3PSC(), getIC4F(), getIC4PSC(), getOC3M(), getOC4M(), setCC3S(), setCC4S(), setIC3F(), setIC3PSC(), setIC4F(), setIC4PSC(), setOC3M(), and setOC4M().
TIM3_CCR1
uint32_t* TIM3_CCR1 = (uint32_t*)(TIM3_BASE + 0x34)
Definition at line 58 of file timers.c.
Referenced by getTIMx_CCR1(), and setTIMx_CCR1().
TIM3_CCR2
uint32_t* TIM3_CCR2 = (uint32_t*)(TIM3_BASE + 0x38)
Definition at line 59 of file timers.c.
Referenced by getTIMx_CCR2(), and setTIMx_CCR2().
TIM3_CCR3
uint32_t* TIM3_CCR3 = (uint32_t*)(TIM3_BASE + 0x3C)
Definition at line 60 of file timers.c.
Referenced by getTIMx_CCR3(), and setTIMx_CCR3().
TIM3_CCR4
uint32_t* TIM3_CCR4 = (uint32_t*)(TIM3_BASE + 0x40)
Definition at line 61 of file timers.c.
Referenced by getTIMx_CCR4(), and setTIMx_CCR4().
TIM3_CNT
uint32_t* TIM3_CNT = (uint32_t*)(TIM3_BASE + 0x24)
Definition at line 54 of file timers.c.
Referenced by getTIMx_CNT(), and setTIMx_CNT().
TIM3_CR1
uint32_t* TIM3_CR1 = (uint32_t*)(TIM3_BASE + 0x00)
Definition at line 45 of file timers.c.
Referenced by disableCounter(), enableCounter(), getARPE(), getDIR(), getOPM(), getUDIS(), getURS(), setARPE(), setCKD(), setCMS(), setDIR(), setOPM(), setUDIS(), and setURS().
TIM3_CR2
uint32_t* TIM3_CR2 = (uint32_t*)(TIM3_BASE + 0x04)
Definition at line 46 of file timers.c.
Referenced by getCCDS(), getCCPC(), getCCUS(), getOIS1(), getOIS1N(), getOIS2(), getOIS2N(), getOIS3(), getOIS3N(), getOIS4(), getTI1S(), setCCDS(), setCCPC(), setCCUS(), setMMS(), setOIS1(), setOIS1N(), setOIS2(), setOIS2N(), setOIS3(), setOIS3N(), setOIS4(), and setTI1S().
TIM3_DCR
uint32_t* TIM3_DCR = (uint32_t*)(TIM3_BASE + 0x48)
Definition at line 63 of file timers.c.
Referenced by getDBA(), getDLB(), setDBA(), and setDLB().
TIM3_DIER
uint32_t* TIM3_DIER = (uint32_t*)(TIM3_BASE + 0x0C)
Definition at line 48 of file timers.c.
TIM3_DMAR
uint32_t* TIM3_DMAR = (uint32_t*)(TIM3_BASE + 0x4C)
Definition at line 64 of file timers.c.
Referenced by getTIMx_DMAR(), and setTIMx_DMAR().
TIM3_EGR
uint32_t* TIM3_EGR = (uint32_t*)(TIM3_BASE + 0x14)
Definition at line 50 of file timers.c.
TIM3_PSC
uint32_t* TIM3_PSC = (uint32_t*)(TIM3_BASE + 0x28)
Definition at line 55 of file timers.c.
Referenced by getTIMx_PSC().
TIM3_RCR
uint32_t* TIM3_RCR = (uint32_t*)(TIM3_BASE + 0x30)
Definition at line 57 of file timers.c.
Referenced by getTIMx_RCR(), and setTIMx_RCR().
TIM3_SMCR
uint32_t* TIM3_SMCR = (uint32_t*)(TIM3_BASE + 0x08)
Definition at line 47 of file timers.c.
Referenced by getECE(), getETF(), getETP(), getETPS(), getMSM(), getSMS(), getTS(), setECE(), setETF(), setETP(), setETPS(), setMSM(), setSMS(), and setTS().
TIM3_SR
uint32_t* TIM3_SR = (uint32_t*)(TIM3_BASE + 0x10)
Definition at line 49 of file timers.c.
TIM4_ARR
uint32_t* TIM4_ARR = (uint32_t*)(TIM4_BASE + 0x2C)
Definition at line 77 of file timers.c.
Referenced by getTIMx_ARR(), setTIMx_ARR(), and setTIMx_PSC().
TIM4_BDTR
uint32_t* TIM4_BDTR = (uint32_t*)(TIM4_BASE + 0x44)
Definition at line 83 of file timers.c.
Referenced by getAOE(), getBKE(), getBKP(), getDTG(), getLOCK(), getMOE(), getOSSI(), getOSSR(), setAOE(), setBKE(), setBKP(), setDTG(), setLOCK(), setMOE(), setOSSI(), and setOSSR().
TIM4_CCER
uint32_t* TIM4_CCER = (uint32_t*)(TIM4_BASE + 0x20)
Definition at line 74 of file timers.c.
TIM4_CCMR1
uint32_t* TIM4_CCMR1 = (uint32_t*)(TIM4_BASE + 0x18)
Definition at line 72 of file timers.c.
Referenced by getCC2S(), getCCS1(), getIC1F(), getIC1PSC(), getIC2F(), getIC2PSC(), getOC1M(), getOC2M(), setCC1S(), setCC2S(), setIC1F(), setIC1PSC(), setIC2F(), setIC2PSC(), setOC1M(), and setOC2M().
TIM4_CCMR2
uint32_t* TIM4_CCMR2 = (uint32_t*)(TIM4_BASE + 0x1C)
Definition at line 73 of file timers.c.
Referenced by getCC4S(), getCCS3(), getIC3F(), getIC3PSC(), getIC4F(), getIC4PSC(), getOC3M(), getOC4M(), setCC3S(), setCC4S(), setIC3F(), setIC3PSC(), setIC4F(), setIC4PSC(), setOC3M(), and setOC4M().
TIM4_CCR1
uint32_t* TIM4_CCR1 = (uint32_t*)(TIM4_BASE + 0x34)
Definition at line 79 of file timers.c.
Referenced by getTIMx_CCR1(), and setTIMx_CCR1().
TIM4_CCR2
uint32_t* TIM4_CCR2 = (uint32_t*)(TIM4_BASE + 0x38)
Definition at line 80 of file timers.c.
Referenced by getTIMx_CCR2(), and setTIMx_CCR2().
TIM4_CCR3
uint32_t* TIM4_CCR3 = (uint32_t*)(TIM4_BASE + 0x3C)
Definition at line 81 of file timers.c.
Referenced by getTIMx_CCR3(), and setTIMx_CCR3().
TIM4_CCR4
uint32_t* TIM4_CCR4 = (uint32_t*)(TIM4_BASE + 0x40)
Definition at line 82 of file timers.c.
Referenced by getTIMx_CCR4(), and setTIMx_CCR4().
TIM4_CNT
uint32_t* TIM4_CNT = (uint32_t*)(TIM4_BASE + 0x24)
Definition at line 75 of file timers.c.
Referenced by getTIMx_CNT(), and setTIMx_CNT().
TIM4_CR1
uint32_t* TIM4_CR1 = (uint32_t*)(TIM4_BASE + 0x00)
Definition at line 66 of file timers.c.
Referenced by disableCounter(), enableCounter(), getARPE(), getCKD(), getCMS(), getDIR(), getOPM(), getUDIS(), getURS(), setARPE(), setCKD(), setCMS(), setDIR(), setOPM(), setUDIS(), and setURS().
TIM4_CR2
uint32_t* TIM4_CR2 = (uint32_t*)(TIM4_BASE + 0x04)
Definition at line 67 of file timers.c.
Referenced by getCCDS(), getCCPC(), getCCUS(), getMMS(), getOIS1(), getOIS1N(), getOIS2(), getOIS2N(), getOIS3(), getOIS3N(), getOIS4(), getTI1S(), setCCDS(), setCCPC(), setCCUS(), setMMS(), setOIS1(), setOIS1N(), setOIS2(), setOIS2N(), setOIS3(), setOIS3N(), setOIS4(), and setTI1S().
TIM4_DCR
uint32_t* TIM4_DCR = (uint32_t*)(TIM4_BASE + 0x48)
Definition at line 84 of file timers.c.
Referenced by getDBA(), getDLB(), setDBA(), and setDLB().
TIM4_DIER
uint32_t* TIM4_DIER = (uint32_t*)(TIM4_BASE + 0x0C)
Definition at line 69 of file timers.c.
TIM4_DMAR
uint32_t* TIM4_DMAR = (uint32_t*)(TIM4_BASE + 0x4C)
Definition at line 85 of file timers.c.
Referenced by getTIMx_DMAR(), and setTIMx_DMAR().
TIM4_EGR
uint32_t* TIM4_EGR = (uint32_t*)(TIM4_BASE + 0x14)
Definition at line 71 of file timers.c.
TIM4_PSC
uint32_t* TIM4_PSC = (uint32_t*)(TIM4_BASE + 0x28)
Definition at line 76 of file timers.c.
Referenced by getTIMx_PSC().
TIM4_RCR
uint32_t* TIM4_RCR = (uint32_t*)(TIM4_BASE + 0x30)
Definition at line 78 of file timers.c.
Referenced by getTIMx_RCR(), and setTIMx_RCR().
TIM4_SMCR
uint32_t* TIM4_SMCR = (uint32_t*)(TIM4_BASE + 0x08)
Definition at line 68 of file timers.c.
Referenced by getECE(), getETF(), getETP(), getETPS(), getMSM(), getSMS(), getTS(), setECE(), setETF(), setETP(), setETPS(), setMSM(), setSMS(), and setTS().
TIM4_SR
uint32_t* TIM4_SR = (uint32_t*)(TIM4_BASE + 0x10)
Definition at line 70 of file timers.c.