Learn-ARM: /home/ubuntu/Desktop/repositories/learn-arm/src/c/lib/source/delay.c File Reference
delay.c File Reference
#include "../include/delay.h"
Functions
void delays_init (uint32_t clk)
Deley configuratio.
void wait (uint32_t base_period)
void delay_ms (uint32_t dly)
void delay_us (uint32_t dly)
Variables
uint32_t SYS_CLK = 8
Function Documentation
delay_ms()
void delay_ms (uint32_t dly)
Definition at line 23 of file delay.c.
References SYS_CLK, and wait().
delay_us()
void delay_us (uint32_t dly)
Definition at line 29 of file delay.c.
References SYS_CLK, and wait().
Referenced by trigger().
delays_init()
void delays_init (uint32_t sys_clk)
Deley configuratio.
configures the delays to operate based on the value of the system clcok setting
Parameters
sys_clk The value of the system clock setting
Note
The default value of the system clock setting is 72 MHz
See also
main.h
Definition at line 5 of file delay.c.
References CLK_PROCESSOR, disableException(), disableSystickTimer(), enableSystickTimer(), setCockSource(), and SYS_CLK.
Referenced by initialize().
wait()
void wait (uint32_t base_period)
Definition at line 16 of file delay.c.
References isCountZero(), setCurrentValue(), and setReloadValue().
Referenced by delay_ms(), and delay_us().
Variable Documentation
SYS_CLK
uint32_t SYS_CLK = 8
Definition at line 3 of file delay.c.
Referenced by delay_ms(), delay_us(), and delays_init().