Learn-ARM: /home/ubuntu/Desktop/repositories/learn-arm/src/c/lib/source/afio.c File Reference
afio.c File Reference
#include "../include/afio.h"
Functions
void setEXTIxCFG (uint8_t src, uint32_t cfg)
uint8_t getEXTIxCFG (uint8_t src)
void setEVOE (bool state)
void setADC2_ETRGREG_REMAP (bool state)
void setADC2_ETRGINJ_REMAP (bool state)
void setADC1_ETRGREG_REMAP (bool state)
void setADC1_ETRGINJ_REMAP (bool state)
void setPDO1_REMAP (bool state)
void setTIM4_REMAP (bool state)
void setUSART2_REMAP (bool state)
void setUSART1_REMAP (bool state)
void setI2C1_REMAP (bool state)
void setSPI1_REMAP (bool state)
bool getEVOE (void)
bool getADC2_ETRGREG_REMAP (void)
bool getADC2_ETRGINJ_REMAP (void)
bool getADC1_ETRGREG_REMAP (void)
bool getADC1_ETRGINJ_REMAP (void)
bool getPDO1_REMAP (void)
bool getTIM4_REMAP (void)
bool getUSART2_REMAP (void)
bool getUSART1_REMAP (void)
bool getTI2C1_REMAP (void)
bool getSPI1_REMAP (void)
void setPORT (uint32_t value)
void setPIN (uint32_t value)
void setSWJ_CFG (uint32_t value)
void setCAN_REMAP (uint32_t value)
void setTIM3_REMAP (uint32_t value)
void setTIM2_REMAP (uint32_t value)
void setTIM1_REMAP (uint32_t value)
void setUSART3_REMAP (uint32_t value)
uint32_t getPORT (void)
uint32_t getPIN (void)
uint32_t getSWJ_CFG (void)
uint32_t getCAN_REMAP (void)
uint32_t getTIM3_REMAP (void)
uint32_t getTIM2_REMAP (void)
uint32_t getTIM1_REMAP (void)
uint32_t getUSART3_REMAP (void)
Variables
uint32_t * AFIO_EVCR = (uint32_t*)(AFIO_BASE + 0X00)
uint32_t * AFIO_MAPR = (uint32_t*)(AFIO_BASE + 0X04)
uint32_t * AFIO_EXTICR1 = (uint32_t*)(AFIO_BASE + 0X08)
uint32_t * AFIO_EXTICR2 = (uint32_t*)(AFIO_BASE + 0X0C)
uint32_t * AFIO_EXTICR3 = (uint32_t*)(AFIO_BASE + 0X10)
uint32_t * AFIO_EXTICR4 = (uint32_t*)(AFIO_BASE + 0X14)
Function Documentation
getADC1_ETRGINJ_REMAP()
bool getADC1_ETRGINJ_REMAP (void)
Definition at line 173 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_ADC1_ETRIGINJ_REMAP.
getADC1_ETRGREG_REMAP()
bool getADC1_ETRGREG_REMAP (void)
Definition at line 168 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_ADC1_ETRIGREG_REMAP.
getADC2_ETRGINJ_REMAP()
bool getADC2_ETRGINJ_REMAP (void)
Definition at line 163 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_ADC2_ETRIGINJ_REMAP.
getADC2_ETRGREG_REMAP()
bool getADC2_ETRGREG_REMAP (void)
Definition at line 158 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_ADC2_ETRIGREG_REMAP.
getCAN_REMAP()
uint32_t getCAN_REMAP (void)
Definition at line 267 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_CAN_REMAP.
getEVOE()
bool getEVOE (void)
Definition at line 153 of file afio.c.
References AFIO_EVCR, and AFIO_EVCR_EVOE.
getEXTIxCFG()
uint8_t getEXTIxCFG (uint8_t src)
Definition at line 35 of file afio.c.
References AFIO_EXTICR1.
getPDO1_REMAP()
bool getPDO1_REMAP (void)
Definition at line 178 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_PDO1_REMAP.
getPIN()
uint32_t getPIN (void)
Definition at line 257 of file afio.c.
References AFIO_EVCR, and AFIO_EVCR_PIN.
getPORT()
uint32_t getPORT (void)
Definition at line 252 of file afio.c.
References AFIO_EVCR, and AFIO_EVCR_PORT.
getSPI1_REMAP()
bool getSPI1_REMAP (void)
Definition at line 203 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_SPI_REMAP.
getSWJ_CFG()
uint32_t getSWJ_CFG (void)
Definition at line 262 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_SWJ_CFG.
getTI2C1_REMAP()
bool getTI2C1_REMAP (void)
Definition at line 198 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_I2C1_REMAP.
getTIM1_REMAP()
uint32_t getTIM1_REMAP (void)
Definition at line 282 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_TIM1_REMAP.
getTIM2_REMAP()
uint32_t getTIM2_REMAP (void)
Definition at line 277 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_TIM2_REMAP.
getTIM3_REMAP()
uint32_t getTIM3_REMAP (void)
Definition at line 272 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_TIM3_REMAP.
getTIM4_REMAP()
bool getTIM4_REMAP (void)
Definition at line 183 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_TIM4_REMAP.
getUSART1_REMAP()
bool getUSART1_REMAP (void)
Definition at line 193 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_USART1_REMAP.
getUSART2_REMAP()
bool getUSART2_REMAP (void)
Definition at line 188 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_USART2_REMAP.
getUSART3_REMAP()
uint32_t getUSART3_REMAP (void)
Definition at line 287 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_USART3_REMAP.
setADC1_ETRGINJ_REMAP()
void setADC1_ETRGINJ_REMAP (bool state)
Definition at line 95 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_ADC1_ETRIGINJ_REMAP.
setADC1_ETRGREG_REMAP()
void setADC1_ETRGREG_REMAP (bool state)
Definition at line 87 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_ADC1_ETRIGREG_REMAP.
setADC2_ETRGINJ_REMAP()
void setADC2_ETRGINJ_REMAP (bool state)
Definition at line 79 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_ADC2_ETRIGINJ_REMAP.
setADC2_ETRGREG_REMAP()
void setADC2_ETRGREG_REMAP (bool state)
Definition at line 71 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_ADC2_ETRIGREG_REMAP.
setCAN_REMAP()
void setCAN_REMAP (uint32_t value)
Definition at line 225 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_CAN_REMAP.
setEVOE()
void setEVOE (bool state)
Definition at line 63 of file afio.c.
References AFIO_EVCR, and AFIO_EVCR_EVOE.
setEXTIxCFG()
void setEXTIxCFG (uint8_t src, uint32_t cfg)
Definition at line 10 of file afio.c.
References AFIO_EXTICR1, AFIO_EXTICR2, AFIO_EXTICR3, and AFIO_EXTICR4.
setI2C1_REMAP()
void setI2C1_REMAP (bool state)
Definition at line 135 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_I2C1_REMAP.
setPDO1_REMAP()
void setPDO1_REMAP (bool state)
Definition at line 103 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_PDO1_REMAP.
setPIN()
void setPIN (uint32_t value)
Definition at line 215 of file afio.c.
References AFIO_EVCR, and AFIO_EVCR_PIN.
setPORT()
void setPORT (uint32_t value)
Definition at line 210 of file afio.c.
References AFIO_EVCR, and AFIO_EVCR_PORT.
setSPI1_REMAP()
void setSPI1_REMAP (bool state)
Definition at line 143 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_SPI_REMAP.
setSWJ_CFG()
void setSWJ_CFG (uint32_t value)
Definition at line 220 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_SWJ_CFG.
setTIM1_REMAP()
void setTIM1_REMAP (uint32_t value)
Definition at line 240 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_TIM1_REMAP.
setTIM2_REMAP()
void setTIM2_REMAP (uint32_t value)
Definition at line 235 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_TIM2_REMAP.
setTIM3_REMAP()
void setTIM3_REMAP (uint32_t value)
Definition at line 230 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_TIM3_REMAP.
setTIM4_REMAP()
void setTIM4_REMAP (bool state)
Definition at line 111 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_TIM4_REMAP.
setUSART1_REMAP()
void setUSART1_REMAP (bool state)
Definition at line 127 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_USART1_REMAP.
setUSART2_REMAP()
void setUSART2_REMAP (bool state)
Definition at line 119 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_USART2_REMAP.
setUSART3_REMAP()
void setUSART3_REMAP (uint32_t value)
Definition at line 245 of file afio.c.
References AFIO_MAPR, and AFIO_MAPR_USART3_REMAP.
Variable Documentation
AFIO_EVCR
uint32_t* AFIO_EVCR = (uint32_t*)(AFIO_BASE + 0X00)
Definition at line 3 of file afio.c.
Referenced by getEVOE(), getPIN(), getPORT(), setEVOE(), setPIN(), and setPORT().
AFIO_EXTICR1
uint32_t* AFIO_EXTICR1 = (uint32_t*)(AFIO_BASE + 0X08)
Definition at line 5 of file afio.c.
Referenced by getEXTIxCFG(), and setEXTIxCFG().
AFIO_EXTICR2
uint32_t* AFIO_EXTICR2 = (uint32_t*)(AFIO_BASE + 0X0C)
Definition at line 6 of file afio.c.
Referenced by setEXTIxCFG().
AFIO_EXTICR3
uint32_t* AFIO_EXTICR3 = (uint32_t*)(AFIO_BASE + 0X10)
Definition at line 7 of file afio.c.
Referenced by setEXTIxCFG().
AFIO_EXTICR4
uint32_t* AFIO_EXTICR4 = (uint32_t*)(AFIO_BASE + 0X14)
Definition at line 8 of file afio.c.
Referenced by setEXTIxCFG().
AFIO_MAPR
uint32_t* AFIO_MAPR = (uint32_t*)(AFIO_BASE + 0X04)
Definition at line 4 of file afio.c.
Referenced by getADC1_ETRGINJ_REMAP(), getADC1_ETRGREG_REMAP(), getADC2_ETRGINJ_REMAP(), getADC2_ETRGREG_REMAP(), getCAN_REMAP(), getPDO1_REMAP(), getSPI1_REMAP(), getSWJ_CFG(), getTI2C1_REMAP(), getTIM1_REMAP(), getTIM2_REMAP(), getTIM3_REMAP(), getTIM4_REMAP(), getUSART1_REMAP(), getUSART2_REMAP(), getUSART3_REMAP(), setADC1_ETRGINJ_REMAP(), setADC1_ETRGREG_REMAP(), setADC2_ETRGINJ_REMAP(), setADC2_ETRGREG_REMAP(), setCAN_REMAP(), setI2C1_REMAP(), setPDO1_REMAP(), setSPI1_REMAP(), setSWJ_CFG(), setTIM1_REMAP(), setTIM2_REMAP(), setTIM3_REMAP(), setTIM4_REMAP(), setUSART1_REMAP(), setUSART2_REMAP(), and setUSART3_REMAP().