Learn-ARM: main.h File Reference
main.h File Reference
This header file contains all the function declarations for main.
#include <stdint.h>
#include "jlx12864g-086.h"
#include "flash.h"
#include "rcc.h"
#include "spi.h"
#include "gpio.h"
#include "delay.h"
#include "exti.h"
#include "nvic.h"
#include "timers.h"
Macros
#define SYS_CLK 72
System clock setting.
Functions
void initialize (void)
System initialization.
void configureSystemClock (void)
System clock confoguration.
void configureTimer1 (void)
Timer 1 confoguration.
Detailed Description
This header file contains all the function declarations for main.
Author
Mark R. Jennings mbede.nosp@m.ce@g.nosp@m.mail..nosp@m.com
Date
Auguts 8, 2020
Version
1.0
Definition in file main.h.
Macro Definition Documentation
SYS_CLK
#define SYS_CLK 72
System clock setting.
This macro is the default setting for the MCU system clock. This is the max value allowed for the STM32f103c8t6.
Definition at line 30 of file main.h.
Function Documentation
configureSystemClock()
void configureSystemClock (void)
System clock confoguration.
This function configures the system clock to 72 MHz. APB2 clock = 72 MHz and APB1 clcok = 36 MHz. HSE clock is 8 MHz and prescaler = 9
Definition at line 111 of file main.c.
Referenced by initialize().
configureTimer1()
void configureTimer1 (void)
Timer 1 confoguration.
This function configures timer 1 to count down from 75 ms in order to debouce the push button
See also
TIM1_UP_Handler()
EXTI9_5_Handler()
Definition at line 45 of file main.c.
References prescaler, and timerValue.
Referenced by initialize().
initialize()
void initialize (void)
System initialization.
This function perform all initialization tasks such as the configuration of the system clock, enabling peripheral clocks, enabling peripherals, etc.
Note
The system clcok at this time can only be configured for two speeds
8 MHz
72 MHz
Attention
To configure the system clock for 8 MHz simply change the value of SYS_CLK to 8 and do not call configureSystemClock
Definition at line 93 of file main.c.
References configureSystemClock(), configureTimer1(), and SYS_CLK.
Referenced by main().