Learn-ARM: /home/ubuntu/Desktop/repositories/learn-arm/src/c/lib/include/delay.h File Reference
delay.h File Reference
This header file contains all the function declarations for the LCD module.
#include "systick.h"
#include <stdint.h>
#include <stdbool.h>
Functions
void delays_init (uint32_t sys_clk)
Deley configuratio.
void wait (uint32_t)
void delay_ms (uint32_t)
void delay_us (uint32_t)
Variables
uint32_t SYS_CLK
variable to store value of system clock
Detailed Description
This header file contains all the function declarations for the LCD module.
Author
Mark R. Jennings mbede.nosp@m.ce@g.nosp@m.mail..nosp@m.com
Date
Auguts 2, 2020
Version
1.0
Definition in file delay.h.
Function Documentation
delay_ms()
void delay_ms (uint32_t)
Definition at line 23 of file delay.c.
References SYS_CLK, and wait().
delay_us()
void delay_us (uint32_t)
Definition at line 29 of file delay.c.
References SYS_CLK, and wait().
Referenced by trigger().
delays_init()
void delays_init (uint32_t sys_clk)
Deley configuratio.
configures the delays to operate based on the value of the system clcok setting
Parameters
sys_clk The value of the system clock setting
Note
The default value of the system clock setting is 72 MHz
See also
main.h
Definition at line 5 of file delay.c.
References CLK_PROCESSOR, disableException(), disableSystickTimer(), enableSystickTimer(), setCockSource(), and SYS_CLK.
Referenced by initialize().
wait()
void wait (uint32_t)
Definition at line 16 of file delay.c.
References isCountZero(), setCurrentValue(), and setReloadValue().
Referenced by delay_ms(), and delay_us().
Variable Documentation
SYS_CLK
uint32_t SYS_CLK
variable to store value of system clock
Definition at line 17 of file delay.h.