Learn-ARM: /home/ubuntu/Desktop/repositories/learn-arm/src/c/lib/source/nvic.c File Reference
nvic.c File Reference
#include "../include/nvic.h"
Functions
void enableIRQ (uint32_t irq)
void disableIRQ (uint32_t irq)
Variables
uint32_t * NVIC_ISER0 =(uint32_t*)0xE000E100
uint32_t * NVIC_ISER1 =(uint32_t*)0xE000E104
uint32_t * NVIC_ICER0 = (uint32_t*)0xE000E180
uint32_t * NVIC_ICER1 = (uint32_t*)0xE000E180
Function Documentation
disableIRQ()
void disableIRQ (uint32_t irq)
Definition at line 26 of file nvic.c.
References NVIC_ICER0, and NVIC_ICER1.
enableIRQ()
void enableIRQ (uint32_t irq)
Definition at line 9 of file nvic.c.
References NVIC_ISER0, and NVIC_ISER1.
Variable Documentation
NVIC_ICER0
uint32_t* NVIC_ICER0 = (uint32_t*)0xE000E180
Definition at line 6 of file nvic.c.
Referenced by disableIRQ().
NVIC_ICER1
uint32_t* NVIC_ICER1 = (uint32_t*)0xE000E180
Definition at line 7 of file nvic.c.
Referenced by disableIRQ().
NVIC_ISER0
uint32_t* NVIC_ISER0 =(uint32_t*)0xE000E100
Definition at line 3 of file nvic.c.
Referenced by enableIRQ().
NVIC_ISER1
uint32_t* NVIC_ISER1 =(uint32_t*)0xE000E104
Definition at line 4 of file nvic.c.
Referenced by enableIRQ().