Learn-ARM: /home/ubuntu/Desktop/repositories/learn-arm/src/c/lib/source/spi.c File Reference
spi.c File Reference
#include <stdint.h>
#include "../include/spi.h"
Functions
void enableSpiClk (void)
void enableSPI (uint32_t module)
void disableSPI (uint32_t module)
uint16_t spiTransfer (uint16_t module, uint16_t data)
void setBIDIMODE (uint32_t module, bool mode)
void setBIDIOE (uint32_t module, bool mode)
void setCRCEN (uint32_t module, bool mode)
void setCRCNEXT (uint32_t module, bool mode)
void setDFF (uint32_t module, bool mode)
void setRXONLY (uint32_t module, bool mode)
void setSSM (uint32_t module, bool mode)
void setSSI (uint32_t module, bool mode)
void setLSBFIRST (uint32_t module, bool mode)
void setBR (uint32_t module, uint32_t br)
void setMSTR (uint32_t module, bool mode)
void setCPOL (uint32_t module, bool mode)
void setCPHA (uint32_t module, bool mode)
bool getBIBIMODE (uint32_t module)
bool getBIBIOE (uint32_t module)
bool getCRCEN (uint32_t module)
bool getDFF (uint32_t module)
bool getCRCNEXT (uint32_t module)
bool getRXONLY (uint32_t module)
bool getSSM (uint32_t module)
bool getSSI (uint32_t module)
bool getLSBFIRST (uint32_t module)
bool getSPE (uint32_t module)
uint32_t getBR (uint32_t module)
bool getMSTR (uint32_t module)
bool getCPOL (uint32_t module)
bool getCPHA (uint32_t module)
void setTXEIE (uint32_t module, bool mode)
void setRXNEIE (uint32_t module, bool mode)
void setERRIE (uint32_t module, bool mode)
void setSSOE (uint32_t module, bool mode)
void setTXDMAEN (uint32_t module, bool mode)
void setRXDMAEN (uint32_t module, bool mode)
bool getTXEIE (uint32_t module)
bool getRXNEIE (uint32_t module)
bool getERRIE (uint32_t module)
bool getSSOE (uint32_t module)
bool getTXDMAEN (uint32_t module)
bool getRXDMAEN (uint32_t module)
void clearCRCERR (uint32_t module)
bool getBSY (uint32_t module)
bool getOVR (uint32_t module)
bool getMODF (uint32_t module)
bool getCRCERR (uint32_t module)
bool getUDR (uint32_t module)
bool getCHSIDE (uint32_t module)
bool getTXE (uint32_t module)
bool getRXNE (uint32_t module)
uint16_t readSPICRCPR (uint32_t module)
void writeSPICRCPR (uint32_t module, uint16_t data)
uint16_t readSPIRXCRCR (uint32_t module)
uint16_t readSPITXCRCR (uint32_t module)
Variables
uint32_t * SPI1_CR1 =(uint32_t*)0x40013000
uint32_t * SPI1_CR2 =(uint32_t*)0x40013004
uint32_t * SPI1_SR =(uint32_t*)0x40013008
uint32_t * SPI1_DR =(uint32_t*)0x4001300C
uint32_t * SPI1_CRCPR =(uint32_t*)0x40013010
uint32_t * SPI1_RXCRCR =(uint32_t*)0x40013014
uint32_t * SPI1_TXCRCR =(uint32_t*)0x40013018
uint32_t * SPI2_CR1 =(uint32_t*)0x40003800
uint32_t * SPI2_CR2 =(uint32_t*)0x40003804
uint32_t * SPI2_SR =(uint32_t*)0x40003808
uint32_t * SPI2_DR =(uint32_t*)0x4000380C
uint32_t * SPI2_CRCPR =(uint32_t*)0x40003810
uint32_t * SPI2_RXCRCR =(uint32_t*)0x40003814
uint32_t * SPI2_TXCRCR =(uint32_t*)0x40003818
Function Documentation
clearCRCERR()
void clearCRCERR (uint32_t module)
Definition at line 786 of file spi.c.
References SPI1_SR, SPI2_SR, and SPI_SR_CRCERR.
disableSPI()
void disableSPI (uint32_t module)
Definition at line 38 of file spi.c.
References SPI1_CR1, SPI1_SR, SPI2_CR1, SPI2_SR, SPI_CR1_SPE, SPI_SR_BSY, and SPI_SR_TXE.
enableSPI()
void enableSPI (uint32_t module)
Definition at line 26 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_SPE.
Referenced by sendCMD(), and sendData().
enableSpiClk()
void enableSpiClk (void)
Definition at line 21 of file spi.c.
References enablePeripheralClock(), and RCC_APB2ENR_SPI1EN.
getBIBIMODE()
bool getBIBIMODE (uint32_t module)
Definition at line 307 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_BIDIMODE.
getBIBIOE()
bool getBIBIOE (uint32_t module)
Definition at line 325 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_BIDIOE.
getBR()
uint32_t getBR (uint32_t module)
Definition at line 488 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_BR.
getBSY()
bool getBSY (uint32_t module)
Definition at line 799 of file spi.c.
References SPI1_SR, SPI2_SR, and SPI_SR_BSY.
getCHSIDE()
bool getCHSIDE (uint32_t module)
Definition at line 889 of file spi.c.
References SPI1_SR, SPI2_SR, and SPI_SR_CHSIDE.
getCPHA()
bool getCPHA (uint32_t module)
Definition at line 542 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_CPHA.
getCPOL()
bool getCPOL (uint32_t module)
Definition at line 524 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_CPOL.
getCRCEN()
bool getCRCEN (uint32_t module)
Definition at line 343 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_CRXEN.
getCRCERR()
bool getCRCERR (uint32_t module)
Definition at line 853 of file spi.c.
References SPI1_SR, SPI2_SR, and SPI_SR_CRCERR.
getCRCNEXT()
bool getCRCNEXT (uint32_t module)
Definition at line 380 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_CRCNEXT.
getDFF()
bool getDFF (uint32_t module)
Definition at line 362 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_DFF.
getERRIE()
bool getERRIE (uint32_t module)
Definition at line 706 of file spi.c.
References SPI1_CR2, SPI2_CR2, and SPI_CR2_ERRIE.
getLSBFIRST()
bool getLSBFIRST (uint32_t module)
Definition at line 452 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_LSBFIRST.
getMODF()
bool getMODF (uint32_t module)
Definition at line 835 of file spi.c.
References SPI1_SR, SPI2_SR, and SPI_SR_MODF.
getMSTR()
bool getMSTR (uint32_t module)
Definition at line 506 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_MSTR.
getOVR()
bool getOVR (uint32_t module)
Definition at line 817 of file spi.c.
References SPI1_SR, SPI2_SR, and SPI_SR_OVR.
getRXDMAEN()
bool getRXDMAEN (uint32_t module)
Definition at line 763 of file spi.c.
References SPI1_CR2, SPI2_CR2, and SPI_CR2_RXDMAEN.
getRXNE()
bool getRXNE (uint32_t module)
Definition at line 925 of file spi.c.
References SPI1_SR, SPI2_SR, and SPI_SR_RXNE.
Referenced by spiTransfer().
getRXNEIE()
bool getRXNEIE (uint32_t module)
Definition at line 688 of file spi.c.
References SPI1_CR2, SPI2_CR2, and SPI_CR2_RXNEIE.
getRXONLY()
bool getRXONLY (uint32_t module)
Definition at line 398 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_RXONLY.
getSPE()
bool getSPE (uint32_t module)
Definition at line 470 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_SPE.
getSSI()
bool getSSI (uint32_t module)
Definition at line 434 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_SSI.
getSSM()
bool getSSM (uint32_t module)
Definition at line 416 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_SSM.
getSSOE()
bool getSSOE (uint32_t module)
Definition at line 725 of file spi.c.
References SPI1_CR2, SPI2_CR2, and SPI_CR2_SSOE.
getTXDMAEN()
bool getTXDMAEN (uint32_t module)
Definition at line 744 of file spi.c.
References SPI1_CR2, SPI2_CR2, and SPI_CR2_TXDMAEN.
getTXE()
bool getTXE (uint32_t module)
Definition at line 907 of file spi.c.
References SPI1_SR, SPI2_SR, and SPI_SR_TXE.
getTXEIE()
bool getTXEIE (uint32_t module)
Definition at line 670 of file spi.c.
References SPI1_CR2, SPI2_CR2, and SPI_CR2_TXEIE.
getUDR()
bool getUDR (uint32_t module)
Definition at line 871 of file spi.c.
References SPI1_SR, SPI2_SR, and SPI_SR_UDR.
readSPICRCPR()
uint16_t readSPICRCPR (uint32_t module)
Definition at line 943 of file spi.c.
References SPI1_CRCPR, and SPI2_CRCPR.
readSPIRXCRCR()
uint16_t readSPIRXCRCR (uint32_t module)
Definition at line 971 of file spi.c.
References SPI1_RXCRCR, and SPI2_RXCRCR.
readSPITXCRCR()
uint16_t readSPITXCRCR (uint32_t module)
Definition at line 987 of file spi.c.
References SPI1_TXCRCR, and SPI2_TXCRCR.
setBIDIMODE()
void setBIDIMODE (uint32_t module, bool mode)
Definition at line 78 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_BIDIMODE.
setBIDIOE()
void setBIDIOE (uint32_t module, bool mode)
Definition at line 96 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_BIDIOE.
setBR()
void setBR (uint32_t module, uint32_t br)
Definition at line 240 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_BR.
setCPHA()
void setCPHA (uint32_t module, bool mode)
Definition at line 288 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_CPHA.
setCPOL()
void setCPOL (uint32_t module, bool mode)
Definition at line 270 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_CPOL.
setCRCEN()
void setCRCEN (uint32_t module, bool mode)
Definition at line 114 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_CRXEN.
setCRCNEXT()
void setCRCNEXT (uint32_t module, bool mode)
Definition at line 132 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_CRCNEXT.
setDFF()
void setDFF (uint32_t module, bool mode)
Definition at line 150 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_DFF.
setERRIE()
void setERRIE (uint32_t module, bool mode)
Definition at line 597 of file spi.c.
References SPI1_CR1, SPI1_CR2, SPI2_CR2, and SPI_CR2_ERRIE.
setLSBFIRST()
void setLSBFIRST (uint32_t module, bool mode)
Definition at line 222 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_LSBFIRST.
setMSTR()
void setMSTR (uint32_t module, bool mode)
Definition at line 252 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_MSTR.
setRXDMAEN()
void setRXDMAEN (uint32_t module, bool mode)
Definition at line 651 of file spi.c.
References SPI1_CR1, SPI1_CR2, SPI2_CR2, and SPI_CR2_RXDMAEN.
setRXNEIE()
void setRXNEIE (uint32_t module, bool mode)
Definition at line 579 of file spi.c.
References SPI1_CR1, SPI1_CR2, SPI2_CR2, and SPI_CR2_RXNEIE.
setRXONLY()
void setRXONLY (uint32_t module, bool mode)
Definition at line 168 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_RXONLY.
setSSI()
void setSSI (uint32_t module, bool mode)
Definition at line 204 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_SSI.
setSSM()
void setSSM (uint32_t module, bool mode)
Definition at line 186 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_SSM.
setSSOE()
void setSSOE (uint32_t module, bool mode)
Definition at line 615 of file spi.c.
References SPI1_CR1, SPI1_CR2, SPI2_CR2, and SPI_CR2_SSOE.
setTXDMAEN()
void setTXDMAEN (uint32_t module, bool mode)
Definition at line 633 of file spi.c.
References SPI1_CR1, SPI1_CR2, SPI2_CR2, and SPI_CR2_TXDMAEN.
setTXEIE()
void setTXEIE (uint32_t module, bool mode)
Definition at line 561 of file spi.c.
References SPI1_CR1, SPI1_CR2, SPI2_CR2, and SPI_CR2_TXEIE.
spiTransfer()
uint16_t spiTransfer (uint16_t module, uint16_t data)
Definition at line 54 of file spi.c.
References getRXNE(), SPI1_DR, and SPI2_DR.
writeSPICRCPR()
void writeSPICRCPR (uint32_t module, uint16_t data)
Definition at line 959 of file spi.c.
References SPI1_DR, and SPI2_DR.
Variable Documentation
SPI1_CR1
uint32_t* SPI1_CR1 =(uint32_t*)0x40013000
Definition at line 5 of file spi.c.
Referenced by disableSPI(), enableSPI(), getBIBIMODE(), getBIBIOE(), getBR(), getCPHA(), getCPOL(), getCRCEN(), getCRCNEXT(), getDFF(), getLSBFIRST(), getMSTR(), getRXONLY(), getSPE(), getSSI(), getSSM(), setBIDIMODE(), setBIDIOE(), setBR(), setCPHA(), setCPOL(), setCRCEN(), setCRCNEXT(), setDFF(), setERRIE(), setLSBFIRST(), setMSTR(), setRXDMAEN(), setRXNEIE(), setRXONLY(), setSSI(), setSSM(), setSSOE(), setTXDMAEN(), and setTXEIE().
SPI1_CR2
uint32_t* SPI1_CR2 =(uint32_t*)0x40013004
Definition at line 6 of file spi.c.
Referenced by getERRIE(), getRXDMAEN(), getRXNEIE(), getSSOE(), getTXDMAEN(), getTXEIE(), setERRIE(), setRXDMAEN(), setRXNEIE(), setSSOE(), setTXDMAEN(), and setTXEIE().
SPI1_CRCPR
uint32_t* SPI1_CRCPR =(uint32_t*)0x40013010
Definition at line 9 of file spi.c.
Referenced by readSPICRCPR().
SPI1_DR
uint32_t* SPI1_DR =(uint32_t*)0x4001300C
Definition at line 8 of file spi.c.
Referenced by spiTransfer(), and writeSPICRCPR().
SPI1_RXCRCR
uint32_t* SPI1_RXCRCR =(uint32_t*)0x40013014
Definition at line 10 of file spi.c.
Referenced by readSPIRXCRCR().
SPI1_SR
uint32_t* SPI1_SR =(uint32_t*)0x40013008
Definition at line 7 of file spi.c.
Referenced by clearCRCERR(), disableSPI(), getBSY(), getCHSIDE(), getCRCERR(), getMODF(), getOVR(), getRXNE(), getTXE(), and getUDR().
SPI1_TXCRCR
uint32_t* SPI1_TXCRCR =(uint32_t*)0x40013018
Definition at line 11 of file spi.c.
Referenced by readSPITXCRCR().
SPI2_CR1
uint32_t* SPI2_CR1 =(uint32_t*)0x40003800
Definition at line 13 of file spi.c.
Referenced by disableSPI(), enableSPI(), getBIBIMODE(), getBIBIOE(), getBR(), getCPHA(), getCPOL(), getCRCEN(), getCRCNEXT(), getDFF(), getLSBFIRST(), getMSTR(), getRXONLY(), getSPE(), getSSI(), getSSM(), setBIDIMODE(), setBIDIOE(), setBR(), setCPHA(), setCPOL(), setCRCEN(), setCRCNEXT(), setDFF(), setLSBFIRST(), setMSTR(), setRXONLY(), setSSI(), and setSSM().
SPI2_CR2
uint32_t* SPI2_CR2 =(uint32_t*)0x40003804
Definition at line 14 of file spi.c.
Referenced by getERRIE(), getRXDMAEN(), getRXNEIE(), getSSOE(), getTXDMAEN(), getTXEIE(), setERRIE(), setRXDMAEN(), setRXNEIE(), setSSOE(), setTXDMAEN(), and setTXEIE().
SPI2_CRCPR
uint32_t* SPI2_CRCPR =(uint32_t*)0x40003810
Definition at line 17 of file spi.c.
Referenced by readSPICRCPR().
SPI2_DR
uint32_t* SPI2_DR =(uint32_t*)0x4000380C
Definition at line 16 of file spi.c.
Referenced by spiTransfer(), and writeSPICRCPR().
SPI2_RXCRCR
uint32_t* SPI2_RXCRCR =(uint32_t*)0x40003814
Definition at line 18 of file spi.c.
Referenced by readSPIRXCRCR().
SPI2_SR
uint32_t* SPI2_SR =(uint32_t*)0x40003808
Definition at line 15 of file spi.c.
Referenced by clearCRCERR(), disableSPI(), getBSY(), getCHSIDE(), getCRCERR(), getMODF(), getOVR(), getRXNE(), getTXE(), and getUDR().
SPI2_TXCRCR
uint32_t* SPI2_TXCRCR =(uint32_t*)0x40003818
Definition at line 19 of file spi.c.
Referenced by readSPITXCRCR().