Learn-ARM: /home/ubuntu/Desktop/repositories/learn-arm/src/c/lib/include/gpio.h File Reference
gpio.h File Reference
This header file contains all the function declarations for the LCD module.
#include <stdint.h>
#include <stdbool.h>
Macros
#define PORTA 0
#define PORTB 1
#define PORTC 2
#define PORTD 3
#define PORTE 4
#define GPIO_PIN0 0
#define GPIO_PIN1 1
#define GPIO_PIN2 2
#define GPIO_PIN3 3
#define GPIO_PIN4 4
#define GPIO_PIN5 5
#define GPIO_PIN6 6
#define GPIO_PIN7 7
#define GPIO_PIN8 8
#define GPIO_PIN9 9
#define GPIO_PIN10 10
#define GPIO_PIN11 11
#define GPIO_PIN12 12
#define GPIO_PIN13 13
#define GPIO_PIN14 14
#define GPIO_PIN15 15
#define HIGH 1
#define LOW 0
#define MODE_INPUT 0
#define MODE_OUTPUT_10MHz 1
#define MODE_OUTPUT_2MHz 2
#define MODE_OUTPUT_50MHz 3
#define CNF_MODE_INPUT_ANALOG 0
#define CNF_MODE_INPUT_FLOAT 1
#define CNF_MODE_INPUT_PULL_UP_DN 2
#define CNF_MODE_OUTPUT_GP_PP 0
#define CNF_MODE_OUTPUT_GP_OD 1
#define CNF_MODE_OUTPUT_AF_PP 2
#define CNF_MODE_OUTPUT_AF_OD 3
#define GPIO_BASE 0x40010000
#define PORTA_BASE ((GPIO_BASE) + (0x800))
#define PORTB_BASE ((GPIO_BASE) + (0xC00))
#define PORTC_BASE ((GPIO_BASE) + (0x1000))
#define PORTD_BASE ((GPIO_BASE) + (0x1400))
#define PORTE_BASE ((GPIO_BASE) + (0x1800))
#define GPIOx_ORD0 0
#define GPIOx_ORD1 1
#define GPIOx_ORD2 2
#define GPIOx_ORD3 3
#define GPIOx_ORD4 4
#define GPIOx_ORD5 5
#define GPIOx_ORD6 6
#define GPIOx_ORD7 7
#define GPIOx_ORD8 8
#define GPIOx_ORD9 9
#define GPIOx_ORD10 10
#define GPIOx_ORD11 11
#define GPIOx_ORD12 12
#define GPIOx_ORD13 13
#define GPIOx_ORD14 14
#define GPIOx_ORD15 15
Functions
void configurePortPin (uint32_t, uint32_t, uint32_t, uint32_t)
void pinState (uint32_t, uint32_t, uint32_t)
void toggle (uint32_t, uint32_t)
bool pinState (uint32_t port, uint32_t pin)
\breif Gets the state of an IO pin This function return a boolean value indicating the current dtate of an IO pin
Variables
uint32_t * GPIOA_CRL
uint32_t * GPIOA_CRH
uint32_t * GPIOA_IDR
uint32_t * GPIOA_ORD
uint32_t * GPIOA_BSRR
uint32_t * GPIOA_BRR
uint32_t * GPIOA_LCKR
uint32_t * GPIOB_CRL
uint32_t * GPIOB_CRH
uint32_t * GPIOB_IDR
uint32_t * GPIOB_ORD
uint32_t * GPIOB_BSRR
uint32_t * GPIOB_BRR
uint32_t * GPIOB_LCKR
uint32_t * GPIOC_CRL
uint32_t * GPIOC_CRH
uint32_t * GPIOC_IDR
uint32_t * GPIOC_ORD
uint32_t * GPIOC_BSRR
uint32_t * GPIOC_BRR
uint32_t * GPIOC_LCKR
uint32_t * GPIOD_CRL
uint32_t * GPIOD_CRH
uint32_t * GPIOD_IDR
uint32_t * GPIOD_ORD
uint32_t * GPIOD_BSRR
uint32_t * GPIOD_BRR
uint32_t * GPIOD_LCKR
uint32_t * GPIOE_CRL
uint32_t * GPIOE_CRH
uint32_t * GPIOE_IDR
uint32_t * GPIOE_ORD
uint32_t * GPIOE_BSRR
uint32_t * GPIOE_BRR
uint32_t * GPIOE_LCKR
Detailed Description
This header file contains all the function declarations for the LCD module.
Author
Mark R. Jennings mbede.nosp@m.ce@g.nosp@m.mail..nosp@m.com
Date
Auguts 2, 2020
Version
1.0
Definition in file gpio.h.
Macro Definition Documentation
CNF_MODE_INPUT_ANALOG
#define CNF_MODE_INPUT_ANALOG 0
Definition at line 39 of file gpio.h.
CNF_MODE_INPUT_FLOAT
#define CNF_MODE_INPUT_FLOAT 1
Definition at line 40 of file gpio.h.
CNF_MODE_INPUT_PULL_UP_DN
#define CNF_MODE_INPUT_PULL_UP_DN 2
Definition at line 41 of file gpio.h.
CNF_MODE_OUTPUT_AF_OD
#define CNF_MODE_OUTPUT_AF_OD 3
Definition at line 46 of file gpio.h.
CNF_MODE_OUTPUT_AF_PP
#define CNF_MODE_OUTPUT_AF_PP 2
Definition at line 45 of file gpio.h.
CNF_MODE_OUTPUT_GP_OD
#define CNF_MODE_OUTPUT_GP_OD 1
Definition at line 44 of file gpio.h.
CNF_MODE_OUTPUT_GP_PP
#define CNF_MODE_OUTPUT_GP_PP 0
Definition at line 43 of file gpio.h.
GPIO_BASE
#define GPIO_BASE 0x40010000
Definition at line 49 of file gpio.h.
GPIO_PIN0
#define GPIO_PIN0 0
Definition at line 14 of file gpio.h.
GPIO_PIN1
#define GPIO_PIN1 1
Definition at line 15 of file gpio.h.
GPIO_PIN10
#define GPIO_PIN10 10
Definition at line 24 of file gpio.h.
GPIO_PIN11
#define GPIO_PIN11 11
Definition at line 25 of file gpio.h.
GPIO_PIN12
#define GPIO_PIN12 12
Definition at line 26 of file gpio.h.
GPIO_PIN13
#define GPIO_PIN13 13
Definition at line 27 of file gpio.h.
GPIO_PIN14
#define GPIO_PIN14 14
Definition at line 28 of file gpio.h.
GPIO_PIN15
#define GPIO_PIN15 15
Definition at line 29 of file gpio.h.
GPIO_PIN2
#define GPIO_PIN2 2
Definition at line 16 of file gpio.h.
GPIO_PIN3
#define GPIO_PIN3 3
Definition at line 17 of file gpio.h.
GPIO_PIN4
#define GPIO_PIN4 4
Definition at line 18 of file gpio.h.
GPIO_PIN5
#define GPIO_PIN5 5
Definition at line 19 of file gpio.h.
GPIO_PIN6
#define GPIO_PIN6 6
Definition at line 20 of file gpio.h.
GPIO_PIN7
#define GPIO_PIN7 7
Definition at line 21 of file gpio.h.
GPIO_PIN8
#define GPIO_PIN8 8
Definition at line 22 of file gpio.h.
GPIO_PIN9
#define GPIO_PIN9 9
Definition at line 23 of file gpio.h.
GPIOx_ORD0
#define GPIOx_ORD0 0
Definition at line 56 of file gpio.h.
GPIOx_ORD1
#define GPIOx_ORD1 1
Definition at line 57 of file gpio.h.
GPIOx_ORD10
#define GPIOx_ORD10 10
Definition at line 74 of file gpio.h.
GPIOx_ORD11
#define GPIOx_ORD11 11
Definition at line 75 of file gpio.h.
GPIOx_ORD12
#define GPIOx_ORD12 12
Definition at line 76 of file gpio.h.
GPIOx_ORD13
#define GPIOx_ORD13 13
Definition at line 77 of file gpio.h.
GPIOx_ORD14
#define GPIOx_ORD14 14
Definition at line 78 of file gpio.h.
GPIOx_ORD15
#define GPIOx_ORD15 15
Definition at line 79 of file gpio.h.
GPIOx_ORD2
#define GPIOx_ORD2 2
Definition at line 58 of file gpio.h.
GPIOx_ORD3
#define GPIOx_ORD3 3
Definition at line 59 of file gpio.h.
GPIOx_ORD4
#define GPIOx_ORD4 4
Definition at line 60 of file gpio.h.
GPIOx_ORD5
#define GPIOx_ORD5 5
Definition at line 61 of file gpio.h.
GPIOx_ORD6
#define GPIOx_ORD6 6
Definition at line 62 of file gpio.h.
GPIOx_ORD7
#define GPIOx_ORD7 7
Definition at line 71 of file gpio.h.
GPIOx_ORD8
#define GPIOx_ORD8 8
Definition at line 72 of file gpio.h.
GPIOx_ORD9
#define GPIOx_ORD9 9
Definition at line 73 of file gpio.h.
HIGH
#define HIGH 1
Definition at line 31 of file gpio.h.
LOW
#define LOW 0
Definition at line 32 of file gpio.h.
MODE_INPUT
#define MODE_INPUT 0
Definition at line 34 of file gpio.h.
MODE_OUTPUT_10MHz
#define MODE_OUTPUT_10MHz 1
Definition at line 35 of file gpio.h.
MODE_OUTPUT_2MHz
#define MODE_OUTPUT_2MHz 2
Definition at line 36 of file gpio.h.
MODE_OUTPUT_50MHz
#define MODE_OUTPUT_50MHz 3
Definition at line 37 of file gpio.h.
PORTA
#define PORTA 0
Definition at line 8 of file gpio.h.
PORTA_BASE
#define PORTA_BASE ((GPIO_BASE) + (0x800))
Definition at line 50 of file gpio.h.
PORTB
#define PORTB 1
Definition at line 9 of file gpio.h.
PORTB_BASE
#define PORTB_BASE ((GPIO_BASE) + (0xC00))
Definition at line 51 of file gpio.h.
PORTC
#define PORTC 2
Definition at line 10 of file gpio.h.
PORTC_BASE
#define PORTC_BASE ((GPIO_BASE) + (0x1000))
Definition at line 52 of file gpio.h.
PORTD
#define PORTD 3
Definition at line 11 of file gpio.h.
PORTD_BASE
#define PORTD_BASE ((GPIO_BASE) + (0x1400))
Definition at line 53 of file gpio.h.
PORTE
#define PORTE 4
Definition at line 12 of file gpio.h.
PORTE_BASE
#define PORTE_BASE ((GPIO_BASE) + (0x1800))
Definition at line 54 of file gpio.h.
Function Documentation
configurePortPin()
void configurePortPin (uint32_t , uint32_t , uint32_t , uint32_t)
Definition at line 50 of file gpio.c.
References GPIOA_CRH, GPIOA_CRL, GPIOB_CRH, GPIOB_CRL, GPIOC_CRH, GPIOC_CRL, GPIOD_CRH, GPIOD_CRL, GPIOE_CRH, GPIOE_CRL, PORTA, PORTB, PORTC, PORTD, and PORTE.
Referenced by HCSR04(), and initialize().
pinState() [1/2]
bool pinState (uint32_t port, uint32_t pin)
\breif Gets the state of an IO pin This function return a boolean value indicating the current dtate of an IO pin
Parameters
port The port being read
pin The IO pin under observation
pinState() [2/2]
void pinState (uint32_t , uint32_t , uint32_t)
Definition at line 126 of file gpio.c.
References GPIOA_BSRR, GPIOB_BSRR, GPIOC_BSRR, GPIOD_BSRR, GPIOE_BSRR, PORTA, PORTB, PORTC, PORTD, and PORTE.
Referenced by HCSR04(), and trigger().
toggle()
void toggle (uint32_t , uint32_t)
Definition at line 167 of file gpio.c.
References GPIOA_ORD, GPIOB_ORD, GPIOC_ORD, GPIOD_ORD, GPIOE_ORD, PORTA, PORTB, PORTC, PORTD, and PORTE.
Variable Documentation
GPIOA_BRR
uint32_t* GPIOA_BRR
Definition at line 87 of file gpio.h.
GPIOA_BSRR
uint32_t* GPIOA_BSRR
Definition at line 86 of file gpio.h.
GPIOA_CRH
uint32_t* GPIOA_CRH
Definition at line 83 of file gpio.h.
GPIOA_CRL
uint32_t* GPIOA_CRL
Definition at line 82 of file gpio.h.
GPIOA_IDR
uint32_t* GPIOA_IDR
Definition at line 84 of file gpio.h.
GPIOA_LCKR
uint32_t* GPIOA_LCKR
Definition at line 88 of file gpio.h.
GPIOA_ORD
uint32_t* GPIOA_ORD
Definition at line 85 of file gpio.h.
GPIOB_BRR
uint32_t* GPIOB_BRR
Definition at line 96 of file gpio.h.
GPIOB_BSRR
uint32_t* GPIOB_BSRR
Definition at line 95 of file gpio.h.
GPIOB_CRH
uint32_t* GPIOB_CRH
Definition at line 92 of file gpio.h.
GPIOB_CRL
uint32_t* GPIOB_CRL
Definition at line 91 of file gpio.h.
GPIOB_IDR
uint32_t* GPIOB_IDR
Definition at line 93 of file gpio.h.
GPIOB_LCKR
uint32_t* GPIOB_LCKR
Definition at line 97 of file gpio.h.
GPIOB_ORD
uint32_t* GPIOB_ORD
Definition at line 94 of file gpio.h.
GPIOC_BRR
uint32_t* GPIOC_BRR
Definition at line 105 of file gpio.h.
GPIOC_BSRR
uint32_t* GPIOC_BSRR
Definition at line 104 of file gpio.h.
GPIOC_CRH
uint32_t* GPIOC_CRH
Definition at line 101 of file gpio.h.
GPIOC_CRL
uint32_t* GPIOC_CRL
Definition at line 100 of file gpio.h.
GPIOC_IDR
uint32_t* GPIOC_IDR
Definition at line 102 of file gpio.h.
GPIOC_LCKR
uint32_t* GPIOC_LCKR
Definition at line 106 of file gpio.h.
GPIOC_ORD
uint32_t* GPIOC_ORD
Definition at line 103 of file gpio.h.
GPIOD_BRR
uint32_t* GPIOD_BRR
Definition at line 114 of file gpio.h.
GPIOD_BSRR
uint32_t* GPIOD_BSRR
Definition at line 113 of file gpio.h.
GPIOD_CRH
uint32_t* GPIOD_CRH
Definition at line 110 of file gpio.h.
GPIOD_CRL
uint32_t* GPIOD_CRL
Definition at line 109 of file gpio.h.
GPIOD_IDR
uint32_t* GPIOD_IDR
Definition at line 111 of file gpio.h.
GPIOD_LCKR
uint32_t* GPIOD_LCKR
Definition at line 115 of file gpio.h.
GPIOD_ORD
uint32_t* GPIOD_ORD
Definition at line 112 of file gpio.h.
GPIOE_BRR
uint32_t* GPIOE_BRR
Definition at line 123 of file gpio.h.
GPIOE_BSRR
uint32_t* GPIOE_BSRR
Definition at line 122 of file gpio.h.
GPIOE_CRH
uint32_t* GPIOE_CRH
Definition at line 119 of file gpio.h.
GPIOE_CRL
uint32_t* GPIOE_CRL
Definition at line 118 of file gpio.h.
GPIOE_IDR
uint32_t* GPIOE_IDR
Definition at line 120 of file gpio.h.
GPIOE_LCKR
uint32_t* GPIOE_LCKR
Definition at line 124 of file gpio.h.
GPIOE_ORD
uint32_t* GPIOE_ORD
Definition at line 121 of file gpio.h.