Learn-ARM: /home/ubuntu/Desktop/repositories/learn-arm/src/c/lib/include/spi.h File Reference
spi.h File Reference
#include <stdint.h>
#include <stdbool.h>
#include "../include/rcc.h"
Macros
#define SPI1 0
#define SPI2 1
#define SPI_CR1_BIDIMODE 15
#define SPI_CR1_BIDIOE 14
#define SPI_CR1_CRXEN 13
#define SPI_CR1_CRCNEXT 12
#define SPI_CR1_DFF 11
#define SPI_CR1_RXONLY 10
#define SPI_CR1_SSM 9
#define SPI_CR1_SSI 8
#define SPI_CR1_LSBFIRST 7
#define SPI_CR1_SPE 6
#define SPI_CR1_BR 3
#define SPI_CR1_MSTR 2
#define SPI_CR1_CPOL 1
#define SPI_CR1_CPHA 0
#define SPI_CR2_TXEIE 7
#define SPI_CR2_RXNEIE 6
#define SPI_CR2_ERRIE 5
#define SPI_CR2_SSOE 2
#define SPI_CR2_TXDMAEN 1
#define SPI_CR2_RXDMAEN 0
#define SPI_SR_BSY 7
#define SPI_SR_OVR 6
#define SPI_SR_MODF 5
#define SPI_SR_CRCERR 4
#define SPI_SR_UDR 3
#define SPI_SR_CHSIDE 2
#define SPI_SR_TXE 1
#define SPI_SR_RXNE 0
Functions
void enableSpiClk (void)
void enableSPI (uint32_t)
void disableSPI (uint32_t)
uint16_t spiTransfer (uint16_t, uint16_t)
void setBIDIMODE (uint32_t, bool)
void setBIDIOE (uint32_t, bool)
void setCRCEN (uint32_t, bool)
void setCRCNEXT (uint32_t, bool)
void setDFF (uint32_t, bool)
void setRXONLY (uint32_t, bool)
void setSSM (uint32_t, bool)
void setSSI (uint32_t, bool)
void setLSBFIRST (uint32_t, bool)
void setBR (uint32_t, uint32_t)
void setMSTR (uint32_t, bool)
void setCPOL (uint32_t, bool)
void setCPHA (uint32_t, bool)
bool getBIBIMODE (uint32_t)
bool getBIBIOE (uint32_t)
bool getCRCEN (uint32_t)
bool getCRCNEXT (uint32_t)
bool getDFF (uint32_t)
bool getRXONLY (uint32_t)
bool getSSM (uint32_t)
bool getSSI (uint32_t)
bool getLSBFIRST (uint32_t)
bool getSPE (uint32_t)
uint32_t getBR (uint32_t)
bool getMSTR (uint32_t)
bool getCPOL (uint32_t)
bool getCPHA (uint32_t)
void setTXEIE (uint32_t, bool)
void setRXNEIE (uint32_t, bool)
void setERRIE (uint32_t, bool)
void setSSOE (uint32_t, bool)
void setTXDMAEN (uint32_t, bool)
void setRXDMAEN (uint32_t, bool)
bool getTXEIE (uint32_t)
bool getRXNEIE (uint32_t)
bool getERRIE (uint32_t)
bool getSSOE (uint32_t)
bool getTXDMAEN (uint32_t)
bool getRXDMAEN (uint32_t)
void clearCRCERR (uint32_t)
bool getBSY (uint32_t)
bool getOVR (uint32_t)
bool getMODF (uint32_t)
bool getCRCERR (uint32_t)
bool getUDR (uint32_t)
bool getCHSIDE (uint32_t)
bool getTXE (uint32_t)
bool getRXNE (uint32_t)
uint16_t readSPICRCPR (uint32_t)
void writeSPICRCPR (uint32_t, uint16_t)
uint16_t readSPIRXCRCR (uint32_t)
uint16_t readSPITXCRCR (uint32_t)
Variables
uint32_t * SPI1_CR1
uint32_t * SPI1_CR2
uint32_t * SPI1_SR
uint32_t * SPI1_DR
uint32_t * SPI1_CRCPR
uint32_t * SPI1_RXCRCR
uint32_t * SPI1_TXCRCR
uint32_t * SPI2_CR1
uint32_t * SPI2_CR2
uint32_t * SPI2_SR
uint32_t * SPI2_DR
uint32_t * SPI2_CRCPR
uint32_t * SPI2_RXCRCR
uint32_t * SPI2_TXCRCR
Macro Definition Documentation
SPI1
#define SPI1 0
Definition at line 16 of file spi.h.
SPI2
#define SPI2 1
Definition at line 17 of file spi.h.
SPI_CR1_BIDIMODE
#define SPI_CR1_BIDIMODE 15
Definition at line 20 of file spi.h.
SPI_CR1_BIDIOE
#define SPI_CR1_BIDIOE 14
Definition at line 21 of file spi.h.
SPI_CR1_BR
#define SPI_CR1_BR 3
Definition at line 30 of file spi.h.
SPI_CR1_CPHA
#define SPI_CR1_CPHA 0
Definition at line 33 of file spi.h.
SPI_CR1_CPOL
#define SPI_CR1_CPOL 1
Definition at line 32 of file spi.h.
SPI_CR1_CRCNEXT
#define SPI_CR1_CRCNEXT 12
Definition at line 23 of file spi.h.
SPI_CR1_CRXEN
#define SPI_CR1_CRXEN 13
Definition at line 22 of file spi.h.
SPI_CR1_DFF
#define SPI_CR1_DFF 11
Definition at line 24 of file spi.h.
SPI_CR1_LSBFIRST
#define SPI_CR1_LSBFIRST 7
Definition at line 28 of file spi.h.
SPI_CR1_MSTR
#define SPI_CR1_MSTR 2
Definition at line 31 of file spi.h.
SPI_CR1_RXONLY
#define SPI_CR1_RXONLY 10
Definition at line 25 of file spi.h.
SPI_CR1_SPE
#define SPI_CR1_SPE 6
Definition at line 29 of file spi.h.
SPI_CR1_SSI
#define SPI_CR1_SSI 8
Definition at line 27 of file spi.h.
SPI_CR1_SSM
#define SPI_CR1_SSM 9
Definition at line 26 of file spi.h.
SPI_CR2_ERRIE
#define SPI_CR2_ERRIE 5
Definition at line 37 of file spi.h.
SPI_CR2_RXDMAEN
#define SPI_CR2_RXDMAEN 0
Definition at line 40 of file spi.h.
SPI_CR2_RXNEIE
#define SPI_CR2_RXNEIE 6
Definition at line 36 of file spi.h.
SPI_CR2_SSOE
#define SPI_CR2_SSOE 2
Definition at line 38 of file spi.h.
SPI_CR2_TXDMAEN
#define SPI_CR2_TXDMAEN 1
Definition at line 39 of file spi.h.
SPI_CR2_TXEIE
#define SPI_CR2_TXEIE 7
Definition at line 35 of file spi.h.
SPI_SR_BSY
#define SPI_SR_BSY 7
Definition at line 42 of file spi.h.
SPI_SR_CHSIDE
#define SPI_SR_CHSIDE 2
Definition at line 47 of file spi.h.
SPI_SR_CRCERR
#define SPI_SR_CRCERR 4
Definition at line 45 of file spi.h.
SPI_SR_MODF
#define SPI_SR_MODF 5
Definition at line 44 of file spi.h.
SPI_SR_OVR
#define SPI_SR_OVR 6
Definition at line 43 of file spi.h.
SPI_SR_RXNE
#define SPI_SR_RXNE 0
Definition at line 49 of file spi.h.
SPI_SR_TXE
#define SPI_SR_TXE 1
Definition at line 48 of file spi.h.
SPI_SR_UDR
#define SPI_SR_UDR 3
Definition at line 46 of file spi.h.
Function Documentation
clearCRCERR()
void clearCRCERR (uint32_t)
Definition at line 786 of file spi.c.
References SPI1_SR, SPI2_SR, and SPI_SR_CRCERR.
disableSPI()
void disableSPI (uint32_t)
Definition at line 38 of file spi.c.
References SPI1_CR1, SPI1_SR, SPI2_CR1, SPI2_SR, SPI_CR1_SPE, SPI_SR_BSY, and SPI_SR_TXE.
enableSPI()
void enableSPI (uint32_t)
Definition at line 26 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_SPE.
Referenced by sendCMD(), and sendData().
enableSpiClk()
void enableSpiClk (void)
Definition at line 21 of file spi.c.
References enablePeripheralClock(), and RCC_APB2ENR_SPI1EN.
getBIBIMODE()
bool getBIBIMODE (uint32_t)
Definition at line 307 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_BIDIMODE.
getBIBIOE()
bool getBIBIOE (uint32_t)
Definition at line 325 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_BIDIOE.
getBR()
uint32_t getBR (uint32_t)
Definition at line 488 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_BR.
getBSY()
bool getBSY (uint32_t)
Definition at line 799 of file spi.c.
References SPI1_SR, SPI2_SR, and SPI_SR_BSY.
getCHSIDE()
bool getCHSIDE (uint32_t)
Definition at line 889 of file spi.c.
References SPI1_SR, SPI2_SR, and SPI_SR_CHSIDE.
getCPHA()
bool getCPHA (uint32_t)
Definition at line 542 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_CPHA.
getCPOL()
bool getCPOL (uint32_t)
Definition at line 524 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_CPOL.
getCRCEN()
bool getCRCEN (uint32_t)
Definition at line 343 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_CRXEN.
getCRCERR()
bool getCRCERR (uint32_t)
Definition at line 853 of file spi.c.
References SPI1_SR, SPI2_SR, and SPI_SR_CRCERR.
getCRCNEXT()
bool getCRCNEXT (uint32_t)
Definition at line 380 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_CRCNEXT.
getDFF()
bool getDFF (uint32_t)
Definition at line 362 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_DFF.
getERRIE()
bool getERRIE (uint32_t)
Definition at line 706 of file spi.c.
References SPI1_CR2, SPI2_CR2, and SPI_CR2_ERRIE.
getLSBFIRST()
bool getLSBFIRST (uint32_t)
Definition at line 452 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_LSBFIRST.
getMODF()
bool getMODF (uint32_t)
Definition at line 835 of file spi.c.
References SPI1_SR, SPI2_SR, and SPI_SR_MODF.
getMSTR()
bool getMSTR (uint32_t)
Definition at line 506 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_MSTR.
getOVR()
bool getOVR (uint32_t)
Definition at line 817 of file spi.c.
References SPI1_SR, SPI2_SR, and SPI_SR_OVR.
getRXDMAEN()
bool getRXDMAEN (uint32_t)
Definition at line 763 of file spi.c.
References SPI1_CR2, SPI2_CR2, and SPI_CR2_RXDMAEN.
getRXNE()
bool getRXNE (uint32_t)
Definition at line 925 of file spi.c.
References SPI1_SR, SPI2_SR, and SPI_SR_RXNE.
Referenced by spiTransfer().
getRXNEIE()
bool getRXNEIE (uint32_t)
Definition at line 688 of file spi.c.
References SPI1_CR2, SPI2_CR2, and SPI_CR2_RXNEIE.
getRXONLY()
bool getRXONLY (uint32_t)
Definition at line 398 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_RXONLY.
getSPE()
bool getSPE (uint32_t)
Definition at line 470 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_SPE.
getSSI()
bool getSSI (uint32_t)
Definition at line 434 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_SSI.
getSSM()
bool getSSM (uint32_t)
Definition at line 416 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_SSM.
getSSOE()
bool getSSOE (uint32_t)
Definition at line 725 of file spi.c.
References SPI1_CR2, SPI2_CR2, and SPI_CR2_SSOE.
getTXDMAEN()
bool getTXDMAEN (uint32_t)
Definition at line 744 of file spi.c.
References SPI1_CR2, SPI2_CR2, and SPI_CR2_TXDMAEN.
getTXE()
bool getTXE (uint32_t)
Definition at line 907 of file spi.c.
References SPI1_SR, SPI2_SR, and SPI_SR_TXE.
getTXEIE()
bool getTXEIE (uint32_t)
Definition at line 670 of file spi.c.
References SPI1_CR2, SPI2_CR2, and SPI_CR2_TXEIE.
getUDR()
bool getUDR (uint32_t)
Definition at line 871 of file spi.c.
References SPI1_SR, SPI2_SR, and SPI_SR_UDR.
readSPICRCPR()
uint16_t readSPICRCPR (uint32_t)
Definition at line 943 of file spi.c.
References SPI1_CRCPR, and SPI2_CRCPR.
readSPIRXCRCR()
uint16_t readSPIRXCRCR (uint32_t)
Definition at line 971 of file spi.c.
References SPI1_RXCRCR, and SPI2_RXCRCR.
readSPITXCRCR()
uint16_t readSPITXCRCR (uint32_t)
Definition at line 987 of file spi.c.
References SPI1_TXCRCR, and SPI2_TXCRCR.
setBIDIMODE()
void setBIDIMODE (uint32_t , bool)
Definition at line 78 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_BIDIMODE.
setBIDIOE()
void setBIDIOE (uint32_t , bool)
Definition at line 96 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_BIDIOE.
setBR()
void setBR (uint32_t , uint32_t)
Definition at line 240 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_BR.
setCPHA()
void setCPHA (uint32_t , bool)
Definition at line 288 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_CPHA.
setCPOL()
void setCPOL (uint32_t , bool)
Definition at line 270 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_CPOL.
setCRCEN()
void setCRCEN (uint32_t , bool)
Definition at line 114 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_CRXEN.
setCRCNEXT()
void setCRCNEXT (uint32_t , bool)
Definition at line 132 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_CRCNEXT.
setDFF()
void setDFF (uint32_t , bool)
Definition at line 150 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_DFF.
setERRIE()
void setERRIE (uint32_t , bool)
Definition at line 597 of file spi.c.
References SPI1_CR1, SPI1_CR2, SPI2_CR2, and SPI_CR2_ERRIE.
setLSBFIRST()
void setLSBFIRST (uint32_t , bool)
Definition at line 222 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_LSBFIRST.
setMSTR()
void setMSTR (uint32_t , bool)
Definition at line 252 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_MSTR.
setRXDMAEN()
void setRXDMAEN (uint32_t , bool)
Definition at line 651 of file spi.c.
References SPI1_CR1, SPI1_CR2, SPI2_CR2, and SPI_CR2_RXDMAEN.
setRXNEIE()
void setRXNEIE (uint32_t , bool)
Definition at line 579 of file spi.c.
References SPI1_CR1, SPI1_CR2, SPI2_CR2, and SPI_CR2_RXNEIE.
setRXONLY()
void setRXONLY (uint32_t , bool)
Definition at line 168 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_RXONLY.
setSSI()
void setSSI (uint32_t , bool)
Definition at line 204 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_SSI.
setSSM()
void setSSM (uint32_t , bool)
Definition at line 186 of file spi.c.
References SPI1_CR1, SPI2_CR1, and SPI_CR1_SSM.
setSSOE()
void setSSOE (uint32_t , bool)
Definition at line 615 of file spi.c.
References SPI1_CR1, SPI1_CR2, SPI2_CR2, and SPI_CR2_SSOE.
setTXDMAEN()
void setTXDMAEN (uint32_t , bool)
Definition at line 633 of file spi.c.
References SPI1_CR1, SPI1_CR2, SPI2_CR2, and SPI_CR2_TXDMAEN.
setTXEIE()
void setTXEIE (uint32_t , bool)
Definition at line 561 of file spi.c.
References SPI1_CR1, SPI1_CR2, SPI2_CR2, and SPI_CR2_TXEIE.
spiTransfer()
uint16_t spiTransfer (uint16_t , uint16_t)
Definition at line 54 of file spi.c.
References getRXNE(), SPI1_DR, and SPI2_DR.
writeSPICRCPR()
void writeSPICRCPR (uint32_t , uint16_t)
Definition at line 959 of file spi.c.
References SPI1_DR, and SPI2_DR.
Variable Documentation
SPI1_CR1
uint32_t* SPI1_CR1
Definition at line 52 of file spi.h.
SPI1_CR2
uint32_t* SPI1_CR2
Definition at line 53 of file spi.h.
SPI1_CRCPR
uint32_t* SPI1_CRCPR
Definition at line 56 of file spi.h.
SPI1_DR
uint32_t* SPI1_DR
Definition at line 55 of file spi.h.
SPI1_RXCRCR
uint32_t* SPI1_RXCRCR
Definition at line 57 of file spi.h.
SPI1_SR
uint32_t* SPI1_SR
Definition at line 54 of file spi.h.
SPI1_TXCRCR
uint32_t* SPI1_TXCRCR
Definition at line 58 of file spi.h.
SPI2_CR1
uint32_t* SPI2_CR1
Definition at line 60 of file spi.h.
SPI2_CR2
uint32_t* SPI2_CR2
Definition at line 61 of file spi.h.
SPI2_CRCPR
uint32_t* SPI2_CRCPR
Definition at line 64 of file spi.h.
SPI2_DR
uint32_t* SPI2_DR
Definition at line 63 of file spi.h.
SPI2_RXCRCR
uint32_t* SPI2_RXCRCR
Definition at line 65 of file spi.h.
SPI2_SR
uint32_t* SPI2_SR
Definition at line 62 of file spi.h.
SPI2_TXCRCR
uint32_t* SPI2_TXCRCR
Definition at line 66 of file spi.h.