Learn-ARM: /home/ubuntu/Desktop/repositories/learn-arm/src/c/lib/include/rcc.h File Reference
rcc.h File Reference
This header file contains all the function declarations for the LCD module.
#include <stdint.h>
#include <stdbool.h>
Macros
#define RCC_BASE 0x40021000
#define RCC_APB1ENR_TIM2EN 0
#define RCC_APB1ENR_TIM3EN 3
#define RCC_APB1ENR_TIM4EN 4
#define RCC_APB1ENR_WWDGEN 11
#define RCC_APB1ENR_SPI2EN 14
#define RCC_APB1ENR_USART2EN 17
#define RCC_APB1ENR_USART3EN 18
#define RCC_APB1ENR_I2C1EN 21
#define RCC_APB1ENR_I2C2EN 22
#define RCC_APB2ENR_AFIOEN 32
#define RCC_APB2ENR_IOPAEN 34
#define RCC_APB2ENR_IOPBEN 35
#define RCC_APB2ENR_IOPCEN 36
#define RCC_APB2ENR_IOPDEN 37
#define RCC_APB2ENR_IOPEEN 38
#define RCC_APB2ENR_TIM1EN 43
#define RCC_APB2ENR_SPI1EN 44
#define RCC_APB2ENR_USART1EN 46
#define RCC_CR_PLLRDY 25
#define RCC_CR_PLLON 24
#define RCC_CR_CSSON 19
#define RCC_CR_HSEBYP 18
#define RCC_CR_HSERDY 17
#define RCC_CR_HSEON 16
#define RCC_CR_HSIRDY 1
#define RCC_CR_HSION 0
#define RCC_CFGR_USBPRE 22
#define RCC_CFGR_PLLMUL 18
#define RCC_CFGR_PLLXTPRE 17
#define RCC_CFGR_PLLSRC 16
#define RCC_CFGR_PPRE2 11
#define RCC_CFGR_PPRE1 8
#define RCC_CFGR_HPRE 4
#define RCC_CFGR_SWS 2
#define RCC_CFGR_SW 0
#define USB_PLL_DIVx1_5 0
#define USB_PLL_DIVx1 1
#define RCC_CFGR_PLLMULx2 0
#define RCC_CFGR_PLLMULx3 1
#define RCC_CFGR_PLLMULx4 2
#define RCC_CFGR_PLLMULx5 3
#define RCC_CFGR_PLLMULx6 4
#define RCC_CFGR_PLLMULx7 5
#define RCC_CFGR_PLLMULx8 6
#define RCC_CFGR_PLLMULx9 7
#define RCC_CFGR_PLLMULx10 8
#define RCC_CFGR_PLLMULx11 9
#define RCC_CFGR_PLLMULx12 10
#define RCC_CFGR_PLLMULx13 11
#define RCC_CFGR_PLLMULx14 12
#define RCC_CFGR_PLLMULx15 13
#define RCC_CFGR_PLLMULx16 14
#define RCC_CFGR_SW_HS1 0
#define RCC_CFGR_SW_HSE 1
#define RCC_CFGR_SW_PLL 2
#define RCC_CFGR_SYSCLK_DIVx1 0
#define RCC_CFGR_SYSCLK_DIVx2 8
#define RCC_CFGR_SYSCLK_DIVx4 9
#define RCC_CFGR_SYSCLK_DIVx8 10
#define RCC_CFGR_SYSCLK_DIVx16 11
#define RCC_CFGR_SYSCLK_DIVx64 12
#define RCC_CFGR_SYSCLK_DIVx128 13
#define RCC_CFGR_SYSCLK_DIVx256 14
#define RCC_CFGR_SYSCLK_DIVx512 15
#define RCC_CFGR_HCLK_DIVx1 0
#define RCC_CFGR_HCLK_DIVx2 4
#define RCC_CFGR_HCLK_DIVx4 5
#define RCC_CFGR_HCLK_DIVx8 6
#define RCC_CFGR_HCLK_DIVx16 7
Functions
void enablePeripheralClock (uint32_t)
bool isHSIRDY (void)
void enableHSE (void)
void disableHSE (void)
void enableHSI (void)
void disableHSI (void)
bool isHSERDY (void)
void enableCSS (void)
void disableCSS (void)
void enablePLL (void)
void disablePLL (void)
bool isPLLRDY (void)
void setSW (uint32_t)
uint32_t getSWS (void)
void setAHB_PSC (uint32_t)
void setAPB1_PSC (uint32_t)
void setAPB2_PSC (uint32_t)
void setPLLSRC (void)
void clearPLLSRC (void)
void setPLLXTPRE (void)
void clearPLLXTPRE (void)
void setPLLMULL (uint32_t)
void setUSBPRE (uint32_t)
Variables
uint32_t * RCC_CR
uint32_t * RCC_CFGR
uint32_t * RCC_APB2ENR
uint32_t * RCC_APB1ENR
Detailed Description
This header file contains all the function declarations for the LCD module.
Author
Mark R. Jennings mbede.nosp@m.ce@g.nosp@m.mail..nosp@m.com
Date
Auguts 2, 2020
Version
1.0
Definition in file rcc.h.
Macro Definition Documentation
RCC_APB1ENR_I2C1EN
#define RCC_APB1ENR_I2C1EN 21
Definition at line 24 of file rcc.h.
RCC_APB1ENR_I2C2EN
#define RCC_APB1ENR_I2C2EN 22
Definition at line 25 of file rcc.h.
RCC_APB1ENR_SPI2EN
#define RCC_APB1ENR_SPI2EN 14
Definition at line 21 of file rcc.h.
RCC_APB1ENR_TIM2EN
#define RCC_APB1ENR_TIM2EN 0
Definition at line 17 of file rcc.h.
RCC_APB1ENR_TIM3EN
#define RCC_APB1ENR_TIM3EN 3
Definition at line 18 of file rcc.h.
RCC_APB1ENR_TIM4EN
#define RCC_APB1ENR_TIM4EN 4
Definition at line 19 of file rcc.h.
RCC_APB1ENR_USART2EN
#define RCC_APB1ENR_USART2EN 17
Definition at line 22 of file rcc.h.
RCC_APB1ENR_USART3EN
#define RCC_APB1ENR_USART3EN 18
Definition at line 23 of file rcc.h.
RCC_APB1ENR_WWDGEN
#define RCC_APB1ENR_WWDGEN 11
Definition at line 20 of file rcc.h.
RCC_APB2ENR_AFIOEN
#define RCC_APB2ENR_AFIOEN 32
Definition at line 27 of file rcc.h.
RCC_APB2ENR_IOPAEN
#define RCC_APB2ENR_IOPAEN 34
Definition at line 28 of file rcc.h.
RCC_APB2ENR_IOPBEN
#define RCC_APB2ENR_IOPBEN 35
Definition at line 29 of file rcc.h.
RCC_APB2ENR_IOPCEN
#define RCC_APB2ENR_IOPCEN 36
Definition at line 30 of file rcc.h.
RCC_APB2ENR_IOPDEN
#define RCC_APB2ENR_IOPDEN 37
Definition at line 31 of file rcc.h.
RCC_APB2ENR_IOPEEN
#define RCC_APB2ENR_IOPEEN 38
Definition at line 32 of file rcc.h.
RCC_APB2ENR_SPI1EN
#define RCC_APB2ENR_SPI1EN 44
Definition at line 34 of file rcc.h.
RCC_APB2ENR_TIM1EN
#define RCC_APB2ENR_TIM1EN 43
Definition at line 33 of file rcc.h.
RCC_APB2ENR_USART1EN
#define RCC_APB2ENR_USART1EN 46
Definition at line 35 of file rcc.h.
RCC_BASE
#define RCC_BASE 0x40021000
Definition at line 15 of file rcc.h.
RCC_CFGR_HCLK_DIVx1
#define RCC_CFGR_HCLK_DIVx1 0
Definition at line 89 of file rcc.h.
RCC_CFGR_HCLK_DIVx16
#define RCC_CFGR_HCLK_DIVx16 7
Definition at line 93 of file rcc.h.
RCC_CFGR_HCLK_DIVx2
#define RCC_CFGR_HCLK_DIVx2 4
Definition at line 90 of file rcc.h.
RCC_CFGR_HCLK_DIVx4
#define RCC_CFGR_HCLK_DIVx4 5
Definition at line 91 of file rcc.h.
RCC_CFGR_HCLK_DIVx8
#define RCC_CFGR_HCLK_DIVx8 6
Definition at line 92 of file rcc.h.
RCC_CFGR_HPRE
#define RCC_CFGR_HPRE 4
Definition at line 52 of file rcc.h.
RCC_CFGR_PLLMUL
#define RCC_CFGR_PLLMUL 18
Definition at line 47 of file rcc.h.
RCC_CFGR_PLLMULx10
#define RCC_CFGR_PLLMULx10 8
Definition at line 67 of file rcc.h.
RCC_CFGR_PLLMULx11
#define RCC_CFGR_PLLMULx11 9
Definition at line 68 of file rcc.h.
RCC_CFGR_PLLMULx12
#define RCC_CFGR_PLLMULx12 10
Definition at line 69 of file rcc.h.
RCC_CFGR_PLLMULx13
#define RCC_CFGR_PLLMULx13 11
Definition at line 70 of file rcc.h.
RCC_CFGR_PLLMULx14
#define RCC_CFGR_PLLMULx14 12
Definition at line 71 of file rcc.h.
RCC_CFGR_PLLMULx15
#define RCC_CFGR_PLLMULx15 13
Definition at line 72 of file rcc.h.
RCC_CFGR_PLLMULx16
#define RCC_CFGR_PLLMULx16 14
Definition at line 73 of file rcc.h.
RCC_CFGR_PLLMULx2
#define RCC_CFGR_PLLMULx2 0
Definition at line 59 of file rcc.h.
RCC_CFGR_PLLMULx3
#define RCC_CFGR_PLLMULx3 1
Definition at line 60 of file rcc.h.
RCC_CFGR_PLLMULx4
#define RCC_CFGR_PLLMULx4 2
Definition at line 61 of file rcc.h.
RCC_CFGR_PLLMULx5
#define RCC_CFGR_PLLMULx5 3
Definition at line 62 of file rcc.h.
RCC_CFGR_PLLMULx6
#define RCC_CFGR_PLLMULx6 4
Definition at line 63 of file rcc.h.
RCC_CFGR_PLLMULx7
#define RCC_CFGR_PLLMULx7 5
Definition at line 64 of file rcc.h.
RCC_CFGR_PLLMULx8
#define RCC_CFGR_PLLMULx8 6
Definition at line 65 of file rcc.h.
RCC_CFGR_PLLMULx9
#define RCC_CFGR_PLLMULx9 7
Definition at line 66 of file rcc.h.
RCC_CFGR_PLLSRC
#define RCC_CFGR_PLLSRC 16
Definition at line 49 of file rcc.h.
RCC_CFGR_PLLXTPRE
#define RCC_CFGR_PLLXTPRE 17
Definition at line 48 of file rcc.h.
RCC_CFGR_PPRE1
#define RCC_CFGR_PPRE1 8
Definition at line 51 of file rcc.h.
RCC_CFGR_PPRE2
#define RCC_CFGR_PPRE2 11
Definition at line 50 of file rcc.h.
RCC_CFGR_SW
#define RCC_CFGR_SW 0
Definition at line 54 of file rcc.h.
RCC_CFGR_SW_HS1
#define RCC_CFGR_SW_HS1 0
Definition at line 75 of file rcc.h.
RCC_CFGR_SW_HSE
#define RCC_CFGR_SW_HSE 1
Definition at line 76 of file rcc.h.
RCC_CFGR_SW_PLL
#define RCC_CFGR_SW_PLL 2
Definition at line 77 of file rcc.h.
RCC_CFGR_SWS
#define RCC_CFGR_SWS 2
Definition at line 53 of file rcc.h.
RCC_CFGR_SYSCLK_DIVx1
#define RCC_CFGR_SYSCLK_DIVx1 0
Definition at line 79 of file rcc.h.
RCC_CFGR_SYSCLK_DIVx128
#define RCC_CFGR_SYSCLK_DIVx128 13
Definition at line 85 of file rcc.h.
RCC_CFGR_SYSCLK_DIVx16
#define RCC_CFGR_SYSCLK_DIVx16 11
Definition at line 83 of file rcc.h.
RCC_CFGR_SYSCLK_DIVx2
#define RCC_CFGR_SYSCLK_DIVx2 8
Definition at line 80 of file rcc.h.
RCC_CFGR_SYSCLK_DIVx256
#define RCC_CFGR_SYSCLK_DIVx256 14
Definition at line 86 of file rcc.h.
RCC_CFGR_SYSCLK_DIVx4
#define RCC_CFGR_SYSCLK_DIVx4 9
Definition at line 81 of file rcc.h.
RCC_CFGR_SYSCLK_DIVx512
#define RCC_CFGR_SYSCLK_DIVx512 15
Definition at line 87 of file rcc.h.
RCC_CFGR_SYSCLK_DIVx64
#define RCC_CFGR_SYSCLK_DIVx64 12
Definition at line 84 of file rcc.h.
RCC_CFGR_SYSCLK_DIVx8
#define RCC_CFGR_SYSCLK_DIVx8 10
Definition at line 82 of file rcc.h.
RCC_CFGR_USBPRE
#define RCC_CFGR_USBPRE 22
Definition at line 46 of file rcc.h.
RCC_CR_CSSON
#define RCC_CR_CSSON 19
Definition at line 39 of file rcc.h.
RCC_CR_HSEBYP
#define RCC_CR_HSEBYP 18
Definition at line 40 of file rcc.h.
RCC_CR_HSEON
#define RCC_CR_HSEON 16
Definition at line 42 of file rcc.h.
RCC_CR_HSERDY
#define RCC_CR_HSERDY 17
Definition at line 41 of file rcc.h.
RCC_CR_HSION
#define RCC_CR_HSION 0
Definition at line 44 of file rcc.h.
RCC_CR_HSIRDY
#define RCC_CR_HSIRDY 1
Definition at line 43 of file rcc.h.
RCC_CR_PLLON
#define RCC_CR_PLLON 24
Definition at line 38 of file rcc.h.
RCC_CR_PLLRDY
#define RCC_CR_PLLRDY 25
Definition at line 37 of file rcc.h.
USB_PLL_DIVx1
#define USB_PLL_DIVx1 1
Definition at line 57 of file rcc.h.
USB_PLL_DIVx1_5
#define USB_PLL_DIVx1_5 0
Definition at line 56 of file rcc.h.
Function Documentation
clearPLLSRC()
void clearPLLSRC (void)
Definition at line 116 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_PLLSRC.
clearPLLXTPRE()
void clearPLLXTPRE (void)
Definition at line 131 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_PLLXTPRE.
disableCSS()
void disableCSS (void)
Definition at line 67 of file rcc.c.
References RCC_CR, and RCC_CR_CSSON.
disableHSE()
void disableHSE (void)
Definition at line 39 of file rcc.c.
References RCC_CR, and RCC_CR_HSEON.
disableHSI()
void disableHSI (void)
Definition at line 49 of file rcc.c.
References RCC_CR, and RCC_CR_HSION.
Referenced by configureSystemClock().
disablePLL()
void disablePLL (void)
Definition at line 77 of file rcc.c.
References RCC_CR, and RCC_CR_PLLON.
enableCSS()
void enableCSS (void)
Definition at line 62 of file rcc.c.
References RCC_CR, and RCC_CR_CSSON.
enableHSE()
void enableHSE (void)
Definition at line 34 of file rcc.c.
References RCC_CR, and RCC_CR_HSEON.
Referenced by configureSystemClock().
enableHSI()
void enableHSI (void)
Definition at line 44 of file rcc.c.
References RCC_CR, and RCC_CR_HSION.
Referenced by configureSystemClock().
enablePeripheralClock()
void enablePeripheralClock (uint32_t)
Definition at line 9 of file rcc.c.
References RCC_APB1ENR, and RCC_APB2ENR.
Referenced by enableSpiClk(), enableTIMxClock(), and HCSR04().
enablePLL()
void enablePLL (void)
Definition at line 72 of file rcc.c.
References RCC_CR, and RCC_CR_PLLON.
Referenced by configureSystemClock().
getSWS()
uint32_t getSWS (void)
Definition at line 95 of file rcc.c.
References RCC_CFGR.
Referenced by configureSystemClock().
isHSERDY()
bool isHSERDY (void)
Definition at line 54 of file rcc.c.
References RCC_CR, and RCC_CR_HSERDY.
Referenced by configureSystemClock().
isHSIRDY()
bool isHSIRDY (void)
Definition at line 26 of file rcc.c.
References RCC_CR, and RCC_CR_HSIRDY.
isPLLRDY()
bool isPLLRDY (void)
Definition at line 82 of file rcc.c.
References RCC_CR, and RCC_CR_PLLRDY.
Referenced by configureSystemClock().
setAHB_PSC()
void setAHB_PSC (uint32_t)
Definition at line 101 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_HPRE.
setAPB1_PSC()
void setAPB1_PSC (uint32_t)
Definition at line 106 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_PPRE1.
Referenced by configureSystemClock().
setAPB2_PSC()
void setAPB2_PSC (uint32_t)
Definition at line 121 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_PPRE2.
setPLLMULL()
void setPLLMULL (uint32_t)
Definition at line 136 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_PLLMUL.
Referenced by configureSystemClock().
setPLLSRC()
void setPLLSRC (void)
Definition at line 111 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_PLLSRC.
Referenced by configureSystemClock().
setPLLXTPRE()
void setPLLXTPRE (void)
Definition at line 126 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_PLLXTPRE.
setSW()
void setSW (uint32_t)
Definition at line 90 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_SW.
Referenced by configureSystemClock().
setUSBPRE()
void setUSBPRE (uint32_t)
Definition at line 141 of file rcc.c.
References RCC_CFGR, RCC_CFGR_USBPRE, and USB_PLL_DIVx1.
Referenced by configureSystemClock().
Variable Documentation
RCC_APB1ENR
uint32_t* RCC_APB1ENR
Definition at line 99 of file rcc.h.
RCC_APB2ENR
uint32_t* RCC_APB2ENR
Definition at line 98 of file rcc.h.
RCC_CFGR
uint32_t* RCC_CFGR
Definition at line 97 of file rcc.h.
RCC_CR
uint32_t* RCC_CR
Definition at line 96 of file rcc.h.