Learn-ARM: /home/ubuntu/Desktop/repositories/learn-arm/src/c/lib/source/rtc.c File Reference
rtc.c File Reference
#include "../include/rtc.h"
Functions
void setOWIE (bool state)
void setALRIE (bool state)
void setSECIE (bool state)
bool getOWIE (void)
bool getALRIE (void)
bool getSECIE (void)
void setCNF (bool state)
bool getRTOFF (void)
bool getCNF (void)
bool getRSF (void)
bool getOWF (void)
bool getALRF (void)
bool getSECF (void)
Variables
uint32_t * RTC_CRH = (uint32_t*)(RTC_BASE + 0x00)
uint32_t * RTC_CRL = (uint32_t*)(RTC_BASE + 0x04)
uint32_t * RTC_PRLH = (uint32_t*)(RTC_BASE + 0x08)
uint32_t * RTC_PRLL = (uint32_t*)(RTC_BASE + 0x0C)
uint32_t * RTC_DIVH = (uint32_t*)(RTC_BASE + 0x10)
uint32_t * RTC_DIVL = (uint32_t*)(RTC_BASE + 0x14)
uint32_t * RTC_CNTH = (uint32_t*)(RTC_BASE + 0x18)
uint32_t * RTC_CNTL = (uint32_t*)(RTC_BASE + 0x1C)
uint32_t * RTC_ALRH = (uint32_t*)(RTC_BASE + 0x20)
uint32_t * RTC_ALRL = (uint32_t*)(RTC_BASE + 0x24)
Function Documentation
getALRF()
bool getALRF (void)
Definition at line 83 of file rtc.c.
References RTC_CRL, and RTC_CRL_ALRF.
getALRIE()
bool getALRIE (void)
Definition at line 44 of file rtc.c.
References RTC_CRH, and RTC_CRH_ALRIE.
getCNF()
bool getCNF (void)
Definition at line 68 of file rtc.c.
References RTC_CRL, and RTC_CRL_CNF.
getOWF()
bool getOWF (void)
Definition at line 78 of file rtc.c.
References RTC_CRL, and RTC_CRL_OWF.
getOWIE()
bool getOWIE (void)
Definition at line 39 of file rtc.c.
References RTC_CRH, and RTC_CRH_OWIE.
getRSF()
bool getRSF (void)
Definition at line 73 of file rtc.c.
References RTC_CRL, and RTC_CRL_RSF.
getRTOFF()
bool getRTOFF (void)
Definition at line 63 of file rtc.c.
References RTC_CRL, and RTC_CRL_RTOFF.
getSECF()
bool getSECF (void)
Definition at line 88 of file rtc.c.
References RTC_CRL, and RTC_CRL_SECF.
getSECIE()
bool getSECIE (void)
Definition at line 49 of file rtc.c.
References RTC_CRH, and RTC_CRH_SECIE.
setALRIE()
void setALRIE (bool state)
Definition at line 22 of file rtc.c.
References RTC_CRH, and RTC_CRH_ALRIE.
setCNF()
void setCNF (bool state)
Definition at line 55 of file rtc.c.
References RTC_CRL, and RTC_CRL_CNF.
setOWIE()
void setOWIE (bool state)
Definition at line 14 of file rtc.c.
References RTC_CRH, and RTC_CRH_OWIE.
setSECIE()
void setSECIE (bool state)
Definition at line 30 of file rtc.c.
References RTC_CRH, and RTC_CRH_SECIE.
Variable Documentation
RTC_ALRH
uint32_t* RTC_ALRH = (uint32_t*)(RTC_BASE + 0x20)
Definition at line 11 of file rtc.c.
RTC_ALRL
uint32_t* RTC_ALRL = (uint32_t*)(RTC_BASE + 0x24)
Definition at line 12 of file rtc.c.
RTC_CNTH
uint32_t* RTC_CNTH = (uint32_t*)(RTC_BASE + 0x18)
Definition at line 9 of file rtc.c.
RTC_CNTL
uint32_t* RTC_CNTL = (uint32_t*)(RTC_BASE + 0x1C)
Definition at line 10 of file rtc.c.
RTC_CRH
uint32_t* RTC_CRH = (uint32_t*)(RTC_BASE + 0x00)
Definition at line 3 of file rtc.c.
Referenced by getALRIE(), getOWIE(), getSECIE(), setALRIE(), setOWIE(), and setSECIE().
RTC_CRL
uint32_t* RTC_CRL = (uint32_t*)(RTC_BASE + 0x04)
Definition at line 4 of file rtc.c.
Referenced by getALRF(), getCNF(), getOWF(), getRSF(), getRTOFF(), getSECF(), and setCNF().
RTC_DIVH
uint32_t* RTC_DIVH = (uint32_t*)(RTC_BASE + 0x10)
Definition at line 7 of file rtc.c.
RTC_DIVL
uint32_t* RTC_DIVL = (uint32_t*)(RTC_BASE + 0x14)
Definition at line 8 of file rtc.c.
RTC_PRLH
uint32_t* RTC_PRLH = (uint32_t*)(RTC_BASE + 0x08)
Definition at line 5 of file rtc.c.
RTC_PRLL
uint32_t* RTC_PRLL = (uint32_t*)(RTC_BASE + 0x0C)
Definition at line 6 of file rtc.c.