Learn-ARM: /home/ubuntu/Desktop/repositories/learn-arm/src/c/lib/source/exti.c File Reference
exti.c File Reference
#include "../include/exti.h"
Functions
void setEXTI_IMR (uint32_t bit, bool state)
void setEXTI_EMR (uint32_t bit, bool state)
void setEXTI_RTSR (uint32_t bit, bool state)
void setEXTI_FTSR (uint32_t bit, bool state)
void setEXTI_SWIER (uint32_t bit, bool state)
void setEXTI_PR (uint32_t bit, bool state)
bool getEXTI_IMR (uint32_t bit)
bool getEXTI_EMR (uint32_t bit)
bool getEXTI_RTSR (uint32_t bit)
bool getEXTI_FTSR (uint32_t bit)
bool getEXTI_SWIER (uint32_t bit)
bool getEXTI_PR (uint32_t bit)
Variables
uint32_t * EXTI_IMR = (uint32_t*)(EXTI_BASE + 0x00)
uint32_t * EXTI_EMR = (uint32_t*)(EXTI_BASE + 0x04)
uint32_t * EXTI_RTSR = (uint32_t*)(EXTI_BASE + 0x08)
uint32_t * EXTI_FTSR = (uint32_t*)(EXTI_BASE + 0x0C)
uint32_t * EXTI_SWIER = (uint32_t*)(EXTI_BASE + 0x10)
uint32_t * EXTI_PR = (uint32_t*)(EXTI_BASE + 0x14)
Function Documentation
getEXTI_EMR()
bool getEXTI_EMR (uint32_t bit)
Definition at line 67 of file exti.c.
References EXTI_EMR.
getEXTI_FTSR()
bool getEXTI_FTSR (uint32_t bit)
Definition at line 77 of file exti.c.
References EXTI_FTSR.
getEXTI_IMR()
bool getEXTI_IMR (uint32_t bit)
Definition at line 62 of file exti.c.
References EXTI_IMR.
getEXTI_PR()
bool getEXTI_PR (uint32_t bit)
Definition at line 87 of file exti.c.
References EXTI_PR.
getEXTI_RTSR()
bool getEXTI_RTSR (uint32_t bit)
Definition at line 72 of file exti.c.
References EXTI_RTSR.
getEXTI_SWIER()
bool getEXTI_SWIER (uint32_t bit)
Definition at line 82 of file exti.c.
References EXTI_SWIER.
setEXTI_EMR()
void setEXTI_EMR (uint32_t bit, bool state)
Definition at line 21 of file exti.c.
References EXTI_EMR.
setEXTI_FTSR()
void setEXTI_FTSR (uint32_t bit, bool state)
Definition at line 37 of file exti.c.
References EXTI_FTSR.
setEXTI_IMR()
void setEXTI_IMR (uint32_t bit, bool state)
Definition at line 13 of file exti.c.
References EXTI_IMR.
setEXTI_PR()
void setEXTI_PR (uint32_t bit, bool state)
Definition at line 53 of file exti.c.
References EXTI_PR.
setEXTI_RTSR()
void setEXTI_RTSR (uint32_t bit, bool state)
Definition at line 29 of file exti.c.
References EXTI_RTSR.
setEXTI_SWIER()
void setEXTI_SWIER (uint32_t bit, bool state)
Definition at line 45 of file exti.c.
References EXTI_SWIER.
Variable Documentation
EXTI_EMR
uint32_t* EXTI_EMR = (uint32_t*)(EXTI_BASE + 0x04)
Definition at line 4 of file exti.c.
Referenced by getEXTI_EMR(), and setEXTI_EMR().
EXTI_FTSR
uint32_t* EXTI_FTSR = (uint32_t*)(EXTI_BASE + 0x0C)
Definition at line 7 of file exti.c.
Referenced by getEXTI_FTSR(), and setEXTI_FTSR().
EXTI_IMR
uint32_t* EXTI_IMR = (uint32_t*)(EXTI_BASE + 0x00)
Definition at line 3 of file exti.c.
Referenced by getEXTI_IMR(), and setEXTI_IMR().
EXTI_PR
uint32_t* EXTI_PR = (uint32_t*)(EXTI_BASE + 0x14)
Definition at line 10 of file exti.c.
Referenced by getEXTI_PR(), and setEXTI_PR().
EXTI_RTSR
uint32_t* EXTI_RTSR = (uint32_t*)(EXTI_BASE + 0x08)
Definition at line 6 of file exti.c.
Referenced by getEXTI_RTSR(), and setEXTI_RTSR().
EXTI_SWIER
uint32_t* EXTI_SWIER = (uint32_t*)(EXTI_BASE + 0x10)
Definition at line 9 of file exti.c.
Referenced by getEXTI_SWIER(), and setEXTI_SWIER().