Learn-ARM: /home/ubuntu/Desktop/repositories/learn-arm/src/c/lib/include/systick.h File Reference
systick.h File Reference
#include <stdint.h>
#include <stdbool.h>
Macros
#define SYST_CSR_COUNTFLAG 16
#define SYST_CSR_CLKSOURCE 2
#define SYST_CSR_TICKINT 1
#define SYST_CSR_ENABLE 0
#define CLK_PROCESSOR 1
#define CLK_EXTERNAL 0
Functions
bool isCountZero (void)
void setCockSource (uint32_t)
void enableSystickTimer (void)
void disableSystickTimer (void)
bool isTimerEnabled (void)
void enableException (void)
void disableException (void)
bool isExcetionEnabled (void)
void setReloadValue (uint32_t)
uint32_t getCurrentValue (void)
void setCurrentValue (uint32_t)
Variables
uint32_t * SYST_CSR
uint32_t * SYST_RVR
uint32_t * SYST_CVR
Macro Definition Documentation
CLK_EXTERNAL
#define CLK_EXTERNAL 0
Definition at line 13 of file systick.h.
CLK_PROCESSOR
#define CLK_PROCESSOR 1
Definition at line 12 of file systick.h.
SYST_CSR_CLKSOURCE
#define SYST_CSR_CLKSOURCE 2
Definition at line 8 of file systick.h.
SYST_CSR_COUNTFLAG
#define SYST_CSR_COUNTFLAG 16
Definition at line 7 of file systick.h.
SYST_CSR_ENABLE
#define SYST_CSR_ENABLE 0
Definition at line 10 of file systick.h.
SYST_CSR_TICKINT
#define SYST_CSR_TICKINT 1
Definition at line 9 of file systick.h.
Function Documentation
disableException()
void disableException (void)
Definition at line 39 of file systick.c.
References SYST_CSR, and SYST_CSR_TICKINT.
Referenced by delays_init().
disableSystickTimer()
void disableSystickTimer (void)
Definition at line 29 of file systick.c.
References SYST_CSR, and SYST_CSR_ENABLE.
Referenced by delays_init().
enableException()
void enableException (void)
Definition at line 34 of file systick.c.
References SYST_CSR, and SYST_CSR_TICKINT.
enableSystickTimer()
void enableSystickTimer (void)
Definition at line 24 of file systick.c.
References SYST_CSR, and SYST_CSR_ENABLE.
Referenced by delays_init().
getCurrentValue()
uint32_t getCurrentValue (void)
Definition at line 65 of file systick.c.
References SYST_CVR.
isCountZero()
bool isCountZero (void)
Definition at line 7 of file systick.c.
References SYST_CSR, and SYST_CSR_COUNTFLAG.
Referenced by wait().
isExcetionEnabled()
bool isExcetionEnabled (void)
Definition at line 52 of file systick.c.
References SYST_CSR, and SYST_CSR_TICKINT.
isTimerEnabled()
bool isTimerEnabled (void)
Definition at line 44 of file systick.c.
References SYST_CSR, and SYST_CSR_ENABLE.
setCockSource()
void setCockSource (uint32_t)
Definition at line 15 of file systick.c.
References CLK_PROCESSOR, SYST_CSR, and SYST_CSR_CLKSOURCE.
Referenced by delays_init().
setCurrentValue()
void setCurrentValue (uint32_t)
Definition at line 70 of file systick.c.
References SYST_CVR.
Referenced by wait().
setReloadValue()
void setReloadValue (uint32_t)
Definition at line 60 of file systick.c.
References SYST_RVR.
Referenced by wait().
Variable Documentation
SYST_CSR
uint32_t* SYST_CSR
Definition at line 15 of file systick.h.
SYST_CVR
uint32_t* SYST_CVR
Definition at line 17 of file systick.h.
SYST_RVR
uint32_t* SYST_RVR
Definition at line 16 of file systick.h.